import { scrapeSarkariResult, scrapePostDetail, type ScrapedItem, type PostSummary } from "./scraper";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Scraping sarkariresult.com...");
  const data = await scrapeSarkariResult();
  const allItems = [...data.results, ...data.admitCards, ...data.latestJobs, ...data.answerKeys, ...data.documents, ...data.admissions];

  console.log(`Found ${allItems.length} total items across all categories`);

  const seen = new Set<string>();
  const uniqueItems: ScrapedItem[] = [];
  for (const item of allItems) {
    if (!seen.has(item.url)) {
      seen.add(item.url);
      uniqueItems.push(item);
    }
  }
  console.log(`Fetching details for ${uniqueItems.length} unique posts...`);

  const postsDir = path.resolve(process.cwd(), "data", "posts");
  fs.mkdirSync(postsDir, { recursive: true });

  const CONCURRENCY = 5;
  let completed = 0;
  for (let i = 0; i < uniqueItems.length; i += CONCURRENCY) {
    const batch = uniqueItems.slice(i, i + CONCURRENCY);
    const results = await Promise.allSettled(
      batch.map((item) => scrapePostDetail(item.url))
    );
    for (let j = 0; j < results.length; j++) {
      const result = results[j];
      if (result.status === "fulfilled" && result.value) {
        const post = result.value;
        data.posts[post.slug] = {
          title: post.title,
          slug: post.slug,
          url: post.url,
          category: post.category,
          publishedDate: post.publishedDate,
          intro: post.intro,
        } as PostSummary;
        // Also inject date into the listing item
        const listingItem = uniqueItems.find((u) => u.url === post.url);
        if (listingItem) listingItem.publishedDate = post.publishedDate;
        fs.writeFileSync(path.join(postsDir, `${post.slug}.json`), JSON.stringify(post, null, 2), "utf-8");
      }
    }
    completed += batch.length;
    console.log(`  ${completed}/${uniqueItems.length} posts processed`);
  }

  console.log(`Saved ${Object.keys(data.posts).length} individual post files`);

  const outDir = path.resolve(process.cwd(), "data");
  fs.mkdirSync(outDir, { recursive: true });

  const listingOnly = {
    results: data.results,
    admitCards: data.admitCards,
    latestJobs: data.latestJobs,
    answerKeys: data.answerKeys,
    documents: data.documents,
    admissions: data.admissions,
    posts: data.posts,
    fetchedAt: data.fetchedAt,
  };

  fs.writeFileSync(path.join(outDir, "scraped.json"), JSON.stringify(data, null, 2), "utf-8");

  const tsContent = `// Auto-generated by npm run scrape - DO NOT EDIT
export const scrapedData = ${JSON.stringify(listingOnly, null, 2)} as const;
`;
  fs.writeFileSync(path.join(outDir, "scraped-data.ts"), tsContent, "utf-8");

  console.log("Saved listing to data/scraped-data.ts");
}

main().catch(console.error);
