// Auto-generated by npm run scrape - DO NOT EDIT
export const scrapedData = {
  "results": [
    {
      "title": "UP Polytechnic JEECUP Answer Key 2026",
      "url": "https://www.sarkariexam.com/up-polytechnic-jeecup-2026/",
      "category": "results",
      "slug": "up-polytechnic-jeecup-2026",
      "publishedDate": "2026-06-11T15:22:45+05:30"
    },
    {
      "title": "OFSS Bihar 11th 3rd Merit List 2026 – Soon",
      "url": "https://www.sarkariexam.com/ofss-bihar-11th-admissions-2026/",
      "category": "results",
      "slug": "ofss-bihar-11th-admissions-2026",
      "publishedDate": "2026-06-11T10:41:45+05:30"
    },
    {
      "title": "UPPSC PCS 2024 Marksheet",
      "url": "https://www.sarkariexam.com/uppsc-pcs-2024/",
      "category": "results",
      "slug": "uppsc-pcs-2024",
      "publishedDate": "2026-06-11T10:25:30+05:30"
    },
    {
      "title": "BSF Constable Tradesman PET/ PST Result 2026",
      "url": "https://www.sarkariexam.com/bsf-constable-tradesman-2025/",
      "category": "results",
      "slug": "bsf-constable-tradesman-2025",
      "publishedDate": "2026-06-10T16:18:52+05:30"
    },
    {
      "title": "UPHESC Assistant Professor 2022 Result 2026",
      "url": "https://www.sarkariexam.com/uphesc-assistant-professor-2022/",
      "category": "results",
      "slug": "uphesc-assistant-professor-2022",
      "publishedDate": "2026-06-10T02:15:44+05:30"
    },
    {
      "title": "MPESB Group 5 Paramedical Post Result 2026",
      "url": "https://www.sarkariexam.com/mpesb-group-5-paramedical-post-2026/",
      "category": "results",
      "slug": "mpesb-group-5-paramedical-post-2026",
      "publishedDate": "2026-06-10T02:09:03+05:30"
    },
    {
      "title": "NTA CUET UG Answer Key 2026 – Out",
      "url": "https://www.sarkariexam.com/nta-cuet-ug-2026/",
      "category": "results",
      "slug": "nta-cuet-ug-2026",
      "publishedDate": "2026-06-09T16:09:56+05:30"
    },
    {
      "title": "UPSSSC BCG Technician 2024 Result",
      "url": "https://www.sarkariexam.com/upsssc-bcg-technician-2024/",
      "category": "results",
      "slug": "upsssc-bcg-technician-2024",
      "publishedDate": "2026-06-09T15:18:50+05:30"
    },
    {
      "title": "UPSSSC Technical Assistant Group C 2024 Supplementary List",
      "url": "https://www.sarkariexam.com/upsssc-technical-assistant-group-c-2025/",
      "category": "results",
      "slug": "upsssc-technical-assistant-group-c-2025",
      "publishedDate": "2026-06-09T14:46:52+05:30"
    },
    {
      "title": "India Post GDS 4th Merit List 2026",
      "url": "https://www.sarkariexam.com/india-post-gds-2026/",
      "category": "results",
      "slug": "india-post-gds-2026",
      "publishedDate": "2026-06-08T22:27:56+05:30"
    },
    {
      "title": "DDA Group A, B & C Various Posts Marks 2026",
      "url": "https://www.sarkariexam.com/dda-group-a-b-c-post-2025/",
      "category": "results",
      "slug": "dda-group-a-b-c-post-2025",
      "publishedDate": "2026-06-08T14:22:39+05:30"
    },
    {
      "title": "DSSSB Advt 05/2024 Stenographer Grade-D Result 2026",
      "url": "https://www.sarkariexam.com/dsssb-various-post-result-2026/",
      "category": "results",
      "slug": "dsssb-various-post-result-2026",
      "publishedDate": "2026-06-08T14:16:33+05:30"
    },
    {
      "title": "SSC MTS / Havaldar Result 2026 – Soon",
      "url": "https://www.sarkariexam.com/ssc-mts-havaldar-2026/",
      "category": "results",
      "slug": "ssc-mts-havaldar-2026",
      "publishedDate": "2026-06-08T13:11:06+05:30"
    },
    {
      "title": "RSSB Livestock Assistant Final Result 2026 – Out",
      "url": "https://www.sarkariexam.com/rssb-livestock-assistant-2025/",
      "category": "results",
      "slug": "rssb-livestock-assistant-2025",
      "publishedDate": "2026-06-06T20:20:35+05:30"
    },
    {
      "title": "Indian Airforce Agniveer Vayu 02/2026 Enrolment List",
      "url": "https://www.sarkariexam.com/indian-airforce-agniveer-vayu-02-2026/",
      "category": "results",
      "slug": "indian-airforce-agniveer-vayu-02-2026",
      "publishedDate": "2026-06-06T10:49:54+05:30"
    },
    {
      "title": "SSC Delhi Police Head Constable Ministerial Result 2026",
      "url": "https://www.sarkariexam.com/ssc-delhi-police-hcm-2025/",
      "category": "results",
      "slug": "ssc-delhi-police-hcm-2025",
      "publishedDate": "2026-06-05T13:50:07+05:30"
    },
    {
      "title": "RSSB REET Mains Upper Teacher Result 2026 (Update)",
      "url": "https://www.sarkariexam.com/rssb-reet-mains-upper-teacher-2025/",
      "category": "results",
      "slug": "rssb-reet-mains-upper-teacher-2025",
      "publishedDate": "2026-06-05T10:15:03+05:30"
    },
    {
      "title": "NTA NCET Result / Score Card 2026",
      "url": "https://www.sarkariexam.com/nta-ncet-2026/",
      "category": "results",
      "slug": "nta-ncet-2026",
      "publishedDate": "2026-06-04T20:56:37+05:30"
    },
    {
      "title": "DECE-LE Bihar Diploma Result / Rank Card 2026 – Out",
      "url": "https://www.sarkariexam.com/dece-le-bihar-diploma-2026/",
      "category": "results",
      "slug": "dece-le-bihar-diploma-2026",
      "publishedDate": "2026-06-04T16:05:52+05:30"
    },
    {
      "title": "Bihar ITI CAT Result / Rank Card 2026 – Out",
      "url": "https://www.sarkariexam.com/bihar-iti-cat-2026/",
      "category": "results",
      "slug": "bihar-iti-cat-2026",
      "publishedDate": "2026-06-04T15:58:27+05:30"
    }
  ],
  "admitCards": [
    {
      "title": "Allahabad University PGAT Admit Card 2026",
      "url": "https://www.sarkariexam.com/allahabad-university-pgat-admissions-2026/",
      "category": "admitCards",
      "slug": "allahabad-university-pgat-admissions-2026",
      "publishedDate": "2026-06-11T11:30:57+05:30"
    },
    {
      "title": "Bihar Police CSBC Constable GD Exam City / Admit Card 2026",
      "url": "https://www.sarkariexam.com/bihar-police-csbc-constable-gd-2026/",
      "category": "admitCards",
      "slug": "bihar-police-csbc-constable-gd-2026",
      "publishedDate": "2026-06-11T11:15:33+05:30"
    },
    {
      "title": "RRB NTPC 10+2 UG CBT-I Admit Card 2026",
      "url": "https://www.sarkariexam.com/rrb-ntpc-102-inter-level-2025/",
      "category": "admitCards",
      "slug": "rrb-ntpc-102-inter-level-2025",
      "publishedDate": "2026-06-10T15:59:56+05:30"
    },
    {
      "title": "NTA UGC NET June Exam City Details 2026",
      "url": "https://www.sarkariexam.com/nta-ugc-net-june-2026/",
      "category": "admitCards",
      "slug": "nta-ugc-net-june-2026",
      "publishedDate": "2026-06-10T15:59:03+05:30"
    },
    {
      "title": "NTA NEET UG Re-Exam City Details 2026",
      "url": "https://www.sarkariexam.com/nta-neet-ug-2026/",
      "category": "admitCards",
      "slug": "nta-neet-ug-2026",
      "publishedDate": "2026-06-10T14:45:07+05:30"
    },
    {
      "title": "Indian Army Agniveer CEE Admit Card 2026",
      "url": "https://www.sarkariexam.com/indian-army-agniveer-cee-2026/",
      "category": "admitCards",
      "slug": "indian-army-agniveer-cee-2026",
      "publishedDate": "2026-06-10T14:45:03+05:30"
    },
    {
      "title": "UP GNM Entrance Exam UPGET Exam City Details 2026",
      "url": "https://www.sarkariexam.com/up-gnm-entrance-exam-upget-2026/",
      "category": "admitCards",
      "slug": "up-gnm-entrance-exam-upget-2026",
      "publishedDate": "2026-06-10T13:20:26+05:30"
    },
    {
      "title": "SSB Head Constable Ministerial Written Exam Date 2026",
      "url": "https://www.sarkariexam.com/ssb-head-constable-ministerial-2021/",
      "category": "admitCards",
      "slug": "ssb-head-constable-ministerial-2021",
      "publishedDate": "2026-06-10T02:22:15+05:30"
    },
    {
      "title": "UPSSSC Forest/ WildLife Guard 2023 Medical Admit Card 2026",
      "url": "https://www.sarkariexam.com/upsssc-forest-guard-wild-guard-2023/",
      "category": "admitCards",
      "slug": "upsssc-forest-guard-wild-guard-2023",
      "publishedDate": "2026-06-09T15:02:04+05:30"
    },
    {
      "title": "UP LT Grade Assistant Teacher Mains Admit Card 2026 (Update)",
      "url": "https://www.sarkariexam.com/up-lt-grade-assistant-teacher-2025/",
      "category": "admitCards",
      "slug": "up-lt-grade-assistant-teacher-2025",
      "publishedDate": "2026-06-09T11:38:19+05:30"
    },
    {
      "title": "NTA SWAYAM Exam City Details 2026",
      "url": "https://www.sarkariexam.com/nta-swayam-2026/",
      "category": "admitCards",
      "slug": "nta-swayam-2026",
      "publishedDate": "2026-06-09T11:37:19+05:30"
    },
    {
      "title": "UKSSSC VDO, Patwari & Other Post Admit Card 2026",
      "url": "https://www.sarkariexam.com/uksssc-vdo-patwari-other-post-2025/",
      "category": "admitCards",
      "slug": "uksssc-vdo-patwari-other-post-2025",
      "publishedDate": "2026-06-09T11:11:14+05:30"
    },
    {
      "title": "Bihar Vidhan Parishad Security Guard Interview Admit Card 2026",
      "url": "https://www.sarkariexam.com/bihar-vidhan-parishad-2023/",
      "category": "admitCards",
      "slug": "bihar-vidhan-parishad-2023",
      "publishedDate": "2026-06-09T10:41:02+05:30"
    },
    {
      "title": "Rajasthan PTET Admit Card 2026",
      "url": "https://www.sarkariexam.com/rajasthan-ptet-2026/",
      "category": "admitCards",
      "slug": "rajasthan-ptet-2026",
      "publishedDate": "2026-06-08T14:36:37+05:30"
    },
    {
      "title": "Bihar Police Prohibition Constable Admit Card 2026",
      "url": "https://www.sarkariexam.com/bihar-police-csbc-prohibition-constable-2025/",
      "category": "admitCards",
      "slug": "bihar-police-csbc-prohibition-constable-2025",
      "publishedDate": "2026-06-08T10:19:52+05:30"
    },
    {
      "title": "Bihar BPSC AES Admit Card 2026",
      "url": "https://www.sarkariexam.com/bihar-bpsc-aes-2025/",
      "category": "admitCards",
      "slug": "bihar-bpsc-aes-2025",
      "publishedDate": "2026-06-08T10:19:45+05:30"
    },
    {
      "title": "Bihar BPSC Stenographer Admit Card 2026",
      "url": "https://www.sarkariexam.com/bpsc-stenographer-2026/",
      "category": "admitCards",
      "slug": "bpsc-stenographer-2026",
      "publishedDate": "2026-06-08T10:19:40+05:30"
    },
    {
      "title": "UPSSSC Pharmacist Mains Exam Fee Payment 2026",
      "url": "https://www.sarkariexam.com/upsssc-pharmacist-2026/",
      "category": "admitCards",
      "slug": "upsssc-pharmacist-2026",
      "publishedDate": "2026-06-07T14:17:34+05:30"
    },
    {
      "title": "SGPGI Nursing Officer & Other Post Exam City Details 2026",
      "url": "https://www.sarkariexam.com/sgpgi-nursing-officer-and-non-teaching-post-2025/",
      "category": "admitCards",
      "slug": "sgpgi-nursing-officer-and-non-teaching-post-2025",
      "publishedDate": "2026-06-07T13:38:32+05:30"
    },
    {
      "title": "BSF HCM & ASI Steno Exam Date 2026",
      "url": "https://www.sarkariexam.com/bsf-hcm-asi-steno-2024/",
      "category": "admitCards",
      "slug": "bsf-hcm-asi-steno-2024",
      "publishedDate": "2026-06-06T10:40:28+05:30"
    }
  ],
  "latestJobs": [
    {
      "title": "RRB ALP CEN 01/2026 Online Form 2026 (11,127 Posts)",
      "url": "https://www.sarkariexam.com/rrb-alp-cen-01-2026/",
      "category": "latestJobs",
      "slug": "rrb-alp-cen-01-2026",
      "publishedDate": "2026-06-11T13:14:26+05:30"
    },
    {
      "title": "SSC CGL 2026 Online Form (12,256 Posts)",
      "url": "https://www.sarkariexam.com/ssc-cgl-2026/",
      "category": "latestJobs",
      "slug": "ssc-cgl-2026",
      "publishedDate": "2026-06-11T13:14:16+05:30"
    },
    {
      "title": "Coal India CIL Management Trainee Online Form 2026 – Extend",
      "url": "https://www.sarkariexam.com/coal-india-cil-management-trainee-2026/",
      "category": "latestJobs",
      "slug": "coal-india-cil-management-trainee-2026",
      "publishedDate": "2026-06-11T13:13:21+05:30"
    },
    {
      "title": "UPSSSC Agriculture Technical Assistant Group-C Online Form 2026 – Last Date",
      "url": "https://www.sarkariexam.com/upsssc-agriculture-technical-assistant-group-c-2026/",
      "category": "latestJobs",
      "slug": "upsssc-agriculture-technical-assistant-group-c-2026",
      "publishedDate": "2026-06-11T13:13:11+05:30"
    },
    {
      "title": "UPSC NDA/ NA-II Online Form 2026 – Last Date",
      "url": "https://www.sarkariexam.com/upsc-nda-na-ii-2026/",
      "category": "latestJobs",
      "slug": "upsc-nda-na-ii-2026",
      "publishedDate": "2026-06-11T13:13:05+05:30"
    },
    {
      "title": "UPSC CDS-II Online Form 2026  – Last Date",
      "url": "https://www.sarkariexam.com/upsc-cds-ii-2026/",
      "category": "latestJobs",
      "slug": "upsc-cds-ii-2026",
      "publishedDate": "2026-06-11T13:13:01+05:30"
    },
    {
      "title": "Railway SECR Bilaspur Apprentices Online Form 2026 (1191 Posts) – Last Date",
      "url": "https://www.sarkariexam.com/railway-rrc-secr-bilaspur-apprentice-2026/",
      "category": "latestJobs",
      "slug": "railway-rrc-secr-bilaspur-apprentice-2026",
      "publishedDate": "2026-06-11T13:12:55+05:30"
    },
    {
      "title": "Indian Army TGC 144 Online Form 2026 – Last Date",
      "url": "https://www.sarkariexam.com/indian-army-tgc-144-2026/",
      "category": "latestJobs",
      "slug": "indian-army-tgc-144-2026",
      "publishedDate": "2026-06-11T13:12:51+05:30"
    },
    {
      "title": "SSC Junior Engineer JE Online Post Preference Form 2026",
      "url": "https://www.sarkariexam.com/ssc-junior-engineer-je-2025/",
      "category": "latestJobs",
      "slug": "ssc-junior-engineer-je-2025",
      "publishedDate": "2026-06-11T13:11:54+05:30"
    },
    {
      "title": "Allahabad High Court RO, ARO & CA Online Form 2026",
      "url": "https://www.sarkariexam.com/allahabad-high-court-ro-aro-ca-2026/",
      "category": "latestJobs",
      "slug": "allahabad-high-court-ro-aro-ca-2026",
      "publishedDate": "2026-06-11T10:10:17+05:30"
    },
    {
      "title": "UPSSSC Lower PCS 2026 Online Form (2516 Posts)",
      "url": "https://www.sarkariexam.com/upsssc-lower-pcs-2026/",
      "category": "latestJobs",
      "slug": "upsssc-lower-pcs-2026",
      "publishedDate": "2026-06-11T10:10:13+05:30"
    },
    {
      "title": "UPSSSC Excise Constable Online Form 2026",
      "url": "https://www.sarkariexam.com/upsssc-excise-constable-2026/",
      "category": "latestJobs",
      "slug": "upsssc-excise-constable-2026",
      "publishedDate": "2026-06-11T10:10:08+05:30"
    },
    {
      "title": "SBI Apprentice Online Form 2026 (7150 Posts) – Extend",
      "url": "https://www.sarkariexam.com/sbi-apprentice-2026/",
      "category": "latestJobs",
      "slug": "sbi-apprentice-2026",
      "publishedDate": "2026-06-11T10:10:03+05:30"
    },
    {
      "title": "Bank of Baroda Apprentices Online Form 2026 (5000 Posts) – Extend",
      "url": "https://www.sarkariexam.com/bank-of-baroda-apprentices-2026/",
      "category": "latestJobs",
      "slug": "bank-of-baroda-apprentices-2026",
      "publishedDate": "2026-06-11T10:09:59+05:30"
    },
    {
      "title": "UPSSSC Vidhan Bhawan Guard/ Fire Guard Online Form 2026",
      "url": "https://www.sarkariexam.com/upsssc-vidhan-bhawan-guard-fire-guard-2026/",
      "category": "latestJobs",
      "slug": "upsssc-vidhan-bhawan-guard-fire-guard-2026",
      "publishedDate": "2026-06-11T10:09:54+05:30"
    },
    {
      "title": "CTET September Online Form 2026",
      "url": "https://www.sarkariexam.com/ctet-september-2026/",
      "category": "latestJobs",
      "slug": "ctet-september-2026",
      "publishedDate": "2026-06-10T10:16:06+05:30"
    },
    {
      "title": "CISF ASI Paramedical Staff Online Form 2026",
      "url": "https://www.sarkariexam.com/cisf-asi-paramedical-staff-2026/",
      "category": "latestJobs",
      "slug": "cisf-asi-paramedical-staff-2026",
      "publishedDate": "2026-06-08T10:23:24+05:30"
    },
    {
      "title": "RPSC APO Online Form 2026",
      "url": "https://www.sarkariexam.com/rpsc-apo-2026/",
      "category": "latestJobs",
      "slug": "rpsc-apo-2026",
      "publishedDate": "2026-06-08T10:22:16+05:30"
    },
    {
      "title": "Hindustan Copper Limited HCL Executive Online Form 2026",
      "url": "https://www.sarkariexam.com/hindustan-copper-limited-hcl-executive-2026/",
      "category": "latestJobs",
      "slug": "hindustan-copper-limited-hcl-executive-2026",
      "publishedDate": "2026-06-07T14:00:00+05:30"
    },
    {
      "title": "UP Board Class 10th/12th Compartment Online Form 2026",
      "url": "https://www.sarkariexam.com/up-board-class-10th-12th-2026/",
      "category": "latestJobs",
      "slug": "up-board-class-10th-12th-2026",
      "publishedDate": "2026-06-06T13:02:51+05:30"
    }
  ],
  "answerKeys": [
    {
      "title": "NTA JIPMAT Answer Key 2026",
      "url": "https://www.sarkariexam.com/nta-jipmat-2026/",
      "category": "answerKeys",
      "slug": "nta-jipmat-2026",
      "publishedDate": "2026-06-11T11:11:56+05:30"
    },
    {
      "title": "UP CNET Answer Key 2026",
      "url": "https://www.sarkariexam.com/up-cnet-2026/",
      "category": "answerKeys",
      "slug": "up-cnet-2026",
      "publishedDate": "2026-06-09T15:30:15+05:30"
    },
    {
      "title": "Bihar CET B.Ed Answer Key 2026 – Out",
      "url": "https://www.sarkariexam.com/bihar-cet-b-ed-2026/",
      "category": "answerKeys",
      "slug": "bihar-cet-b-ed-2026",
      "publishedDate": "2026-06-08T22:35:46+05:30"
    },
    {
      "title": "UPPSC Assistant Professor Answer Key 2026",
      "url": "https://www.sarkariexam.com/uppsc-assistant-professor-2025/",
      "category": "answerKeys",
      "slug": "uppsc-assistant-professor-2025",
      "publishedDate": "2026-06-07T13:23:58+05:30"
    },
    {
      "title": "UP TGT 2022 Answer Key 2026",
      "url": "https://www.sarkariexam.com/up-tgt-2022/",
      "category": "answerKeys",
      "slug": "up-tgt-2022",
      "publishedDate": "2026-06-07T00:01:19+05:30"
    },
    {
      "title": "Bihar BSSC Office Attendant Mains Answer Key 2026 – Out",
      "url": "https://www.sarkariexam.com/bihar-bssc-office-attendant-2022/",
      "category": "answerKeys",
      "slug": "bihar-bssc-office-attendant-2022",
      "publishedDate": "2026-06-05T11:24:45+05:30"
    },
    {
      "title": "JCECEB Jharkhand B.Ed Answer Key 2026",
      "url": "https://www.sarkariexam.com/jceceb-jharkhand-bed-2026/",
      "category": "answerKeys",
      "slug": "jceceb-jharkhand-bed-2026",
      "publishedDate": "2026-06-04T12:35:11+05:30"
    },
    {
      "title": "RSSB REET Mains Primary Teacher Final Answer Key 2026",
      "url": "https://www.sarkariexam.com/rssb-reet-mains-primary-teacher-2025/",
      "category": "answerKeys",
      "slug": "rssb-reet-mains-primary-teacher-2025",
      "publishedDate": "2026-06-03T16:06:22+05:30"
    }
  ],
  "documents": [
    {
      "title": "Aadhar Card PVC Download, Correction, Status 2026",
      "url": "https://www.sarkariexam.com/aadhar-card-print-verification-correction-form/",
      "category": "documents",
      "slug": "aadhar-card-print-verification-correction-form",
      "publishedDate": "2026-01-05T17:18:44+05:30"
    },
    {
      "title": "PAN Card Registration, Correction & Other Service 2026",
      "url": "https://www.sarkariexam.com/pan-card-registration-correction-other-service-2026/",
      "category": "documents",
      "slug": "pan-card-registration-correction-other-service-2026",
      "publishedDate": "2026-01-05T17:18:40+05:30"
    },
    {
      "title": "Bihar Income, Cast, Residential Certificate Online Apply & Verification 2026",
      "url": "https://www.sarkariexam.com/bihar-caste-income-residence-certificate-online-form/",
      "category": "documents",
      "slug": "bihar-caste-income-residence-certificate-online-form",
      "publishedDate": "2026-01-05T17:09:48+05:30"
    },
    {
      "title": "UP Caste, Niwas, Income Certificate Online Verification 2026",
      "url": "https://www.sarkariexam.com/up-caste-niwas-income-certificate-online-verification/",
      "category": "documents",
      "slug": "up-caste-niwas-income-certificate-online-verification",
      "publishedDate": "2026-01-05T16:31:31+05:30"
    },
    {
      "title": "Voter ID Registration & Other Voter Service 2026",
      "url": "https://www.sarkariexam.com/voter-id-registration-other-voter-service-2026/",
      "category": "documents",
      "slug": "voter-id-registration-other-voter-service-2026",
      "publishedDate": "2026-01-05T14:30:50+05:30"
    }
  ],
  "admissions": [
    {
      "title": "UP DELEd Online Form 2026 – Soon",
      "url": "https://www.sarkariexam.com/up-deled-admission-2026/",
      "category": "admissions",
      "slug": "up-deled-admission-2026",
      "publishedDate": "2026-06-10T12:46:17+05:30"
    },
    {
      "title": "MPESB PNST Online Form 2026",
      "url": "https://www.sarkariexam.com/mpesb-pnst-2026/",
      "category": "admissions",
      "slug": "mpesb-pnst-2026",
      "publishedDate": "2026-06-09T15:57:50+05:30"
    },
    {
      "title": "NTA ICAR AIEEA PG, Phd Admissions Online Form 2026",
      "url": "https://www.sarkariexam.com/nta-icar-aieea-pg-phd-admissions-2026/",
      "category": "admissions",
      "slug": "nta-icar-aieea-pg-phd-admissions-2026",
      "publishedDate": "2026-06-08T15:42:19+05:30"
    },
    {
      "title": "UPTAC Admissions Online Registration 2026",
      "url": "https://www.sarkariexam.com/uptac-admissions-2026/",
      "category": "admissions",
      "slug": "uptac-admissions-2026",
      "publishedDate": "2026-06-05T13:28:23+05:30"
    }
  ],
  "posts": {
    "up-polytechnic-jeecup-2026": {
      "title": "UP Polytechnic JEECUP Answer Key 2026",
      "slug": "up-polytechnic-jeecup-2026",
      "url": "https://www.sarkariexam.com/up-polytechnic-jeecup-2026/",
      "category": "",
      "publishedDate": "2026-06-11T15:22:45+05:30",
      "intro": "Short Information : UP Joint Entrance Examination JEECUP has released the answer key for Uttar Pradesh Polytechnic Diploma Admission 2026 on its official website. Applications for the UP Polytechnic JEECUP Online Form 2026 were accepted from 15 January 2026, to 10 May 2026. The written examination is going to be conducted on 02-09 June 2026. Candidates who had applied this form can download their UP Polytechnic JEECUP Answer Key 2026 from the link given below."
    },
    "ofss-bihar-11th-admissions-2026": {
      "title": "OFSS Bihar 11th 3rd Merit List 2026",
      "slug": "ofss-bihar-11th-admissions-2026",
      "url": "https://www.sarkariexam.com/ofss-bihar-11th-admissions-2026/",
      "category": "",
      "publishedDate": "2026-06-11T10:41:45+05:30",
      "intro": "Short Information : Bihar School Examination Board (BSEB), will release the 3rd Merit List for admission in Intermediate (11th) Class 2026 through the Online Facilitation System for Students (OFSS). Candidates who applied for OFSS Bihar 11th Admission 2026 can now check their 3rd Selection List / Merit List. Students can download the intimation letter, check allotted school/college, and complete the admission process within the given time. Those Candidates who are enlisted in the 3rd Merit List can proceed for admission through the link given below."
    },
    "uppsc-pcs-2024": {
      "title": "UPPSC PCS Marksheet 2026",
      "slug": "uppsc-pcs-2024",
      "url": "https://www.sarkariexam.com/uppsc-pcs-2024/",
      "category": "",
      "publishedDate": "2026-06-11T10:25:30+05:30",
      "intro": "Short Details : Uttar Pradesh Public Service Commission UPSC, has released the marksheet for the State/ Upper Subordinate Services 2024, This recruitment was released for 220 posts. The applications for UPPSC Mains Recruitment 2025 were accepted from 07 March 2025 to 24 March 2025. The Interview was held on 16 February 2026 to 20 March 2026. Candidates who appeared for this examination can download their UPPSC PCS Marksheet 2026 from the link given below."
    },
    "bsf-constable-tradesman-2025": {
      "title": "BSF Constable Tradesman PET/ PST Result 2026",
      "slug": "bsf-constable-tradesman-2025",
      "url": "https://www.sarkariexam.com/bsf-constable-tradesman-2025/",
      "category": "",
      "publishedDate": "2026-06-10T16:18:52+05:30",
      "intro": "Short Information : Border Security Force (BSF) has released the result for the post of Constable (Tradesman). This recruitment was released for 3588 posts. Applications for the BSF Constable Tradesman Recruitment 2025 were accepted from 24 July 2025, to 26 August 2025. The PET/ PST examination was held on December 2025. Candidates who appeared for this examination can download their BSF Constable Tradesman PET/ PST Result 2026 from the link given below."
    },
    "uphesc-assistant-professor-2022": {
      "title": "UPHESC Assistant Professor Result 2026",
      "slug": "uphesc-assistant-professor-2022",
      "url": "https://www.sarkariexam.com/uphesc-assistant-professor-2022/",
      "category": "",
      "publishedDate": "2026-06-10T02:15:44+05:30",
      "intro": "Short Information : Uttar Pradesh Higher Education Service Commission (UPHESC) has released result for selection to the posts of Assistant Professor under the Advt No. : 51-2022. The vacancy came in the year 2022 and it took almost four years to conduct the written examination for the prescribed posts. The written examination was held on 18-19 April 2026. Candidates who appeared for this examination can download their UPHESC Assistant Professor Result 2026 from the link given below."
    },
    "mpesb-group-5-paramedical-post-2026": {
      "title": "MPESB Group 5 Paramedical Result 2026",
      "slug": "mpesb-group-5-paramedical-post-2026",
      "url": "https://www.sarkariexam.com/mpesb-group-5-paramedical-post-2026/",
      "category": "",
      "publishedDate": "2026-06-10T02:09:03+05:30",
      "intro": "Short Information : Madhya Pradesh Professional Selection Board (MPESB) has released the result for the recruitment of Group-5 Staff Nurse, Paramedical and Other Combined Posts. This recruitment was released for 373 posts. Applications for the MPESB Group-5 Paramedical Post Recruitment 2026 were accepted from 16 March 2026 to 30 March 2026. The online examination was held on 15 April 2026. Candidates who had appeared in this Examination can download their MPESB Group 5 Paramedical Post Result 2026 from the link given below."
    },
    "nta-cuet-ug-2026": {
      "title": "NTA CUET UG Answer Key 2026",
      "slug": "nta-cuet-ug-2026",
      "url": "https://www.sarkariexam.com/nta-cuet-ug-2026/",
      "category": "",
      "publishedDate": "2026-06-09T16:09:56+05:30",
      "intro": "Short Information : National Testing Agency (NTA) has released the answer key for the Under-Graduate Entrance Test for all Central Universities for Academic Session 2026-27 Examination on the official website of the NTA recently. Applications for the NTA CUET UG Online Form 2026 were accepted from 23 February 2026, to 26 February 2026. The online examination was held on 11-31 May 2026. Candidates who appeared for this examination can download their NTA CUET UG Answer Key 2026 from the link given below."
    },
    "upsssc-bcg-technician-2024": {
      "title": "UPSSSC BCG Technician Result 2026",
      "slug": "upsssc-bcg-technician-2024",
      "url": "https://www.sarkariexam.com/upsssc-bcg-technician-2024/",
      "category": "",
      "publishedDate": "2026-06-09T15:18:50+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Services Selection Commission (UPSSSC) has released the result for the recruitment of BCG Technician posts on the official website of UPSSSC. This recruitment was released for 255 posts. Applications for the UPSSSC BCG Technician Recruitment 2024 were accepted from 08 July 2024, to 07 August 2024. Candidates who had applied this form can download their UPSSSC BCG Technician Result 2026 from the link given below."
    },
    "upsssc-technical-assistant-group-c-2025": {
      "title": "UPSSSC Technical Assistant Group C Supplementary List 2026",
      "slug": "upsssc-technical-assistant-group-c-2025",
      "url": "https://www.sarkariexam.com/upsssc-technical-assistant-group-c-2025/",
      "category": "",
      "publishedDate": "2026-06-09T14:46:52+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Service Selection Board (UPSSSC) has released the Supplementary List for selection to the posts of Technical Assistant Group C under the Advt No. : 07-Exam/2024. The vacancy came in the year 2024 and it took almost one year tow month to conduct the written examination for the prescribed posts. UPSSSC was conduct a written examination on 13 July 2025 for the posts of 3446 UPSSSC Technical Assistant Group C in various locations of Uttar Pradesh. Candidates who appeared for this examination can check their UPSSSC Technical Assistant Group C Supplementary List 2026 from the direct link provided below."
    },
    "india-post-gds-2026": {
      "title": "India Post GDS 4th Merit List 2026",
      "slug": "india-post-gds-2026",
      "url": "https://www.sarkariexam.com/india-post-gds-2026/",
      "category": "",
      "publishedDate": "2026-06-08T22:27:56+05:30",
      "intro": "Short Information : Department of Post (India Post) has released the 4th Merit List for the post of Gramin Dak Sevaks GDS on the official website of India Post. This recruitment was released for 28636 posts. The applications for India Post GDS Recruitment 2025 were accepted from 31 January 2026 to 14 February 2026. Candidates who had applied this form can download their India Post GDS 4rt Merit List 2026 from the link given below."
    },
    "dda-group-a-b-c-post-2025": {
      "title": "DDA Group A, B & C Various Posts Marks 2026",
      "slug": "dda-group-a-b-c-post-2025",
      "url": "https://www.sarkariexam.com/dda-group-a-b-c-post-2025/",
      "category": "",
      "publishedDate": "2026-06-08T14:22:39+05:30",
      "intro": "Short Information : Delhi Development Authority (DDA) has released the marks for the Group A, B & C Various Posts on the official website of the DDA Delhi. This recruitment was released for 1732 posts. Applications for the DDA Group A, B, C Recruitment 2025 were accepted from 06 October 2025, to 05 November 2025. The Skill Test examination was held on 02-03 March 2026. Candidates who appeared for this Examination can download their DDA Group A, B, C Marks 2026 from the link given below."
    },
    "dsssb-various-post-result-2026": {
      "title": "DSSSB Stenographer Grade-D Result 2026",
      "slug": "dsssb-various-post-result-2026",
      "url": "https://www.sarkariexam.com/dsssb-various-post-result-2026/",
      "category": "",
      "publishedDate": "2026-06-08T14:16:33+05:30",
      "intro": "Short Information : Delhi Subordinate Service Selection Board (DSSSB) had conducted the various posts examination few months ago. As per the official updates, the result for the Delhi DSSSB Various Post Exam has been released on the official website of DSSSB. Candidates who have appeared for the aforesaid examination, are now be able to download their DSSSB Various Post Result 2024 from the direct link provided below."
    },
    "ssc-mts-havaldar-2026": {
      "title": "SSC MTS / Havaldar Result 2026",
      "slug": "ssc-mts-havaldar-2026",
      "url": "https://www.sarkariexam.com/ssc-mts-havaldar-2026/",
      "category": "",
      "publishedDate": "2026-06-08T13:11:06+05:30",
      "intro": "Short Information : Staff Selection Commission (SSC) will shortly announce the result for the MTS / Havaldar posts after evaluating candidates’ performance in the examination. This recruitment was conducted for 7,948 posts. Applications for the SSC MTS / Havaldar Recruitment 2025 were accepted from 26 June 2025 to 24 July 2025. The examination was held from 04 February 2026. Candidates are advised to regularly check the Sarkari Result portal for updates regarding the SSC MTS / Havaldar Result 2026, which will be uploaded shortly."
    },
    "rssb-livestock-assistant-2025": {
      "title": "RSSB Livestock Assistant Final Result 2026",
      "slug": "rssb-livestock-assistant-2025",
      "url": "https://www.sarkariexam.com/rssb-livestock-assistant-2025/",
      "category": "",
      "publishedDate": "2026-06-06T20:20:35+05:30",
      "intro": "Short Information : Rajasthan Staff Selection Board (RSSB) has released the final result for the post of Livestock Assistant. This recruitment was released for 1526 posts. Applications for the RSSB Livestock Assistant Recruitment 2025 were accepted from January 31, 2025, to March 01, 2025. The online examination was held on 13 June 2025. Candidates who appeared for this examination can download their RSSB Livestock Assistant Final Result 2026 from the link given below."
    },
    "indian-airforce-agniveer-vayu-02-2026": {
      "title": "Indian Air Force Agniveer Vayu Intake 02/2026 Enrolment List",
      "slug": "indian-airforce-agniveer-vayu-02-2026",
      "url": "https://www.sarkariexam.com/indian-airforce-agniveer-vayu-02-2026/",
      "category": "",
      "publishedDate": "2026-06-06T10:49:54+05:30",
      "intro": "Short Information : Indian Air Force (Bhartiya Vayu Sena) has released Enrolment List for the Airforce Agniveer Vayu Intake 02/2026 Recruitment 2025 (Intake 02/2026) on the official website of IAF. Applications for the Indian Airforce Agniveer Vayu 02/2026 Recruitment 2025 were accepted from July 11, 2025, to August 04, 2025. The Phase II examination  was held on January 2026. Candidates who had applied this form can download their Indian Airforce Agniveer Vayu 02/2026 Enrolment List from the link given below."
    },
    "ssc-delhi-police-hcm-2025": {
      "title": "SSC Delhi Police Head Constable Ministerial Result 2026",
      "slug": "ssc-delhi-police-hcm-2025",
      "url": "https://www.sarkariexam.com/ssc-delhi-police-hcm-2025/",
      "category": "",
      "publishedDate": "2026-06-05T13:50:07+05:30",
      "intro": "Short Information : Staff Selection Commission, SSC has released the result for the post of Head Constable Ministerial on the official website of SSC. This recruitment was released for 456 posts. Applications for the Delhi Police Head Constable Ministerial Recruitment 2025 were accepted from September 29, 2025, to October 20, 2025. The CBT examination was held on 07-12 January 2026. Candidates who appeared for this examination can download their SSC Delhi Police Constable Ministerial Result 2026 from the link given below."
    },
    "rssb-reet-mains-upper-teacher-2025": {
      "title": "RSSB REET Mains Upper Teacher Result 2026 (Update)",
      "slug": "rssb-reet-mains-upper-teacher-2025",
      "url": "https://www.sarkariexam.com/rssb-reet-mains-upper-teacher-2025/",
      "category": "",
      "publishedDate": "2026-06-05T10:15:03+05:30",
      "intro": "Short Information : Rajasthan Staff Selection Board (RSSB) has released the mains result for the post of Level II Upper School Teacher Posts on the official website of RSSB. This recruitment was released for 2133 posts. Applications for the RSSB REET Mains Upper Teacher Recruitment 2025 were accepted from November 07, 2025, to December 06, 2025. The online examination was held on 18-20 January 2026. Candidates who appeared for this examination download their RSSB REET Mains Upper Teacher Mains Result 2026 from the link given below."
    },
    "nta-ncet-2026": {
      "title": "NTA NCET Result / Score Card 2026",
      "slug": "nta-ncet-2026",
      "url": "https://www.sarkariexam.com/nta-ncet-2026/",
      "category": "",
      "publishedDate": "2026-06-04T20:56:37+05:30",
      "intro": "Short Information : National Testing Agency (NTA) has released the Result / Score Card for the National Common Entrance Test NCET online application for admission 2026 on the official website of the NTA. Applications for the NTA NCET Online Form 2026 were accepted from 12 February 2026 to 10 March 2026. The online examination was held on 17-18 April 2026. Candidates who appeared for this examination can download their NTA NCET Result / Score Card 2026 from the link given below."
    },
    "dece-le-bihar-diploma-2026": {
      "title": "DECE-LE Bihar Diploma Result / Rank Card 2026",
      "slug": "dece-le-bihar-diploma-2026",
      "url": "https://www.sarkariexam.com/dece-le-bihar-diploma-2026/",
      "category": "",
      "publishedDate": "2026-06-04T16:05:52+05:30",
      "intro": "Short Information : Bihar Combined Entrance Competitive Examination Board (BCECEB) has released the Result / Rank Card for the Diploma Entrance Competitive Examination (Lateral Entry) (DECE-LE) 2026 on its official website. The online registration process for the DECE-LE Bihar Diploma Admission Form 2026 were accepted from 20 March 2026 to 23 April 2026. Candidates are advised to check the complete details for DECE-LE Bihar Diploma Admission Result / Rank Card 2026 given below."
    },
    "bihar-iti-cat-2026": {
      "title": "Bihar ITI CAT Result / Rank Card 2026",
      "slug": "bihar-iti-cat-2026",
      "url": "https://www.sarkariexam.com/bihar-iti-cat-2026/",
      "category": "",
      "publishedDate": "2026-06-04T15:58:27+05:30",
      "intro": "Short Information : Bihar Combined Entrance Competitive Examination Board (BCECEB) has released the Result / Rank Card for the Bihar ITI Competitive Admission Test 2026. Applications for the Bihar ITI CAT 2026 were accepted from 16 March 2026 to 27 April 2026. The written examination was held on 17 May 2026. Candidates who appeared for this examination can download their Bihar ITI CAT Result / Rank Card 2026 from the link given below."
    },
    "allahabad-university-pgat-admissions-2026": {
      "title": "Allahabad University PGAT Admit card 2026",
      "slug": "allahabad-university-pgat-admissions-2026",
      "url": "https://www.sarkariexam.com/allahabad-university-pgat-admissions-2026/",
      "category": "",
      "publishedDate": "2026-06-11T11:30:57+05:30",
      "intro": "Short Information : Central University of Allahabad, Prayagraj (U.P.) has released the admit card for the PGAT I and PGAT II (B.Ed, LLB, PG & Other Courses) Admission 2026. The online application process for Allahabad University PGAT Online Form 2026 were accepted from 05 May 2026 to 25 May 2026. The Examination is going to conducted on 11 June 2026 Candidates must check the complete details for Allahabad University PGAT Admit Card 2026, which are given below."
    },
    "bihar-police-csbc-constable-gd-2026": {
      "title": "Bihar Police CSBC Constable GD Exam City / Admit Card 2026",
      "slug": "bihar-police-csbc-constable-gd-2026",
      "url": "https://www.sarkariexam.com/bihar-police-csbc-constable-gd-2026/",
      "category": "",
      "publishedDate": "2026-06-11T11:15:33+05:30",
      "intro": "Short Information : Central Selection Board of Constable (CSBC) has released the Exam Date, Admit Card & Exam City Details for the post of Constable (General Duty Close Cadre). This recruitment was released for 83 posts. Applications for the Bihar Police CSBC Constable GD Recruitment 2026 were accepted from 06 February 2026 to 05 March 2026. The written examination is going to be conducted on 24 June 2026. Candidates who have applied for this recruitment can download their Bihar Police CSBC Constable GD Admit Card 2026 from the link given below."
    },
    "rrb-ntpc-102-inter-level-2025": {
      "title": "RRB NTPC 10+2 UG Admit Card 2026",
      "slug": "rrb-ntpc-102-inter-level-2025",
      "url": "https://www.sarkariexam.com/rrb-ntpc-102-inter-level-2025/",
      "category": "",
      "publishedDate": "2026-06-10T15:59:56+05:30",
      "intro": "Short Information : Railway Recruitment Board (RRB) has released the admit card for the Non Technical Popular Categories NTPC 10+2 Under Graduate Level Post on the official website of RRB. This recruitment was released for 3058 posts. Candidates can also check all the details on the official Sarkari Result website. Applications for the RRB NTPC 10+2 UG Recruitment 2025 were accepted from 28 October 2025, to 04 December 2025. The written examination is going to be conducted on 7, 8, 9 May & 13, 14, 15, 16, 20 June 2026. Candidates who had applied this form can download their RRB NTPC 10+2 UG Admit Card 2026 from the link given below."
    },
    "nta-ugc-net-june-2026": {
      "title": "NTA UGC NET June Exam City Details 2026",
      "slug": "nta-ugc-net-june-2026",
      "url": "https://www.sarkariexam.com/nta-ugc-net-june-2026/",
      "category": "",
      "publishedDate": "2026-06-10T15:59:03+05:30",
      "intro": "Short Information : National Testing Agency (NTA) has released the Exam City Details for the University Grant Commission UGC National Eligibility Test NET Assistant Professor / JRF June 2026 Examination. The online application process for NTA UGC NET June Online Form 2026 were accepted from 29 April 2026 to 24 May 2026. The Examination is going to conducted on 22-30 June 2026 Candidates must check the complete details for NTA UGC NET June Exam City Details 2026, which are given below."
    },
    "nta-neet-ug-2026": {
      "title": "NTA NEET UG Online Fee Refund 2026",
      "slug": "nta-neet-ug-2026",
      "url": "https://www.sarkariexam.com/nta-neet-ug-2026/",
      "category": "",
      "publishedDate": "2026-06-10T14:45:07+05:30",
      "intro": "Short Information : National Testing Agency (NTA) has released the NEET UG 2026 Re-Exam City Details on its official website for candidates appearing in the undergraduate medical entrance exam. According to the notification, the NEET UG 2026 Re-Exam is scheduled to be held on 21 June 2026. The last date for submitting the online application form was 11 March 2026. Candidates can access their re-exam details by logging into the portal using their Enrollment Number, Registration Number, or Date of Birth.  Additionally, candidates appearing for the re-exam may receive an extra 15 minutes to complete the examination. Candidates who had applied this form can download their NTA NEET UG Re-Exam City Details 2026 from the link given below."
    },
    "indian-army-agniveer-cee-2026": {
      "title": "Indian Army Agniveer CEE Admit Card 2026",
      "slug": "indian-army-agniveer-cee-2026",
      "url": "https://www.sarkariexam.com/indian-army-agniveer-cee-2026/",
      "category": "",
      "publishedDate": "2026-06-10T14:45:03+05:30",
      "intro": "Short Information : Join Indian Army (Bhartiya Sena) has released the admit card for the Indian Army Common Entrance Exam (CEE) 2026–2027 on the official website of the Indian Army. Applications for the Indian Army Agniveer CEE Recruitment 2025 were accepted from February 12, 2026, to April 10, 2026. The CEE examination is going to be conducted on 01-16 June 2026. Candidates who had applied this form can download their Indian Army Agniveer CEE Admit Card 2026 from the link given below."
    },
    "up-gnm-entrance-exam-upget-2026": {
      "title": "UP GNM Entrance Exam UPGET Exam City Details 2026",
      "slug": "up-gnm-entrance-exam-upget-2026",
      "url": "https://www.sarkariexam.com/up-gnm-entrance-exam-upget-2026/",
      "category": "",
      "publishedDate": "2026-06-10T13:20:26+05:30",
      "intro": "Short Information : Atal Bihari Vajpayee Medical University, ABVMU Uttar Pradesh has released the Exam City Details for the UP GNM Entrance Test UPGET 2026. Online applying process for UP GNM Entrance Exam UPGET Online Form 2026 were accepted from 29 April 2026 to 26 May 2026. The examination is going to be conducted on 16 June 2026. Candidates who applied this form can check their UP GNM Entrance Exam UPGET Exam City Details 2026 from the direct link provided below."
    },
    "ssb-head-constable-ministerial-2021": {
      "title": "SSB Head Constable Ministerial Written Exam Date 2026",
      "slug": "ssb-head-constable-ministerial-2021",
      "url": "https://www.sarkariexam.com/ssb-head-constable-ministerial-2021/",
      "category": "",
      "publishedDate": "2026-06-10T02:22:15+05:30",
      "intro": "Short Information : Sashastra Seema Bal (SSB) has released the Written Exam Date for the post of Head Constable (Ministerial). This recruitment was released for 115 posts. Applications for the SSB Head Constable Ministerial Recruitment 2021 were accepted from July 24, 2021, to August 28, 2021. The written examination is going to be started on 07 July 2026. Candidates who had applied this form can download their SSB Head Constable Ministerial Written Exam Date 2026 from the link given below."
    },
    "upsssc-forest-guard-wild-guard-2023": {
      "title": "UPSSSC Forest/ Wild Life Guard 2023 Medical Admit Card 2026",
      "slug": "upsssc-forest-guard-wild-guard-2023",
      "url": "https://www.sarkariexam.com/upsssc-forest-guard-wild-guard-2023/",
      "category": "",
      "publishedDate": "2026-06-09T15:02:04+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Service Selection Board (UPSSSC) has released the Medical Admit Card on its official website for the Recruitment of Forest Guard Examination 2025. Applications for the UPSSSC Forest Guard, Wild Life Guard Recruitment 2023 were accepted from September 20, 2023, to October 10, 2023. The vacancy came in the year 2023 and it took almost three year one month to conduct the Medical examination for the prescribed posts. The Medical examination is going to be conducted on 15 June 2026. Candidates who qualified PET/PMT examination can check their UPSSSC Forest/ Wild Life Guard 2023 Medical Admit Card 2026 from the direct link provided below."
    },
    "up-lt-grade-assistant-teacher-2025": {
      "title": "UPPSC LT Grade Assistant Teacher Mains Admit Card 2026",
      "slug": "up-lt-grade-assistant-teacher-2025",
      "url": "https://www.sarkariexam.com/up-lt-grade-assistant-teacher-2025/",
      "category": "",
      "publishedDate": "2026-06-09T11:38:19+05:30",
      "intro": "Short Information : Uttar Pradesh Public Service Commission (UPPSC) has released the mains admit card for the post of Assistant Teacher (TGT). This recruitment was released for 7466 posts. Applications for the UP LT Grade Assistant Teacher Mains Recruitment 2026 were accepted from April 02, 2026, to April 17, 2026. The written examination is going to be conducted on 13 June 2026 and 11 July 2026. Candidates who had applied this form can download their UP LT Grade Assistant Teacher Mains Admit Card 2026 from the link given below."
    },
    "nta-swayam-2026": {
      "title": "NTA SWAYAM Exam City Details 2026",
      "slug": "nta-swayam-2026",
      "url": "https://www.sarkariexam.com/nta-swayam-2026/",
      "category": "",
      "publishedDate": "2026-06-09T11:37:19+05:30",
      "intro": "Short Information : National Testing Agency (NTA) has released the Exam City Details for the Study Webs of Active Learning for Young Aspiring Minds SWAYAM 2026 (January 2026 Semester) Examination on the official website of the NTA recently. The online application process for NTA SWAYAM January Online Form 2026 were accepted from 15 April 2026 to13 May 2026. The Examination is going to conducted on 17,18,19, 20 and 21 June 2026 Candidates must check the complete details for NTA SWAYAM Exam City Details 2026, which are given below."
    },
    "uksssc-vdo-patwari-other-post-2025": {
      "title": "UKSSSC VDO, Patwari & Other Post Admit Card 2026",
      "slug": "uksssc-vdo-patwari-other-post-2025",
      "url": "https://www.sarkariexam.com/uksssc-vdo-patwari-other-post-2025/",
      "category": "",
      "publishedDate": "2026-06-09T11:11:14+05:30",
      "intro": "Short Information : Uttarakhand Subordinate Service Selection Commission (UKSSSC) has released the admit card for the post of Village Development Officer (VDO), Patwari, Lekhpal, Village Panchayat Development Officer (VPDO), Personal Assistant & Other Various Post. This recruitment was released for 416 posts. Applications for the UKSSSC VDO, Patwari & Other Post Recruitment 2025 were accepted from April 15, 2025, to May 15, 2025. The written examination is going to be conducted on 14 June 2026. Candidates who had applied this form can download their UKSSSC VDO, Patwari & Other Post Admit Card 2026 from the link given below."
    },
    "bihar-vidhan-parishad-2023": {
      "title": "Bihar Vidhan Parishad Security Guard Interview Admit Card 2026",
      "slug": "bihar-vidhan-parishad-2023",
      "url": "https://www.sarkariexam.com/bihar-vidhan-parishad-2023/",
      "category": "",
      "publishedDate": "2026-06-09T10:41:02+05:30",
      "intro": "Short Information : Bihar Vidhan Parishad (BVP), Government of Bihar, has release the Interview Admit Card for the Security Guard, Reporter, Assistant, DEO & Various Other Posts. This recruitment was released for 176 posts. Applications for the Bihar Vidhan Parishad Various Posts Recruitment 2024 were accepted from 16 October 2024, to 25 October 2024. The Security Guard physical examination was conducted on 21 to 28 April 2026. Candidates who had appeared in this Examination can download their Bihar Vidhan Parishad Security Guard Interview Admit Card 2026 from the link given below."
    },
    "rajasthan-ptet-2026": {
      "title": "Rajasthan PTET Admit Card 2026",
      "slug": "rajasthan-ptet-2026",
      "url": "https://www.sarkariexam.com/rajasthan-ptet-2026/",
      "category": "",
      "publishedDate": "2026-06-08T14:36:37+05:30",
      "intro": "Short Information : Vardhman Mahaveer Open University, MVOU Kota has released the admit card for the Rajasthan 2 Year B.Ed. Joint Entrance Examination 2026. Applications for the Rajasthan PTET Admission Online Form 2026 were accepted from 20 February 2026, to 20 March 2026. The entrance examination is going to be conducted on 14 June 2026. Candidates who had applied this form can download their Rajasthan PTET Admit Card 2026 from the link given below."
    },
    "bihar-police-csbc-prohibition-constable-2025": {
      "title": "Bihar Police Prohibition Constable Admit Card 2026",
      "slug": "bihar-police-csbc-prohibition-constable-2025",
      "url": "https://www.sarkariexam.com/bihar-police-csbc-prohibition-constable-2025/",
      "category": "",
      "publishedDate": "2026-06-08T10:19:52+05:30",
      "intro": "Short Information : Central Selection Board of Constable (CSBC) has released the Exam Date, Admit Card & Exam City Details for the post of Constable posts in Prohibition, Jail Warder, and Mobile Squad units. This recruitment was released for 4236 posts. Applications for the Bihar Police CSBC Prohibition Constable Recruitment 2025 were accepted from 06 October 2025 to 05 November 2025. The written examination is going to be conducted on 14 & 17 June 2026. Candidates who have applied for this recruitment can download their Bihar Police CSBC Prohibition Constable Admit Card 2026 from the link given below."
    },
    "bihar-bpsc-aes-2025": {
      "title": "BPSC AES Admit Card 2026",
      "slug": "bihar-bpsc-aes-2025",
      "url": "https://www.sarkariexam.com/bihar-bpsc-aes-2025/",
      "category": "",
      "publishedDate": "2026-06-08T10:19:45+05:30",
      "intro": "Short Information : Bihar Public Service Commission (BPSC) has released the admit card for the post of Assistant Environmental Scientist (AES). This recruitment was released for 17 posts. Online applying process for Bihar BPSC AES Recruitment 2026 were accepted from 27 August 2026 & the candidates can apply till 19 September 2026. The Mains Examination is going to conducted on 11 June 2026 Candidates must check the complete details for Bihar BPSC AES Admit Card 2026 which has given below."
    },
    "bpsc-stenographer-2026": {
      "title": "BPSC Stenographer Admit Card 2026",
      "slug": "bpsc-stenographer-2026",
      "url": "https://www.sarkariexam.com/bpsc-stenographer-2026/",
      "category": "",
      "publishedDate": "2026-06-08T10:19:40+05:30",
      "intro": "Short Information : Bihar Public Service Commission (BPSC) has released the Admit Card for the post of Stenographer. This recruitment was released for 15 posts. Online applying process for Bihar BPSC Stenographer Recruitment 2026 were accepted from 12 January 2026 & the candidates can apply till 02 February 2026. The written examination is going to conducted on 11 June 2026 Candidates must check the complete details for Bihar BPSC Stenographer Admit Card 2026 which has given below."
    },
    "upsssc-pharmacist-2026": {
      "title": "UPSSSC Pharmacist Mains Exam Fee Payment 2026",
      "slug": "upsssc-pharmacist-2026",
      "url": "https://www.sarkariexam.com/upsssc-pharmacist-2026/",
      "category": "",
      "publishedDate": "2026-06-07T14:17:34+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Services Selection Commission (UPSSSC) has releases the Mains Exam Fee Payment for the post of Pharmacist on the official website of the UPSSSC. Online applying process for UPSSSC Pharmacist Recruitment 2026 were accepted from 09 March 2026 & the candidates can apply till the 31 March 2026. The Examination is Going to conducted on 29 June 2026. Candidates must check the complete details for UPSSSC Pharmacist Revised Exam Date 2026 which has given below."
    },
    "sgpgi-nursing-officer-and-non-teaching-post-2025": {
      "title": "SGPGI Nursing Officer and Non Teaching Post Exam City Details 2026",
      "slug": "sgpgi-nursing-officer-and-non-teaching-post-2025",
      "url": "https://www.sarkariexam.com/sgpgi-nursing-officer-and-non-teaching-post-2025/",
      "category": "",
      "publishedDate": "2026-06-07T13:38:32+05:30",
      "intro": "Short Information : Sanjay Gandhi Post Graduate Institute of Medical Science (SPPGI) has released the exam city details for the Nursing Officer & Other Post. This recruitment was released for 1479 posts. Applications for the SGPGI Nursing Officer & Other Post Recruitment 2025 were accepted from June 18, 2025, to July 31, 2025. The written examination is going to be conducted on 19-23 June 2026. Candidates who had applied this form can download their SGPGI Nursing Officer & Other Post Exam City Details 2026 from the link given below."
    },
    "bsf-hcm-asi-steno-2024": {
      "title": "BSF HCM & ASI Steno Exam Date 2026",
      "slug": "bsf-hcm-asi-steno-2024",
      "url": "https://www.sarkariexam.com/bsf-hcm-asi-steno-2024/",
      "category": "",
      "publishedDate": "2026-06-06T10:40:28+05:30",
      "intro": "Short Information : Border Security Force (BSF) has released the exam date for the Probationary Assistant Sub Inspector ASI Stenographer and Head Constable HC Ministerial Post. This recruitment was released for 1526 posts. Applications for BSF HC Ministerial and ASI Steno Recruitment 2024 were filled from 09 June 2024 to 08 July 2024. The written examination is going to be conducted in September 2026. Candidates who had applied this form can download their BSF HCM & ASI Steno Exam Date 2026 from the link given below."
    },
    "rrb-alp-cen-01-2026": {
      "title": "RRB ALP 01/2026 Recruitment 2026",
      "slug": "rrb-alp-cen-01-2026",
      "url": "https://www.sarkariexam.com/rrb-alp-cen-01-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:14:26+05:30",
      "intro": "Short Information : Railway Recruitment Board (RRB) has released the notification for the RRB CEN 01/2026 recruitment of Assistant Loco Pilot (ALP) posts on its official website. The online application process for RRB ALP CEN 01/2026 Recruitment has started from 15 May 2026 & the candidates can apply untill 14 June 2026. Total of 11,127 vacancies have been announced for Assistant Loco Pilot (ALP) posts under RRB ALP CEN 01/2026 Recruitment. Candidates must check the Complete details for RRB ALP CEN 01/2026 Recruitment given below."
    },
    "ssc-cgl-2026": {
      "title": "SSC CGL Recruitment 2026",
      "slug": "ssc-cgl-2026",
      "url": "https://www.sarkariexam.com/ssc-cgl-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:14:16+05:30",
      "intro": "Short Information : Staff Selection Commission (SSC) has released the notification for the post of Combined Graduate Level CGL Examination 2026. This recruitment has been issued for 12256 posts. Candidates can also check all the details on the official Sarkari Result 2026 website. The online application process for SSC CGL Recruitment 2026 has started on 21 May 2026, and candidates can apply till 22 June 2026. Candidates must check the complete details for SSC CGL Online Form 2026, which are given below."
    },
    "coal-india-cil-management-trainee-2026": {
      "title": "Coal India CIL Management Trainee MT Recruitment 2026",
      "slug": "coal-india-cil-management-trainee-2026",
      "url": "https://www.sarkariexam.com/coal-india-cil-management-trainee-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:13:21+05:30",
      "intro": "Short Information : Coal India Limited (CIL), has released the notification for the post of Management Trainee MT. This recruitment has been issued for 660 posts. Online applying process for Coal India CIL Management Trainee MT Recruitment 2026 has started on 12 May 2026 & the candidates can apply till 11 June 2026. Candidates must check the complete details for Coal India CIL Management Trainee MT Recruitment 2026 which has given below."
    },
    "upsssc-agriculture-technical-assistant-group-c-2026": {
      "title": "UPSSSC Agriculture Technical Assistant Group-C Recruitment 2026",
      "slug": "upsssc-agriculture-technical-assistant-group-c-2026",
      "url": "https://www.sarkariexam.com/upsssc-agriculture-technical-assistant-group-c-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:13:11+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Services Selection Commission (UPSSSC) has released a notification for the recruitment of Agriculture Technical Assistant (AGTA) Group-C posts on the official website of UPSSSC. This recruitment has been issued for 2759 posts. The online application process for UPSSSC Agriculture Technical Assistant AGTA Group-C Recruitment 2026 has started from 22 May 2026, and the candidates can apply until 11 June 2026. Candidates must check the complete details for UPSSSC Agriculture Technical Assistant AGTA Group-C Recruitment 2026 given below."
    },
    "upsc-nda-na-ii-2026": {
      "title": "UPSC NDA/ NA-II Recruitment 2026",
      "slug": "upsc-nda-na-ii-2026",
      "url": "https://www.sarkariexam.com/upsc-nda-na-ii-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:13:05+05:30",
      "intro": "Short Information : Union Public Service Commission (UPSC) has released the Nptification for the post of National Defence Academy NDA & Naval Academy NA -II 2026 on the official website of UPSC. This recruitment was released for 394 posts. The online application process for UPSC NDA/ NA-II Recruitment 2026 has started on 20 May 2026, and candidates can apply until 11 June 2026 (Extended). Candidates must check the complete details of UPSC NDA/ NA-II Recruitment 2026 given below."
    },
    "upsc-cds-ii-2026": {
      "title": "UPSC CDS II Recruitment 2026",
      "slug": "upsc-cds-ii-2026",
      "url": "https://www.sarkariexam.com/upsc-cds-ii-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:13:01+05:30",
      "intro": "Short Information : Union Public Service Commission (UPSC) has released the notification for Combined Defence Service CDS II posts. This recruitment has been released for 451 posts. The online application process for UPSC CDS-II Recruitment 2026 has started on 20 May 2026, and candidates can apply until 11 June 2026 (Extended). Candidates must check the complete details of UPSC CDS-II Recruitment 2026 given below."
    },
    "railway-rrc-secr-bilaspur-apprentice-2026": {
      "title": "Railway RRC SECR Bilaspur Apprentice Recruitment 2026",
      "slug": "railway-rrc-secr-bilaspur-apprentice-2026",
      "url": "https://www.sarkariexam.com/railway-rrc-secr-bilaspur-apprentice-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:12:55+05:30",
      "intro": "Short Information : Railway RRC-South East Central Railway (SECR) Bilaspur Division has released the notification for Apprentice posts. This recruitment has been released for 1191 posts. The online application process for Railway RRC SECR Apprentice Recruitment 2026 started on 12 May 2026, and candidates can apply until 11 June 2026. Candidates must check the complete details of Railway RRC SECR Apprentice Recruitment 2026 given below."
    },
    "indian-army-tgc-144-2026": {
      "title": "Indian Army TGC 144 Recruitment 2026",
      "slug": "indian-army-tgc-144-2026",
      "url": "https://www.sarkariexam.com/indian-army-tgc-144-2026/",
      "category": "",
      "publishedDate": "2026-06-11T13:12:51+05:30",
      "intro": "Short Information : Join Indian Army (Govt. Of India) has release the notification for the recruitment of Technical Graduate Course (TGC 144 Entry January 2027) on the official website of Indian Army. Online registration process for Indian Army TGC 144 Recruitment 2026 has start from 13 May 2026 & the candidates can apply till 11 June 2026. Total 30 vacancies has to be issue in the Indian Army TGC 144 Recruitment 2025 for the Technical Graduate Course starting in January 2027. Candidates must check the complete details for Indian Army TGC 144 Online Form 2026 which has given below."
    },
    "ssc-junior-engineer-je-2025": {
      "title": "SSC Junior Engineer JE Online Post Preference Form 2026",
      "slug": "ssc-junior-engineer-je-2025",
      "url": "https://www.sarkariexam.com/ssc-junior-engineer-je-2025/",
      "category": "",
      "publishedDate": "2026-06-11T13:11:54+05:30",
      "intro": "Short Information : Staff Selection Commission, SSC has released the Online Post Preference Form on its official website for the Recruitment of Junior Engineer Examination 2025. This recruitment was released for 1731 posts. Online registration process for SSC Junior Engineer JE Recruitment 2025 were accepted from 30 June 2025 to 21 July 2025. The Tier-II Exam was conducted on 07 April 2026. Candidates who qualified the Tier-I Examination can check the complete details for SSC Junior Engineer JE Tier-II Answer Key 2026 which has given below."
    },
    "allahabad-high-court-ro-aro-ca-2026": {
      "title": "Allahabad High Court RO / ARO / Computer Assistant Recruitment 2026",
      "slug": "allahabad-high-court-ro-aro-ca-2026",
      "url": "https://www.sarkariexam.com/allahabad-high-court-ro-aro-ca-2026/",
      "category": "",
      "publishedDate": "2026-06-11T10:10:17+05:30",
      "intro": "Short Information : High Court of Judicature at Allahabad (Prayagraj) has released the notification for the post of Review Officer (RO), Assistant Review Officer (ARO) & Computer Assistant (CA). This recruitment has been issued for 543 posts. The online application process for Allahabad High Court RO, ARO & CA Recruitment 2026 has started on 01 June 2026, and candidates can apply till 21 June 2026. Candidates must check the complete details for Allahabad High Court RO, ARO & CA Recruitment 2026, which are given below."
    },
    "upsssc-lower-pcs-2026": {
      "title": "UPSSSC Lower PCS Recruitment 2026",
      "slug": "upsssc-lower-pcs-2026",
      "url": "https://www.sarkariexam.com/upsssc-lower-pcs-2026/",
      "category": "",
      "publishedDate": "2026-06-11T10:10:13+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Services Selection Commission (UPSSSC) has released a notification for the recruitment of Lower Subordinate Services PCS for various posts such as Mandi Supervisor, Amin / Auctioneer, Assistant Manager (Non-Technical), Clerk cum Typist / Cashier cum Clerk / Accounts Clerk, Assistant Treasury Accountant, Auditor, Centre In Charge, Executive Officer, Assistant Chakbandi Officer, Assistant Manager (Non-Technical) (Special Selection), and District Assistant Immunization Officer on its official website. This recruitment has been announced for a total of 2516 posts. The online application process for UPSSSC Lower PCS Recruitment 2026 has started from 29 May 2026, and candidates can apply until 18 June 2026. Candidates are advised to check the complete details for UPSSSC Lower PCS Recruitment 2026 given below."
    },
    "upsssc-excise-constable-2026": {
      "title": "UPSSSC Excise Constable Recruitment 2026",
      "slug": "upsssc-excise-constable-2026",
      "url": "https://www.sarkariexam.com/upsssc-excise-constable-2026/",
      "category": "",
      "publishedDate": "2026-06-11T10:10:08+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Services Selection Commission (UPSSSC) has released a notification for the recruitment of Excise Constable posts on the official website of UPSSSC. This recruitment has been issued for 722 posts. The online application process for UPSSSC Excise Constable Recruitment 2026 has started on 04 June 2026, and candidates can apply until 24 June 2026. Candidates must check the complete details for UPSSSC Excise Constable Recruitment 2026 given below."
    },
    "sbi-apprentice-2026": {
      "title": "SBI Apprentice Recruitment 2026",
      "slug": "sbi-apprentice-2026",
      "url": "https://www.sarkariexam.com/sbi-apprentice-2026/",
      "category": "",
      "publishedDate": "2026-06-11T10:10:03+05:30",
      "intro": "Short Information : State Bank of India (SBI) has released the notification for the post of Apprentice. This recruitment has been issued for 7150 posts. Online applying process for SBI Apprentice Recruitment 2026 has started on 19 May 2026 & the candidates can apply till 15 June 2026 (Extended). Candidates must check the complete details for SBI Apprentice Recruitment 2026 which has given below."
    },
    "bank-of-baroda-apprentices-2026": {
      "title": "Bank of Baroda Apprentice Recruitment 2026",
      "slug": "bank-of-baroda-apprentices-2026",
      "url": "https://www.sarkariexam.com/bank-of-baroda-apprentices-2026/",
      "category": "",
      "publishedDate": "2026-06-11T10:09:59+05:30",
      "intro": "Short Information : Bank of Baroda (BOB) has released the notification for the post of Apprentice. This recruitment has been issued for 2700 posts. This recruitment has been issued for 5000 posts. Online applying process for Bank of Baroda Apprentices Recruitment 2026 has started on 19 May 2026 & the candidates can apply till 15 June 2026. Candidates must check the complete details for Bank of Baroda Apprentices Recruitment 2026 which has given below."
    },
    "upsssc-vidhan-bhawan-guard-fire-guard-2026": {
      "title": "UPSSSC Vidhan Bhawan Guard/ Fire Guard Recruitment 2026",
      "slug": "upsssc-vidhan-bhawan-guard-fire-guard-2026",
      "url": "https://www.sarkariexam.com/upsssc-vidhan-bhawan-guard-fire-guard-2026/",
      "category": "",
      "publishedDate": "2026-06-11T10:09:54+05:30",
      "intro": "Short Information : Uttar Pradesh Subordinate Services Selection Commission (UPSSSC) has released a notification for the recruitment of Vidhan Bhawan Guard/ Fire Guard posts on the official website of UPSSSC. This recruitment has been issued for 170 posts. The online application process for UPSSSC Vidhan Bhawan Guard/ Fire Guard Recruitment 2026 has started on 09 June 2026, and candidates can apply until 29 June 2026. Candidates must check the complete details for UPSSSC Vidhan Bhawan Guard/ Fire Guard Recruitment 2026 given below."
    },
    "ctet-september-2026": {
      "title": "CTET September Online Form 2026",
      "slug": "ctet-september-2026",
      "url": "https://www.sarkariexam.com/ctet-september-2026/",
      "category": "",
      "publishedDate": "2026-06-10T10:16:06+05:30",
      "intro": "Short Details : Central Board of Secondary Education (CBSE) has invited application for the Central Teacher Eligibility Test (CTET) September 2026 examination. Candidates can also check all the details on the official Sarkari Result website. The online application process for CTET September Recruitment 2026 has started on 11 May 2026, and candidates can apply till 10 June 2026. Candidates must check the complete details for CTET September Recruitment 2026, which are given below."
    },
    "cisf-asi-paramedical-staff-2026": {
      "title": "CISF ASI Paramedical Staff Recruitment 2026",
      "slug": "cisf-asi-paramedical-staff-2026",
      "url": "https://www.sarkariexam.com/cisf-asi-paramedical-staff-2026/",
      "category": "",
      "publishedDate": "2026-06-08T10:23:24+05:30",
      "intro": "Short Information : Central Industrial Security Force (CISF) has released the notification for the post of Paramedical Staff. This recruitment has been issued for 24 posts. The online application process for CISF ASI Paramedical Staff Recruitment 2026 has started on 08 June 2026, and candidates can apply till 07 July 2026. Candidates must check the complete details for CISF ASI Paramedical Staff Recruitment 2026, which are given below."
    },
    "rpsc-apo-2026": {
      "title": "RPSC Assistant Prosecution Officer APO Recruitment 2026",
      "slug": "rpsc-apo-2026",
      "url": "https://www.sarkariexam.com/rpsc-apo-2026/",
      "category": "",
      "publishedDate": "2026-06-08T10:22:16+05:30",
      "intro": "Short Information : Rajasthan Public Service Commission (RPSC) has released the notification for the post of Assistant Prosecution Officer APO. This recruitment has been issued for 371 posts. Online applying process for Rajasthan RPSC Assistant Prosecution Officer APO Recruitment 2026 has started on 08 June 2026 & the candidates can apply till 07 July 2026. Candidates must check the complete details for Rajasthan RPSC Assistant Prosecution Officer APO Recruitment 2026 which has given below."
    },
    "hindustan-copper-limited-hcl-executive-2026": {
      "title": "Hindustan Copper Limited HCL Executive Recruitment 2026",
      "slug": "hindustan-copper-limited-hcl-executive-2026",
      "url": "https://www.sarkariexam.com/hindustan-copper-limited-hcl-executive-2026/",
      "category": "",
      "publishedDate": "2026-06-07T14:00:00+05:30",
      "intro": "Short Information : Hindustan Copper Limited (HCL) has released the notification for the post of Executive Manager, Senior Manager & Deputy Manager. This recruitment has been issued for 70 posts. The online application process for Hindustan Copper Limited HCL Executive Recruitment 2026 has started on 06 June 2026, and candidates can apply till 25 June 2026. Candidates must check the complete details for Hindustan Copper Limited HCL Executive Recruitment 2026, which are given below."
    },
    "up-board-class-10th-12th-2026": {
      "title": "UP Board Class 10th, 12th Compartment Online Form 2026",
      "slug": "up-board-class-10th-12th-2026",
      "url": "https://www.sarkariexam.com/up-board-class-10th-12th-2026/",
      "category": "",
      "publishedDate": "2026-06-06T13:02:51+05:30",
      "intro": "Short Details : Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP) has opened the online registration for the 2026 Compartment and Improvement Examinations for both High School (Class 10) and Intermediate (Class 12) students. Students who participated in the UP Board Exams 2026 and either failed in one or more subjects or wish to improve their scores are eligible to apply. The application window is open from June 06, 2026 to June 27, 2026, and submissions can be made through the official website: upmsp.edu.in. Candidates are advised to go through the detailed information regarding the UP Board Compartment Form 2026 provided below."
    },
    "nta-jipmat-2026": {
      "title": "NTA JIPMAT Answer Key 2026",
      "slug": "nta-jipmat-2026",
      "url": "https://www.sarkariexam.com/nta-jipmat-2026/",
      "category": "",
      "publishedDate": "2026-06-11T11:11:56+05:30",
      "intro": "Short Information : National Testing Agency (NTA) has released the answer key for the Join Integrated Program in Management Admission Test JIPMAT 2026. Applications for the NTA JIPMAT Online Form 2026 were accepted from 16 April 2026, to 10 May 2026. The written examination was held on 07 June 2026. Candidates who appeared for this examination can download their NTA JIPMAT Answer Key 2026 from the link given below."
    },
    "up-cnet-2026": {
      "title": "UP CNET Answer Key 2026",
      "slug": "up-cnet-2026",
      "url": "https://www.sarkariexam.com/up-cnet-2026/",
      "category": "",
      "publishedDate": "2026-06-09T15:30:15+05:30",
      "intro": "Short Information : Atal Bihari Vajpayee Medical University, ABVMU Uttar Pradesh has released the answer key for UP Common Nursing Entrance Test UP CNET 2026 on its official website. Online applying process for UP CNET Online Form 2026 were accepted from 28 March 2026 to 20 May 2026. The Examination was held on 06 June 2026. Candidates who appeared for this examination can download their UP CNET Answer Key 2026 from the link given below."
    },
    "bihar-cet-b-ed-2026": {
      "title": "Bihar CET B.Ed Answer Key 2026",
      "slug": "bihar-cet-b-ed-2026",
      "url": "https://www.sarkariexam.com/bihar-cet-b-ed-2026/",
      "category": "",
      "publishedDate": "2026-06-08T22:35:46+05:30",
      "intro": "Short Information : Babasahab Bhimrao Ambedkar University, Muzaffaprur (BRABU) has released the answer key for the B. Ed. Common Entrance Test (CET-BED)-2026 For Regular, Distance and Shiksha Shastri 02 Years Course 2026. Online applying process for Bihar CET B.Ed Online Form 2026 were accepted from 27 April 2026 to 18 May 2026. The Examination was conducted on 07 June 2026. Candidates who had applied this form can download their Bihar CET B.Ed Answer Key 2026 from the link given below."
    },
    "uppsc-assistant-professor-2025": {
      "title": "UPPSC Assistant Professor Answer Key 2026",
      "slug": "uppsc-assistant-professor-2025",
      "url": "https://www.sarkariexam.com/uppsc-assistant-professor-2025/",
      "category": "",
      "publishedDate": "2026-06-07T13:23:58+05:30",
      "intro": "Short Information : Uttar Pradesh Public Service Commission (UPPSC) has released the answer Key for the recruitment of Assistant Professor posts on its official website. This recruitment was released for 1236 posts. Applications for the UPPSC Assistant Professor Recruitment 2025 were accepted from 04 September 2025, to 06 October 2025. The online examination was conducted on 31 May 2026. Candidates who had appeared in this Examination can download their UPPSC Assistant Professor Answer Key 2026 from the link given below."
    },
    "up-tgt-2022": {
      "title": "UP TGT Answer Key 2026",
      "slug": "up-tgt-2022",
      "url": "https://www.sarkariexam.com/up-tgt-2022/",
      "category": "",
      "publishedDate": "2026-06-07T00:01:19+05:30",
      "intro": "Short Information : Uttar Pardesh Secondary Education Services Selection Board (UPSESSB) has released the answer key for selection to the posts of Trained Graduate Teacher (TGT) the Advt. No. 01/2022. The vacancy came in the year 2022 and it took almost two years to conduct the written examination for the prescribed posts. The written examination was held on 03 – 04 June 2026. Candidates who appeared for this examination can download their UP TGT Answer Key 2026 from the link given below."
    },
    "bihar-bssc-office-attendant-2022": {
      "title": "Bihar BSSC Office Attendant Mains Answer Key 2026",
      "slug": "bihar-bssc-office-attendant-2022",
      "url": "https://www.sarkariexam.com/bihar-bssc-office-attendant-2022/",
      "category": "",
      "publishedDate": "2026-06-05T11:24:45+05:30",
      "intro": "Short Information : Department of Science & Technology, Govt of Bihar has released the mains answer key for the post of Office Attendant (Karyaly Parichari). This recruitment was released for 238 posts. Applications for the Bihar DST Office Attendant Recruitment 2022 were accepted from September 23, 2022, to October 31, 2022. The mains examination was held on 26 May 2026. Candidates who appeared for this examination can download their Bihar BSSC Office Attendant Mains Answer Key 2026 from the link given below."
    },
    "jceceb-jharkhand-bed-2026": {
      "title": "JCECEB Jharkhand B.Ed Answer Key 2026",
      "slug": "jceceb-jharkhand-bed-2026",
      "url": "https://www.sarkariexam.com/jceceb-jharkhand-bed-2026/",
      "category": "",
      "publishedDate": "2026-06-04T12:35:11+05:30",
      "intro": "Short Information : Jharkhand Combined Entrance Competitive Examination Board (JCECEB) has released the answer key for the B.Ed/M.Ed/B.P.Ed. Combined Entrance Competitive Examination (CECE) Admission on the official website of the JCECEB recently For the two-year B.Ed. course (Academic Session 2026-28. Applications for the JCECEB B.Ed/M.Ed/B.P.Ed Admission Online Form 2026 were accepted from 25 February 2026, to 25 March 2026. The written examination was held on 31 May 2026. Candidates who appeared for this examination can download their JCECEB Jharkhand B.Ed Answer Key 2026 from the link given below."
    },
    "rssb-reet-mains-primary-teacher-2025": {
      "title": "RSSB REET Mains Primary Teacher Final Answer Key 2026",
      "slug": "rssb-reet-mains-primary-teacher-2025",
      "url": "https://www.sarkariexam.com/rssb-reet-mains-primary-teacher-2025/",
      "category": "",
      "publishedDate": "2026-06-03T16:06:22+05:30",
      "intro": "Short Information : Rajasthan Staff Selection Board (RSSB) has released the final answer key for the post of Level I Primary School Teacher Posts on the official website of RSSB. This recruitment was released for 5636 posts. Applications for the RSSB REET Mains Primary Teacher Recruitment 2025 were accepted from November 07, 2025, to December 06, 2025. The online examination was held on 17-20 January 2026. Candidates who appeared for this examination can download their RSSB REET Mains Primary Teacher Final Answer Key 2026 from the link given below."
    },
    "aadhar-card-print-verification-correction-form": {
      "title": "Aadhar Card PVC Download, Correction, Status 2026",
      "slug": "aadhar-card-print-verification-correction-form",
      "url": "https://www.sarkariexam.com/aadhar-card-print-verification-correction-form/",
      "category": "",
      "publishedDate": "2026-01-05T17:18:44+05:30",
      "intro": "Short Information : Aadhar card by Unique Identification Authority of India UIDAI which citizens also know by the name of my Aadhaar, my identity. This is a unique ID card for all citizens living in India.  How to Download Aadhaar Card, how to update it, how to change mobile number in Aadhaar Card, update address in Aadhaar Card, how to make correction in Aadhaar Card, how to download Aadhaar Card from mobile. Those All The Interested People Checking Aadhaar Card Details all the information related to the Aadhaar Card, Registration is given below and the link to apply is given in the Important Link section below."
    },
    "pan-card-registration-correction-other-service-2026": {
      "title": "PAN Card Registration, Correction & Other Service 2026",
      "slug": "pan-card-registration-correction-other-service-2026",
      "url": "https://www.sarkariexam.com/pan-card-registration-correction-other-service-2026/",
      "category": "",
      "publishedDate": "2026-01-05T17:18:40+05:30",
      "intro": "Short Information : The PAN (Permanent Account Number) is a vital document for citizens of India. Anyone who has applied for a PAN card can check the status of their application online via the official UTI or NSDL websites. These authorized PAN portals also provide services such as applying for a new PAN card, tracking application progress, making corrections, and updating PAN-related details. Access these services using the link provided below."
    },
    "bihar-caste-income-residence-certificate-online-form": {
      "title": "Bihar Income, Cast, Residential Certificate Online Apply & Verification 2026",
      "slug": "bihar-caste-income-residence-certificate-online-form",
      "url": "https://www.sarkariexam.com/bihar-caste-income-residence-certificate-online-form/",
      "category": "",
      "publishedDate": "2026-01-05T17:09:48+05:30",
      "intro": "Short Information : Under the e-District Mission Mode Project, the Right to Public Service (RTPS) Bihar has invited online applications for several government certificates. These include the Residential Certificate, Caste Certificate, Income Certificate, Character Certificate, Non-Creamy Layer (NCL) Certificate, and Economically Weaker Section (EWS) Certificate. Eligible male and female applicants can submit their applications online through the official RTPS Bihar portal at serviceonline.bihar.gov.in for Nivas Praman Patra, Jati Praman Patra, Aay Praman Patra, Charitra Praman Patra, as well as NCL and EWS certificates."
    },
    "up-caste-niwas-income-certificate-online-verification": {
      "title": "UP Caste, Niwas, Income Certificate Online Verification 2026",
      "slug": "up-caste-niwas-income-certificate-online-verification",
      "url": "https://www.sarkariexam.com/up-caste-niwas-income-certificate-online-verification/",
      "category": "",
      "publishedDate": "2026-01-05T16:31:31+05:30",
      "intro": "Short Information : The Uttar Pradesh Board of Revenue (UP BOR) provides an online facility to search and verify Income, Caste, and Domicile Certificates issued in Uttar Pradesh. Using the UP Document/Certificate Verification Portal, individuals can check the validity of certificates and documents required for different government services, helping to ensure their authenticity. This system enables applicants to determine whether their documents are genuine or fake."
    },
    "voter-id-registration-other-voter-service-2026": {
      "title": "Voter ID Registration & Other Voter Service 2026",
      "slug": "voter-id-registration-other-voter-service-2026",
      "url": "https://www.sarkariexam.com/voter-id-registration-other-voter-service-2026/",
      "category": "",
      "publishedDate": "2026-01-05T14:30:50+05:30",
      "intro": "Short Information : The Voter ID, formally known as the Election Photo Identity Card (EPIC), is an official photo identification issued by the Election Commission of India (ECI) to eligible Indian voters. It is used to confirm a voter’s identity, ensure a smooth and transparent voting process, and reduce the chances of impersonation and electoral malpractices during elections. Commonly, it is also called an election card, voter’s card, or Voter ID card."
    },
    "up-deled-admission-2026": {
      "title": "UP DELEd Admission 2026",
      "slug": "up-deled-admission-2026",
      "url": "https://www.sarkariexam.com/up-deled-admission-2026/",
      "category": "",
      "publishedDate": "2026-06-10T12:46:17+05:30",
      "intro": "Short Information : Examination Regulation Authority Allahabad Uttar Pradesh has released the notification for the Examination of UP BTC/ DELED Admission 2026. Candidates Can Also Check All Details on Official SarkariResult2026, Online applying process for UP Deled Admission 2026 will be started from 15 June 2026 & the candidates can apply till 08 July 2026. Candidates must check the complete details for UP Deled Admission 2026 Online Form which has given below."
    },
    "mpesb-pnst-2026": {
      "title": "MPESB PNST Online Form 2026",
      "slug": "mpesb-pnst-2026",
      "url": "https://www.sarkariexam.com/mpesb-pnst-2026/",
      "category": "",
      "publishedDate": "2026-06-09T15:57:50+05:30",
      "intro": "Short Information : Madhya Pradesh Employee Selection Board (MPESB) has released the notification for the Pre Nursing Selection Test (PNST) Admissions 2026 Examination. The online application process for MPESB PNST Online Form 2026 has started on 09 June 2026, and candidates can apply till 23 June 2026. Candidates must check the complete details for MPESB PNST Online Form 2026, which are given below."
    },
    "nta-icar-aieea-pg-phd-admissions-2026": {
      "title": "NTA ICAR AIEEA PG, Phd Admissions Online Form 2026",
      "slug": "nta-icar-aieea-pg-phd-admissions-2026",
      "url": "https://www.sarkariexam.com/nta-icar-aieea-pg-phd-admissions-2026/",
      "category": "",
      "publishedDate": "2026-06-08T15:42:19+05:30",
      "intro": "Short Information : National Testing Agency (NTA) has released the notification for the PG/ Ph.D Under NTA ICAR AIEEA Admission Entrance Examination 2026. The online application process for NTA ICAR AIEEA PG, Phd Admissions Online Form 2026 has started on 08 May 2026, and candidates can apply till 10 June 2026. Candidates must check the complete details for NTA ICAR AIEEA PG, Phd Admissions Online Form 2026, which are given below."
    },
    "uptac-admissions-2026": {
      "title": "UPTAC Admissions Online Registration 2026",
      "slug": "uptac-admissions-2026",
      "url": "https://www.sarkariexam.com/uptac-admissions-2026/",
      "category": "",
      "publishedDate": "2026-06-05T13:28:23+05:30",
      "intro": "Short Information : Uttar Pradesh Technical Admission & Counselling (UPTAC) has released the notification for the B.Tech / M.Tech / B.Arch / MCA / MBA / Other Courses Through CUET UG 2026 , JEEMAIN 2026 , NATA 2026 and CUET PG 2026 under UPTAC. The online application process for UPTAC Admissions Online Registration 2026 has started on 25 May 2026, and candidates can apply till 15 June 2026. Candidates must check the complete details for UPTAC Admissions Online Registration 2026, which are given below."
    }
  },
  "fetchedAt": "2026-06-11T10:15:08.726Z"
} as const;
