import cloudscraper from "cloudscraper";
import * as cheerio from "cheerio";
import { createInterface } from "readline";
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_FILE = resolve(__dirname, "..", "data", "scraped-data.ts");
const POSTS_DIR = resolve(__dirname, "..", "data", "posts");

const CATEGORIES = [
  { id: "results", label: "Result" },
  { id: "admitCards", label: "Admit Card" },
  { id: "latestJobs", label: "Latest Vacancy" },
  { id: "answerKeys", label: "Answer Key" },
  { id: "admissions", label: "Admission" },
  { id: "documents", label: "Documents" },
];

const rl = createInterface({ input: process.stdin, output: process.stdout });
function ask(q) {
  return new Promise((r) => rl.question(q, r));
}

function slugify(url) {
  return url.replace(/\/$/, "").split("/").pop().replace(/\.html?$/, "") || "post-" + Date.now();
}

function loadData() {
  const raw = readFileSync(DATA_FILE, "utf8");
  // Strip comment line, variable declaration, and trailing "as const;" or ";"
  const jsonStr = raw
    .replace(/^\/\/.*[\r\n]+/, "")
    .replace(/^export const scrapedData = /, "")
    .replace(/\s*as const\s*;\s*$/, "")
    .replace(/;\s*$/, "");
  return JSON.parse(jsonStr);
}

function saveData(data) {
  const ts = `// Auto-generated by auto-sync - DO NOT EDIT\nexport const scrapedData = ${JSON.stringify(data, null, 2)} as const;\n`;
  writeFileSync(DATA_FILE, ts, "utf8");
}

function scrapeDetails($) {
  const importantDates = [];
  const applicationFee = [];
  const importantLinks = [];
  const html = $.html();

  // --- EXTRACTOR 1: sarkariexam.com newtable1/2 layout (h3) ---
  $("div.newtable1").each((_, tbl) => {
    const $tbl = $(tbl);
    $tbl.find("h2, h3, h4").each((__, h) => {
      const text = $(h).text().toLowerCase();
      if (text.includes("important dates")) {
        $(h).closest("td.pd-0").find("ul li").each((_, li) => importantDates.push($(li).text().trim()));
      }
      if (text.includes("application fee")) {
        $(h).closest("td.pd-0").find("ul li").each((_, li) => applicationFee.push($(li).text().trim()));
      }
    });
  });

  // --- EXTRACTOR 2: GB Blocks layout (sarkariresult.com.cm) ---
  if (importantDates.length === 0) {
    $(".gb-container").each((_, container) => {
      const $c = $(container);
      $c.find(".gb-headline").each((__, hl) => {
        const text = $(hl).text().toLowerCase();
        if (text.includes("important dates")) {
          $(hl).nextAll("ul, table").first().find("li, tr").each((__, li) => {
            const t = $(li).text().trim();
            if (t && !t.toLowerCase().includes("important")) importantDates.push(t);
          });
        }
        if (text.includes("application fee")) {
          $(hl).nextAll("ul, table").first().find("li, tr").each((__, li) => {
            const t = $(li).text().trim();
            if (t && !t.toLowerCase().includes("application")) applicationFee.push(t);
          });
        }
      });
    });
  }

  // --- EXTRACTOR 3: Generic h2/h3 heading + next sibling ul/table ---
  if (importantDates.length === 0) {
    $("h2, h3, h4, strong").each((_, h) => {
      const text = $(h).text().toLowerCase();
      if (text.includes("important dates") || text.includes("important date")) {
        const $next = $(h).nextAll("ul, ol, table, div").first();
        if ($next.length) {
          $next.find("li, tr").each((__, li) => {
            const t = $(li).text().trim();
            if (t && !t.toLowerCase().includes("important")) importantDates.push(t);
          });
        }
      }
      if (text.includes("application fee") || text.includes("exam fee")) {
        const $next = $(h).nextAll("ul, ol, table, div").first();
        if ($next.length) {
          $next.find("li, tr").each((__, li) => {
            const t = $(li).text().trim();
            if (t) applicationFee.push(t);
          });
        }
      }
    });
  }

  // --- EXTRACTOR 4: Regex fallback for <strong>Important Dates</strong> + table ---
  if (importantDates.length === 0) {
    const m = html.match(/<strong>Important Dates[^<]*<\/strong>[\s\S]*?<table[^>]*>([\s\S]*?)<\/table>/i);
    if (m) {
      const $t = cheerio.load("<table>" + m[1] + "</table>");
      $t("tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length >= 2) {
          const label = cells.eq(0).text().trim();
          const value = cells.eq(1).text().trim();
          if (label && value && !label.toLowerCase().includes("important")) {
            importantDates.push(label + " : " + value);
          }
        }
      });
    }
  }

  // --- EXTRACTOR 5: Regex fallback for fee ---
  if (applicationFee.length === 0) {
    const m = html.match(/<strong>Application Fee[^<]*<\/strong>[\s\S]*?<table[^>]*>([\s\S]*?)<\/table>/i);
    if (m) {
      const $t = cheerio.load("<table>" + m[1] + "</table>");
      $t("tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length >= 2) {
          const label = cells.eq(0).text().trim();
          const value = cells.eq(1).text().trim();
          if (label && value) applicationFee.push(label + " : " + value);
        }
      });
    }
    // Also try plain text extract for fee
    if (applicationFee.length === 0) {
      const feeMatch = html.match(/<strong>Application Fee[^<]*<\/strong>[\s\S]*?<ul[^>]*>([\s\S]*?)<\/ul>/i);
      if (feeMatch) {
        const $f = cheerio.load("<ul>" + feeMatch[1] + "</ul>");
        $f("li").each((__, li) => {
          const t = $(li).text().trim();
          if (t) applicationFee.push(t);
        });
      }
    }
  }

  // --- Important Links: sarkariresult.com table layout (h2 in first td, link in second td) ---
  if (importantLinks.length === 0) {
    const skipLabels = ["important links", "mobile app", "whatsapp", "telegram", "android", "apple ios", "join our"];
    $("table").each((_, tbl) => {
      $(tbl).find("tr").each((_, row) => {
        const cells = $(row).find("td");
        if (cells.length >= 2) {
          const h2 = $(cells[0]).find("h2").text().trim();
          const link = $(cells[1]).find("a").attr("href");
          if (h2 && link && link.startsWith("http") && !skipLabels.some(s => h2.toLowerCase().includes(s))) {
            if (!importantLinks.some(l => l.label === h2)) {
              importantLinks.push({ label: h2, url: link });
            }
          }
        }
      });
    });
  }

  // --- Important Links (sarkariexam.com newtable2) ---
  $("div.newtable2").each((_, tbl) => {
    $(tbl).find("table tbody tr").each((_, row) => {
      const $tds = $(row).find("td.tcell");
      if ($tds.length >= 2) {
        const label = $tds.eq(0).find("h4 span, h4").text().trim();
        const linkUrl = $tds.eq(1).find("a").attr("href");
        if (label && !label.toLowerCase().includes("important links") && !label.toLowerCase().includes("mobile app") && !label.toLowerCase().includes("whatsapp") && !label.toLowerCase().includes("telegram")) {
          importantLinks.push({ label, url: linkUrl || "" });
        }
      }
    });
  });

  // --- Important Links fallback: generic table with Apply Online / Download links ---
  if (importantLinks.length === 0) {
    const linkKeywords = ["apply online", "download", "official website", "notification", "syllabus"];
    $("table").each((_, tbl) => {
      const $tbl = $(tbl);
      $tbl.find("a").each((__, a) => {
        const $a = $(a);
        const text = $a.text().trim();
        const href = $a.attr("href") || "";
        if (text && linkKeywords.some(k => text.toLowerCase().includes(k)) && !href.includes("javascript")) {
          if (!importantLinks.some(l => l.label === text)) {
            importantLinks.push({ label: text, url: href });
          }
        }
      });
    });
  }

  // --- Important Links fallback 2: GB Blocks links ---
  if (importantLinks.length === 0) {
    $(".gb-grid-column a").each((__, a) => {
      const $a = $(a);
      const text = $a.text().trim();
      const href = $a.attr("href") || "";
      if (text && href && href.startsWith("http") && !href.includes("whatsapp") && !href.includes("telegram")) {
        if (!importantLinks.some(l => l.label === text)) {
          importantLinks.push({ label: text, url: href });
        }
      }
    });
  }

  return { importantDates, applicationFee, importantLinks };
}

function toISO(dateStr) {
  if (!dateStr) return new Date().toISOString();
  try {
    const d = new Date(dateStr);
    if (!isNaN(d.getTime())) return d.toISOString();
  } catch {}
  // Try parsing "dd Month yyyy | HH:MM AM/PM"
  const m = dateStr.match(/(\d{1,2})\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+(\d{4})/i);
  if (m) {
    const d = new Date(`${m[3]}-${m[2].substring(0, 3)}-${m[1].padStart(2, "0")}`);
    if (!isNaN(d.getTime())) return d.toISOString().replace(".000Z", "+05:30").replace("Z", "+05:30");
  }
  return new Date().toISOString();
}

console.log("\n========================================");
console.log("  Manual Post Add Tool");
console.log("========================================\n");

const url = (await ask("Enter sarkari result URL: ")).trim();
if (!url) { console.log("No URL provided. Exiting."); process.exit(0); }

console.log("\nFetching page...");
let html;
try {
  html = await cloudscraper({ uri: url, method: "GET" });
} catch (e) {
  console.log("Failed to fetch URL:", e.message);
  process.exit(1);
}

const $ = cheerio.load(html);
const pageTitle = $("h1").first().text().trim() || $("title").text().trim() || "";

  // Intro: try multiple content area selectors
  const introSelectors = [
    "div.post-desc p",
    ".entry-content p",
    ".short_Details p",
    ".post-content p",
    "#content p",
    "div[class*='entry'] p",
    "div[class*='content'] p",
    "article p",
  ];
  let intro = "";
  for (const sel of introSelectors) {
    const t = $(sel).first().text().trim();
    if (t) { intro = t; break; }
  }
  // Fallback: look for "Short Information" in first table
  if (!intro) {
    $("table").eq(0).find("tr").each((_, row) => {
      const text = $(row).text().trim();
      if (text.toLowerCase().includes("short information")) {
        intro = text.replace(/Short Information\s*/i, "").trim();
      }
    });
  }

  // Published date: try multiple patterns
  const publishedDate = $("time.entry-date.published").attr("datetime")
    || $("time[datetime]").first().attr("datetime")
    || $("meta[property='article:published_time']").attr("content")
    || $(".post-date, .entry-date, .published, .meta-date, .date").first().text().trim()
    || $("[class*='date'], [class*='posted'], [class*='published']").first().text().trim()
    || "";

const details = scrapeDetails($);

console.log("\n--- Page Data ---");
console.log("Title:", pageTitle.substring(0, 80));
console.log("Published:", publishedDate || "(not found)");
console.log("Intro:", intro.substring(0, 100));
console.log("Dates found:", details.importantDates.length);
console.log("Fee lines:", details.applicationFee.length);
console.log("Links:", details.importantLinks.length);
console.log("-----------------\n");

const title = (await ask("Enter title (or press Enter to use page title): ")).trim() || pageTitle || "Untitled";
const slug = slugify(url);
const autoCat = title.toLowerCase().includes("admit") ? "admitCards"
  : title.toLowerCase().includes("answer key") ? "answerKeys"
  : title.toLowerCase().includes("admission") || title.toLowerCase().includes("counselling") ? "admissions"
  : title.toLowerCase().includes("certificate") || title.toLowerCase().includes("aadhar") || title.toLowerCase().includes("document") || title.toLowerCase().includes("pancard") || title.toLowerCase().includes("voter") ? "documents"
  : title.toLowerCase().includes("online form") || title.toLowerCase().includes("apply") || title.toLowerCase().includes("recruitment") || title.toLowerCase().includes("apprentice") || title.toLowerCase().includes("vacancy") ? "latestJobs"
  : title.toLowerCase().includes("result") ? "results"
  : "documents";

console.log("Suggested:", CATEGORIES.find((c) => c.id === autoCat)?.label);
console.log("\nCategories:");
CATEGORIES.forEach((c, i) => console.log(`  ${i + 1}. ${c.label}`));
const catChoice = parseInt((await ask(`Select [1-6] (default: ${CATEGORIES.findIndex(c => c.id === autoCat) + 1}): `)).trim() || (CATEGORIES.findIndex(c => c.id === autoCat) + 1).toString());
const category = CATEGORIES[catChoice - 1]?.id || autoCat;

const dateInput = (await ask("Enter date (or press Enter to use page date): ")).trim();
const dateISO = dateInput ? toISO(dateInput) : toISO(publishedDate);

const confirmed = (await ask(`\nAdd this?\n  Title: ${title}\n  URL: ${url}\n  Category: ${CATEGORIES.find(c => c.id === category)?.label}\nConfirm? (Y/n): `)).trim().toLowerCase();
if (confirmed === "n") { console.log("Cancelled."); process.exit(0); }

// Check for existing slug
const data = loadData();
const existingSlugs = new Set();
for (const key of ["results", "admitCards", "latestJobs", "answerKeys", "documents", "admissions"]) {
  for (const item of data[key] || []) {
    if (item.slug) existingSlugs.add(item.slug);
  }
}
if (existingSlugs.has(slug)) {
  const overwrite = (await ask(`Slug "${slug}" already exists! Overwrite? (y/N): `)).trim().toLowerCase();
  if (overwrite !== "y") { console.log("Cancelled."); process.exit(0); }
  // Remove old entries with this slug from all categories
  for (const key of ["results", "admitCards", "latestJobs", "answerKeys", "documents", "admissions"]) {
    if (data[key]) data[key] = data[key].filter((item) => item.slug !== slug);
  }
}

console.log("\nSaving...");
mkdirSync(POSTS_DIR, { recursive: true });

const post = {
  title,
  slug,
  url,
  category,
  publishedDate: dateISO,
  intro: intro || "",
  importantDates: details.importantDates,
  applicationFee: details.applicationFee,
  importantLinks: details.importantLinks,
  fullContentHtml: "",
};
writeFileSync(resolve(POSTS_DIR, `${slug}.json`), JSON.stringify(post, null, 2), "utf8");

if (!data[category]) data[category] = [];
data[category].unshift({ title, url, category, slug, publishedDate: dateISO });
if (!data.posts) data.posts = {};
data.posts[slug] = { lastDate: "", isExpired: false };
if (data.fetchedAt) data.fetchedAt = new Date().toISOString();
saveData(data);

console.log("Data saved locally.\n");

const deploy = (await ask("Deploy to production now? (Y/n): ")).trim().toLowerCase();
if (deploy !== "n") {
  console.log("\nDeploying to Vercel...");
  try {
    const out = execSync("npx vercel deploy --prod --yes", { cwd: resolve(__dirname, ".."), encoding: "utf8", timeout: 120000 });
    console.log(out);
    console.log("Deployed successfully!");
  } catch (e) {
    console.log("Deploy failed:", e.message);
  }
} else {
  console.log("Skipped deploy. Run 'npx vercel deploy --prod --yes' later.");
}

rl.close();
console.log("\nDone!");
