import cloudscraper from "cloudscraper";
import * as cheerio from "cheerio";
import * as https from "https";
import * as http from "http";
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_FILE = resolve(__dirname, "..", "data", "scraped-data.ts");
const POSTS_DIR = resolve(__dirname, "..", "data", "posts");
const FETCH_TIMEOUT = 20000; // 20s per request
const CONCURRENCY = 5;       // 5 parallel detail fetches
const MAX_DETAIL_TIME = 300000; // 5min overall for detail scraping

function loadData() {
  const raw = readFileSync(DATA_FILE, "utf8");
  const jsonStr = raw
    .replace(/^\/\/.*[\r\n]+/, "")
    .replace(/^export const scrapedData = /, "")
    .replace(/\s*as const\s*;\s*$/, "")
    .replace(/;\s*$/, "");
  return JSON.parse(jsonStr);
}

const __timers = new Set();

function saveData(data) {
  const ts = `// Auto-generated by sync-all - DO NOT EDIT\nexport const scrapedData = ${JSON.stringify(data, null, 2)};\n`;
  writeFileSync(DATA_FILE, ts, "utf8");
  // Also write JSON version for runtime loading (avoids Vercel bundling 100MB+)
  const jsonPath = resolve(__dirname, "..", "data", "scraped.json");
  writeFileSync(jsonPath, JSON.stringify(data, null, 2), "utf8");
}

function sanitizeSlug(s) {
  return s.replace(/[<>:"/\\|?*]+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "") || "post";
}

function fetchHtmlFallback(url) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const mod = u.protocol === "https:" ? https : http;
    const req = mod.get(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
      },
      timeout: FETCH_TIMEOUT,
    }, (res) => {
      let data = "";
      res.on("data", (chunk) => { data += chunk; });
      res.on("end", () => {
        if (res.statusCode !== 200 && res.statusCode !== 404) {
          return reject(new Error(`HTTP ${res.statusCode}`));
        }
        resolve(data);
      });
    });
    req.on("error", reject);
    req.on("timeout", () => { req.destroy(); reject(new Error("Timeout")); });
  });
}

async function fetchHtml(url) {
  // First try cloudscraper
  try {
    const html = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error("Timeout")), FETCH_TIMEOUT);
      cloudscraper({ uri: url, method: "GET" })
        .then((h) => { clearTimeout(timer); resolve(h); })
        .catch((err) => { clearTimeout(timer); reject(err); });
    });
    // Only fall back if page is clearly a Cloudflare-only challenge (not real content)
    if (html.length < 500 || (html.includes("Just a moment") && !html.includes("<!DOCTYPE")) || (html.includes("_cf_chl") && !html.includes("</html>"))) {
      return fetchHtmlFallback(url);
    }
    return html;
  } catch {
    return fetchHtmlFallback(url);
  }
}

// ======== Source 1: sarkariresult.com ========

async function scrapeSarkariResult() {
  const html = await fetchHtml("https://www.sarkariresult.com/");
  const $ = cheerio.load(html);

  const viewMorePaths = [];
  $("a.gb-button").each((_, a) => {
    const $a = $(a);
    if ($a.text().trim().toLowerCase() === "view more") {
      const href = $a.attr("href") || "";
      const path = href.replace(/https?:\/\/[^/]+\//, "").replace(/\/$/, "");
      viewMorePaths.push(path);
    }
  });

  const CATEGORY_MAP = { result: "results", admitcard: "admitCards", latestjob: "latestJobs", answerkey: "answerKeys", admission: "admissions" };
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  let containerIdx = 0;
  const seen = new Set();

  $("div[class*=gb-container]").each((_, el) => {
    const $el = $(el);
    const postLinks = $el.find("a[href]").filter((_, a) => $(a).text().trim().length > 15);
    if (postLinks.length < 3) return;

    const vmPath = viewMorePaths[containerIdx] || "";
    const category = CATEGORY_MAP[vmPath] || "";
    containerIdx++;

    if (!category) return;

    postLinks.each((_, a) => {
      const $a = $(a);
      const url = $a.attr("href") || "";
      if (!url || url.toLowerCase().includes(".pdf") || seen.has(url)) return;
      seen.add(url);
      const rawTitle = $a.text().trim();
      const title = cleanCompetitorText(rawTitle);
      if (isJunkOrSpam(title, url)) return;
      const properCat = categorizePost(title, category);
      const slug = generatePostSlug(url, title);
      if (items[properCat]) {
        items[properCat].push({ title, url, category: properCat, slug });
      }
    });
  });

  return items;
}

function cleanLinkLabel(label) {
  if (!label) return "";
  let clean = label.trim();
  const half = Math.floor(clean.length / 2);
  if (clean.length > 4 && clean.slice(0, half) === clean.slice(half)) {
    clean = clean.slice(0, half).trim();
  }
  return clean;
}

async function scrapeSarkariResultDetail(url) {
  try {
    const html = await fetchHtml(url);
    const $ = cheerio.load(html);

    const title = $("h1").first().text().trim() || $("title").text().trim();
    const slug = url.replace(/\/$/, "").split("/").pop().replace(/\.html?$/, "") || "post";

    let publishedDate = $("meta[property='article:published_time']").attr("content") || "";
    if (publishedDate) {
      const d = new Date(publishedDate);
      if (!isNaN(d.getTime())) {
        if (d > new Date()) {
          publishedDate = "";
        } else {
          publishedDate = d.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
        }
      }
    }

    let intro = "";
    $("h3, strong, b").each((_, el) => {
      const text = $(el).text().trim().toLowerCase();
      if (text.includes("short information") || text.includes("brief information")) {
        intro = $(el).parent().next("p").text().trim() || $(el).closest("div").find("p").first().text().trim();
      }
    });
    if (!intro) intro = $(".entry-content p").first().text().trim().slice(0, 300);

    const importantDates = [];
    $("table").each((_, table) => {
      const $table = $(table);
      $table.find("tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length >= 2) {
          const first = $(cells[0]).text().trim().toLowerCase();
          const second = $(cells[1]).text().trim();
          if (first && second && (first.includes("date") || first.includes("fee") || first.includes("age") || first.includes("exam") || !first.includes("link"))) {
            importantDates.push($(cells[0]).text().trim() + " : " + second);
          }
        }
      });
    });

    const importantLinks = [];
    const seenUrls = new Set();
    $("table tr").each((_, row) => {
      const cells = $(row).find("td, th");
      if (cells.length >= 2) {
        const col0Text = $(cells[0]).text().trim();
        const $links = $(cells[1]).find("a[href]");
        if ($links.length > 0) {
          $links.each((_, a) => {
            const $a = $(a);
            const aText = $a.text().trim();
            const href = $a.attr("href") || "";
            if (!href || href === "#" || href.startsWith("javascript") || seenUrls.has(href)) return;

            let label = col0Text;
            if (!label || label.toLowerCase().includes("click here") || label.length < 3) {
              label = aText;
            } else if (aText && !aText.toLowerCase().includes("click here") && aText.toLowerCase() !== label.toLowerCase()) {
              label = `${col0Text} (${aText})`;
            }

            label = cleanLinkLabel(label);
            const lowerLabel = label.toLowerCase();
            if (lowerLabel.includes("whatsapp") || lowerLabel.includes("telegram") || lowerLabel.includes("mobile app") || lowerLabel.includes("join")) return;

            seenUrls.add(href);
            importantLinks.push({ label, url: href });
          });
        }
      }
    });

    if (importantLinks.length === 0) {
      $("table a, .entry-content a").each((_, link) => {
        const $link = $(link);
        const label = cleanLinkLabel($link.text().trim());
        const href = $link.attr("href") || "";
        if (label && href && href !== "#" && !href.startsWith("javascript") && !seenUrls.has(href)) {
          const lower = label.toLowerCase();
          if (!lower.includes("whatsapp") && !lower.includes("telegram")) {
            seenUrls.add(href);
            importantLinks.push({ label, url: href });
          }
        }
      });
    }

    return { title, slug, url, publishedDate, intro, importantDates, applicationFee: [], importantLinks, fullContentHtml: "" };
  } catch {
    return null;
  }
}

// ======== Competitor Traces & Spam Cleaning ========

const COMPETITOR_DOMAINS = [
  "sarkariexam.com", "freejobalert.com", "naukaritime.com", "naukritime.com",
  "sarkariresult.com", "resultbharat.com", "sarkarialert.net", "rojgarresult.com",
  "instagram.com", "facebook.com", "twitter.com", "x.com", "youtube.com",
  "t.me", "whatsapp.com", "play.google.com"
];

const COMPETITOR_REGEX = /sarkariexam(?:\.com)?|freejobalert(?:\.com)?|naukaritime(?:\.com)?|naukritime(?:\.com)?|sarkariresult(?:\.com)?|resultbharat(?:\.com)?|sarkarialert(?:\.net)?|rojgarresult(?:\.com)?/gi;

function cleanCompetitorText(text) {
  if (!text) return "";
  return text
    .replace(/Author\s*:\s*Sarkari\s*Exam\s*Team/gi, "")
    .replace(/Tag\s*:\s*[^\n\r<]+/gi, "")
    .replace(COMPETITOR_REGEX, "All India Exam Result")
    .trim();
}

function isCompetitorLink(url, label) {
  if (!url || url === "#" || url.startsWith("javascript")) return true;
  const lowerUrl = url.toLowerCase();
  const lowerLabel = (label || "").toLowerCase();
  if (COMPETITOR_DOMAINS.some(d => lowerUrl.includes(d))) return true;
  if (lowerLabel.includes("whatsapp") || lowerLabel.includes("telegram") || lowerLabel.includes("instagram") ||
      lowerLabel.includes("mobile app") || lowerLabel.includes("join channel") || lowerLabel.includes("download app") ||
      lowerLabel.includes("sarkariexam") || lowerLabel.includes("freejobalert") || lowerLabel.includes("naukaritime") ||
      lowerLabel.includes("sarkari result") || lowerLabel.includes("sarkari exam") || lowerLabel.includes("result bharat")) return true;
  return false;
}

function isJunkOrSpam(title, url) {
  if (!title || !url) return true;
  const t = (title || "").toLowerCase();
  const u = (url || "").toLowerCase();

  if (u === "#" || u.startsWith("javascript") || u.endsWith(".pdf") || u.endsWith(".zip") || u.endsWith(".doc")) return true;
  if (u.includes("testbook.com/login") || (u.includes("shorturl.at") && !t)) return true;
  if (t.includes("get started for free") || t.includes("sarkari result shine") || t.includes("check driving licence") || t.includes("rcdlstatus")) return true;
  if (t.includes("privacy policy") || t.includes("disclaimer") || t.includes("terms and condition") || t.includes("contact us") || t.includes("about us")) return true;
  return false;
}

function generatePostSlug(url, title) {
  const tSlug = (title || "")
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .slice(0, 75);

  if (!url) return tSlug || "post";
  const lowerUrl = url.toLowerCase();

  // Shorteners and non-post external URLs
  if (lowerUrl.includes("tinyurl.com") || lowerUrl.includes("bit.ly") || lowerUrl.includes("shorturl.at") ||
      lowerUrl.includes("cutt.ly") || lowerUrl.includes("parivahan.gov.in") || lowerUrl.includes("testbook.com")) {
    return tSlug || "post";
  }

  const rawSlug = url.replace(/\/$/, "").split("/").pop().replace(/\.html?$/i, "").replace(/\.pdf$/i, "");
  if (!rawSlug || rawSlug.length <= 6 || /^[a-z0-9]{4,8}$/i.test(rawSlug)) {
    return tSlug || "post";
  }

  return rawSlug.toLowerCase();
}

function categorizePost(title, fallbackCat = "latestJobs") {
  const t = (title || "").toLowerCase();

  // 1. Result ALWAYS takes priority if result / score / cutoff / marks / merit list / qualified
  if (/\b(result|scorecard|marks|merit list|cut\s*off|selection list|shortlist|allotment result|qualified|selected candidates?)\b/i.test(t)) {
    return "results";
  }

  // 2. Answer key
  if (/\b(answer key|response sheet|objection|omr sheet|model answer)\b/i.test(t)) {
    return "answerKeys";
  }

  // 3. Admission / Counselling
  if (/\b(admission|counselling|counseling|seat allotment|entrance test|entrance exam|deled|b\.ed entrance)\b/i.test(t)) {
    return "admissions";
  }

  // 4. Strict Admit Card / Hall Ticket / Call Letter (Pravesh Patra)
  if (/\b(admit card|hall ticket|call letter|pravesh patra)\b/i.test(t)) {
    return "admitCards";
  }

  // 5. Interview Schedule -> results (part of exam interview stage)
  if (/\b(interview schedule|interview letter|interview date|interview list)\b/i.test(t)) {
    return "results";
  }

  // 6. Exam Date / Exam Schedule / Syllabus / Document Verification / Notices -> documents
  if (/\b(exam date|exam schedule|new exam date|revised exam date|time table|schedule|dv schedule|document verification|syllabus|pattern|certificate|application status|rejected list|exam city)\b/i.test(t)) {
    return "documents";
  }

  // 7. Latest Vacancy / Recruitment / Apply
  if (/\b(online form|apply online|recruitment|vacancy|vacancies|apprentice|bharti|posts?|officer|assistant|constable|teacher)\b/i.test(t)) {
    return "latestJobs";
  }

  return fallbackCat || "latestJobs";
}

// ======== Source 2: sarkariexam.com ========

const HEADING_MAP = {
  "result": "results",
  "exam result": "results",
  "new updates": "results",
  "admit card": "admitCards",
  "top online form": "latestJobs",
  "answer keys": "answerKeys",
  "answer key": "answerKeys",
  "admission form": "admissions",
  "document verification": "documents",
  "documents verification": "documents",
  "syllabus": "documents",
  "latest news": "results",
  "diploma / iti": "latestJobs",
  "b.tech / m.tech": "latestJobs",
};

async function scrapeSarkariExam() {
  const html = await fetchHtml("https://www.sarkariexam.com/");
  const $ = cheerio.load(html);
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  const seen = new Set();

  $(".below-block").each((_, block) => {
    const $block = $(block);
    let heading = $block.find("h4.wp-block-heading").text().trim().toLowerCase().replace(/<\/?strong>/g, "");
    if (!heading) {
      heading = $block.find("h4").text().trim().toLowerCase().replace(/<\/?strong>/g, "");
    }
    if (!heading) return;

    const key = HEADING_MAP[heading];
    if (!key || !items[key]) return;

    $block.find("ul.wp-block-latest-posts__list li a.wp-block-latest-posts__post-title").each((__, link) => {
      const $link = $(link);
      const url = $link.attr("href") || "";
      if (!url || seen.has(url)) return;
      seen.add(url);
      const rawTitle = $link.text().trim();
      const title = cleanCompetitorText(rawTitle);
      if (isJunkOrSpam(title, url)) return;
      const finalCat = categorizePost(title, key);
      const slug = generatePostSlug(url, title);
      if (items[finalCat]) {
        items[finalCat].push({ title, url, category: finalCat, slug });
      }
    });
  });

  return items;
}

async function scrapeSarkariExamDetail(url) {
  try {
    const html = await fetchHtml(url);
    const $ = cheerio.load(html);

    const titleText = $("title").text().trim().toLowerCase();
    if (titleText.includes("page not found") || html.length < 1000) {
      return { publishedDate: "", intro: "", importantDates: [], applicationFee: [], importantLinks: [] };
    }

    let publishedDate = $("time.entry-date.published").attr("datetime") || "";
    if (publishedDate) {
      const d = new Date(publishedDate);
      if (!isNaN(d.getTime()) && d > new Date()) publishedDate = "";
    }
    let intro = $("div.post-desc p").text().trim() || $("div.entry-content p").first().text().trim() || "";
    intro = cleanCompetitorText(intro);

    const importantDates = [];
    const applicationFee = [];
    const $table1 = $("div.newtable1");
    if ($table1.length) {
      $table1.find("h3").each((_, h) => {
        const text = $(h).text().trim();
        const lower = text.toLowerCase();
        if (lower.includes("important date") || lower.includes("exam date") || lower.includes("application fee") || lower.includes("fee detail")) {
          const $table = $(h).next("table");
          if ($table.length) {
            $table.find("tr").each((__, row) => {
              const cells = $(row).find("td");
              if (cells.length >= 2) {
                const col0 = cleanLinkLabel(cells.eq(0).text().trim());
                const col1 = cleanLinkLabel(cells.eq(1).text().trim());
                if (col0 && col1 && col0.length < 60 && col1.length < 60 && !col0.includes("\n") && !col1.includes("\n") && !/qualification|post name|click here|download/i.test(col0 + col1)) {
                  const entry = `${col0} : ${col1}`;
                  if (lower.includes("fee")) {
                    applicationFee.push(entry);
                  } else {
                    importantDates.push(entry);
                  }
                }
              }
            });
          }
        }
      });
    }
    if (importantDates.length === 0) {
      $("table").each((_, t) => {
        $(t).find("tr").each((_, row) => {
          const cells = $(row).find("td, th");
          if (cells.length >= 2) {
            const first = $(cells[0]).text().trim();
            const second = $(cells[1]).text().trim();
            const fLower = first.toLowerCase();
            if (first && second && first.length < 60 && second.length < 60 && !first.includes("\n") && !second.includes("\n") && !/qualification|post name|click here|download/i.test(first + second)) {
              if (fLower.includes("date") || fLower.includes("last") || fLower.includes("exam") || fLower.includes("admit")) {
                importantDates.push(first + " : " + second);
              }
            }
          }
        });
      });
    }

    const spamLabels = ["sarkari exam mobile app", "join whatsapp channel", "join telegram channel"];
    const importantLinks = [];
    const seenUrls = new Set();
    const $table2 = $("div.newtable2");
    if ($table2.length) {
      $table2.find("table tbody tr").each((_, row) => {
        const $tds = $(row).find("td.tcell");
        if ($tds.length >= 2) {
          const col0Text = $tds.eq(0).find("h4 span, h4").text().trim() || $tds.eq(0).text().trim();
          const $links = $tds.eq(1).find("a[href]");
          $links.each((_, a) => {
            const linkUrl = $(a).attr("href") || "";
            const aText = $(a).text().trim();
            if (!linkUrl || linkUrl === "#" || linkUrl.startsWith("javascript") || seenUrls.has(linkUrl)) return;

            let label = col0Text;
            if (!label || label.toLowerCase().includes("important links")) {
              label = aText;
            } else if (aText && !aText.toLowerCase().includes("click here") && aText.toLowerCase() !== label.toLowerCase()) {
              label = `${col0Text} (${aText})`;
            }
            label = cleanLinkLabel(label);
            if (isCompetitorLink(linkUrl, label)) return;

            seenUrls.add(linkUrl);
            importantLinks.push({ label: cleanCompetitorText(label), url: linkUrl });
          });
        }
      });
    }

    if (importantLinks.length === 0) {
      $("table tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length >= 2) {
          const col0Text = $(cells[0]).text().trim();
          const $links = $(cells[1]).find("a[href]");
          $links.each((_, a) => {
            const href = $(a).attr("href") || "";
            const aText = $(a).text().trim();
            if (!href || href === "#" || href.startsWith("javascript") || seenUrls.has(href)) return;

            let label = col0Text || aText;
            if (aText && !aText.toLowerCase().includes("click here") && aText.toLowerCase() !== col0Text.toLowerCase()) {
              label = `${col0Text} (${aText})`;
            }
            label = cleanLinkLabel(label);
            if (isCompetitorLink(href, label)) return;

            seenUrls.add(href);
            importantLinks.push({ label: cleanCompetitorText(label), url: href });
          });
        }
      });
    }

    if (importantLinks.length === 0) {
      $("a[href]").each((_, a) => {
        const $a = $(a);
        const label = cleanLinkLabel($a.text().trim());
        const href = $a.attr("href") || "";
        if (label && href && href !== "#" && !href.startsWith("javascript") && !seenUrls.has(href)) {
          const lower = label.toLowerCase();
          if (!spamLabels.some((s) => lower.includes(s))) {
            seenUrls.add(href);
            importantLinks.push({ label, url: href });
          }
        }
      });
    }
    return { publishedDate, intro, importantDates, applicationFee, importantLinks };
  } catch {
    return { publishedDate: "", intro: "", importantDates: [], applicationFee: [], importantLinks: [] };
  }
}

// ======== Source 3: FreeJobAlert (Layout & Section Based) ========

async function scrapeFreeJobAlert() {
  const html = await fetchHtml("https://www.freejobalert.com/");
  const $ = cheerio.load(html);
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  const seen = new Set();

  const FJA_MAP = {
    "job notifications": "latestJobs",
    "state job notifications": "latestJobs",
    "admit card": "admitCards",
    "results": "results",
    "answer keys": "answerKeys",
    "syllabus": "documents",
  };

  $(".hpgjbcont").each((_, container) => {
    const $c = $(container);
    const titleText = $c.find(".nutitle").text().trim().toLowerCase();
    const cat = FJA_MAP[titleText];
    if (!cat || !items[cat]) return;

    $c.find("ul li a[href]").each((__, a) => {
      const $a = $(a);
      let href = $a.attr("href") || "";
      const rawTitle = $a.text().trim();
      if (!href || rawTitle.length < 12 || seen.has(href)) return;
      if (href.includes("#") || href.startsWith("javascript")) return;
      if (!href.startsWith("http")) href = "https://www.freejobalert.com" + href;
      seen.add(href);
      const title = cleanCompetitorText(rawTitle);
      if (isJunkOrSpam(title, href)) return;
      const finalCat = categorizePost(title, cat);
      const slug = generatePostSlug(href, title);
      if (items[finalCat]) items[finalCat].push({ title, url: href, category: finalCat, slug });
    });
  });

  return items;
}

// ======== Source 4: NaukariTime (Layout & Section Based) ========

async function scrapeNaukariTime() {
  const html = await fetchHtml("https://naukaritime.com/");
  const $ = cheerio.load(html);
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  const seen = new Set();

  const NT_MAP = {
    "latest job": "latestJobs",
    "admit card": "admitCards",
    "result": "results",
    "admission": "admissions",
    "defence job": "latestJobs",
  };

  $(".post-card").each((_, card) => {
    const $c = $(card);
    const heading = $c.find("h2.card-heading").text().trim().toLowerCase();
    const cat = NT_MAP[heading];
    if (!cat || !items[cat]) return;

    $c.find("li a[href]").each((__, a) => {
      const $a = $(a);
      let href = $a.attr("href") || "";
      const rawTitle = $a.text().trim();
      if (!href || rawTitle.length < 15 || rawTitle.toLowerCase().includes("view more") || seen.has(href)) return;
      if (href.includes("#") || href.startsWith("javascript")) return;
      if (!href.startsWith("http")) href = "https://naukaritime.com" + (href.startsWith("/") ? href : "/" + href);
      seen.add(href);
      const title = cleanCompetitorText(rawTitle);
      if (isJunkOrSpam(title, href)) return;
      const finalCat = categorizePost(title, cat);
      const slug = generatePostSlug(href, title);
      if (items[finalCat]) items[finalCat].push({ title, url: href, category: finalCat, slug });
    });
  });

  return items;
}

async function scrapeResultBharat() {
  const html = await fetchHtml("https://www.resultbharat.com/");
  const $ = cheerio.load(html);
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  const seen = new Set();
  $("h3 a[href]").each((_, a) => {
    const $a = $(a);
    let href = $a.attr("href") || "";
    const rawTitle = $a.text().trim();
    if (!href || rawTitle.length < 15 || seen.has(href)) return;
    if (href.toLowerCase().includes(".pdf") || href.toLowerCase().includes("/notice/")) return;
    seen.add(href);
    if (!href.startsWith("http")) href = "https://www.resultbharat.com" + (href.startsWith("/") ? href : "/" + href);
    const title = cleanCompetitorText(rawTitle);
    if (isJunkOrSpam(title, href)) return;
    const cat = categorizePost(title, "latestJobs");
    const slug = generatePostSlug(href, title);
    if (items[cat]) items[cat].push({ title, url: href, category: cat, slug });
  });
  return items;
}

async function scrapeSarkariAlert() {
  const html = await fetchHtml("https://sarkarialert.net/");
  const $ = cheerio.load(html);
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  const seen = new Set();
  $("a[href]").each((_, a) => {
    const $a = $(a);
    let href = $a.attr("href") || "";
    const rawTitle = $a.text().trim();
    if (!href || rawTitle.length < 20 || seen.has(href)) return;
    if (href.toLowerCase().includes(".pdf")) return;
    if (href.includes("#") || href.startsWith("javascript")) return;
    seen.add(href);
    if (!href.startsWith("http")) href = "https://sarkarialert.net" + (href.startsWith("/") ? href : "/" + href);
    const title = cleanCompetitorText(rawTitle);
    if (isJunkOrSpam(title, href)) return;
    const cat = categorizePost(title, "latestJobs");
    const slug = generatePostSlug(href, title);
    if (items[cat]) items[cat].push({ title, url: href, category: cat, slug });
  });
  return items;
}

async function scrapeRojgarResult() {
  const html = await fetchHtml("https://rojgarresult.com/");
  const $ = cheerio.load(html);
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  const seen = new Set();
  $("h2 a[href], h3 a[href]").each((_, a) => {
    const $a = $(a);
    let href = $a.attr("href") || "";
    const rawTitle = $a.text().trim();
    if (!href || rawTitle.length < 20 || seen.has(href)) return;
    if (href.toLowerCase().includes(".pdf")) return;
    seen.add(href);
    if (!href.startsWith("http")) href = "https://rojgarresult.com" + (href.startsWith("/") ? href : "/" + href);
    const title = cleanCompetitorText(rawTitle);
    if (isJunkOrSpam(title, href)) return;
    const cat = categorizePost(title, "latestJobs");
    const slug = generatePostSlug(href, title);
    if (items[cat]) items[cat].push({ title, url: href, category: cat, slug });
  });
  return items;
}

async function scrapeGenericDetail(url) {
  try {
    const html = await fetchHtml(url);
    const $ = cheerio.load(html);
    const rawTitle = $("h1").first().text().trim() || $("title").text().trim();
    const title = cleanCompetitorText(rawTitle);
    let publishedDate = $("meta[property='article:published_time']").attr("content") || $("time").attr("datetime") || "";
    if (publishedDate) {
      const d = new Date(publishedDate);
      if (!isNaN(d.getTime())) {
        if (d > new Date()) {
          publishedDate = "";
        } else {
          publishedDate = d.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
        }
      }
    }
    // Content search for real Post Date / Start Date if publishedDate is missing
    if (!publishedDate) {
      const pageText = $("body").text();
      const match = pageText.match(/Post\s*(?:Time|Date)\s*:\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})/i) ||
                    pageText.match(/(?:Online\s*Apply\s*Start\s*on|Apply\s*Start\s*Date|Start\s*Date)\s*[:\-]?\s*(\d{1,2}\s+[A-Za-z]+\s+\d{4})/i);
      if (match) {
        const d = new Date(match[1]);
        if (!isNaN(d.getTime()) && d <= new Date()) {
          publishedDate = d.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
        }
      }
    }
    let intro = $("meta[name='description']").attr("content") || "";
    if (intro.length < 10) intro = $("article p, .entry-content p, .post-content p").first().text().trim().slice(0, 300);
    if (!intro) intro = $("p").first().text().trim().slice(0, 300);
    intro = cleanCompetitorText(intro);

    const importantDates = [];
    const applicationFee = [];
    $("table").each((_, table) => {
      $(table).find("tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length >= 2) {
          const first = $(cells[0]).text().trim().toLowerCase();
          const second = $(cells[1]).text().trim();
          if (first && second) {
            if (first.includes("date") || first.includes("last") || first.includes("exam") || first.includes("admit")) importantDates.push($(cells[0]).text().trim() + " : " + second);
            if (first.includes("fee") || first.includes("general") || first.includes("obc") || first.includes("sc") || first.includes("st")) applicationFee.push($(cells[0]).text().trim() + " : " + second);
          }
        }
      });
    });

    const importantLinks = [];
    const seenLinkUrls = new Set();
    $("a[href]").each((_, link) => {
      const $link = $(link);
      const rawLabel = cleanLinkLabel($link.text().trim());
      const label = cleanCompetitorText(rawLabel);
      const href = $link.attr("href") || "";
      if (label && href && !isCompetitorLink(href, label) && !seenLinkUrls.has(href)) {
        const lower = label.toLowerCase();
        if (lower.includes("official") || lower.includes("apply") || lower.includes("download") || lower.includes("result") || lower.includes("admit") || lower.includes("answer") || lower.includes("website") || lower.includes("notification") || lower.includes("registration") || lower.includes("score")) {
          seenLinkUrls.add(href);
          importantLinks.push({ label, url: href });
        }
      }
    });

    const slug = generatePostSlug(url, title);
    return { title, slug, url, publishedDate, intro, importantDates, applicationFee, importantLinks, fullContentHtml: "" };
  } catch {
    return null;
  }
}

// ======== Main ========

function mergeSourceData(sourceName, sourceData, existing, existingUrls, newItems) {
  let count = 0;
  for (const rawCat of ["results", "admitCards", "latestJobs", "answerKeys", "documents", "admissions"]) {
    const freshItems = sourceData[rawCat] || [];
    for (const item of freshItems) {
      if (isJunkOrSpam(item.title, item.url)) continue;
      const finalCat = categorizePost(item.title, rawCat);
      item.category = finalCat;
      item.slug = generatePostSlug(item.url, item.title);

      const targetList = existing[finalCat] || (existing[finalCat] = []);
      const url = (item.url || "").replace(/\/$/, "");
      if (!existingUrls.has(url)) {
        targetList.unshift(item); // Prepend to top so it's fresh in section layout!
        existingUrls.add(url);
        newItems.push(item);
        count++;
      }
    }
  }
  console.log(`  ${count} new items found`);
  return count;
}

async function main() {
  const start = Date.now();
  console.log("Loading existing data...");
  const existing = loadData();
  const existingUrls = new Set();

  for (const key of ["results", "admitCards", "latestJobs", "answerKeys", "documents", "admissions"]) {
    for (const item of (existing[key] || [])) {
      if (item.url) existingUrls.add(item.url.replace(/\/$/, ""));
    }
  }

  let totalNew = 0;
  const newItems = [];
  const newSlugs = []; // Track slugs of new posts for IndexNow

  // ---- Source 1: sarkariresult.com ----
  console.log("\n[1/7] Fetching sarkariresult.com...");
  try {
    const srData = await scrapeSarkariResult();
    totalNew += mergeSourceData("sarkariresult.com", srData, existing, existingUrls, newItems);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 2: sarkariexam.com ----
  console.log("\n[2/7] Fetching sarkariexam.com (Section-wise)...");
  try {
    const seData = await scrapeSarkariExam();
    totalNew += mergeSourceData("sarkariexam.com", seData, existing, existingUrls, newItems);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 3: freejobalert.com ----
  console.log("\n[3/7] Fetching freejobalert.com (Section-wise)...");
  try {
    const fjaData = await scrapeFreeJobAlert();
    totalNew += mergeSourceData("freejobalert.com", fjaData, existing, existingUrls, newItems);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 4: naukaritime.com ----
  console.log("\n[4/7] Fetching naukaritime.com (Section-wise)...");
  try {
    const ntData = await scrapeNaukariTime();
    totalNew += mergeSourceData("naukaritime.com", ntData, existing, existingUrls, newItems);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 5: resultbharat.com ----
  console.log("\n[5/7] Fetching resultbharat.com...");
  try {
    const rbData = await scrapeResultBharat();
    totalNew += mergeSourceData("resultbharat.com", rbData, existing, existingUrls, newItems);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 6: sarkarialert.net ----
  console.log("\n[6/7] Fetching sarkarialert.net...");
  try {
    const saData = await scrapeSarkariAlert();
    totalNew += mergeSourceData("sarkarialert.net", saData, existing, existingUrls, newItems);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 7: rojgarresult.com ----
  console.log("\n[7/7] Fetching rojgarresult.com...");
  try {
    const rrData = await scrapeRojgarResult();
    totalNew += mergeSourceData("rojgarresult.com", rrData, existing, existingUrls, newItems);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Re-scrape existing empty post files ----
  const existingFiles = readdirSync(POSTS_DIR).filter(f => f.endsWith(".json"));
  const reScrapeQueue = [];
  for (const file of existingFiles) {
    try {
      const p = JSON.parse(fs.readFileSync(POSTS_DIR + "/" + file, "utf8"));
      const empty = (!p.intro || p.intro.length < 5) && (!p.fullContentHtml || p.fullContentHtml.length < 20) && p.url;
      if (empty && p.url && !p.url.includes("tinyurl") && !p.url.includes("pdf")) {
        // Only re-scrape known source URLs
        if (p.url.includes("sarkariresult.com") || p.url.includes("sarkariexam.com") || p.url.includes("resultbharat.com") || p.url.includes("sarkarialert.net") || p.url.includes("rojgarresult.com") || p.url.includes("naukaritime.com") || p.url.includes("freejobalert.com")) {
          reScrapeQueue.push({ file, url: p.url, slug: p.slug || file.replace(".json", ""), title: p.title || "" });
        }
      }
    } catch {}
  }
  if (reScrapeQueue.length > 0) {
    console.log(`\nRe-scraping ${reScrapeQueue.length} empty post files...`);
    for (const item of reScrapeQueue) {
      try {
        let detail;
        if (item.url.includes("sarkariexam.com")) {
          const d = await scrapeSarkariExamDetail(item.url);
          detail = {
            title: item.title || "", slug: item.slug, url: item.url, category: categorizePost(item.title || "", "latestJobs"),
            publishedDate: d.publishedDate || "", intro: d.intro || "",
            importantDates: d.importantDates || [], applicationFee: d.applicationFee || [],
            importantLinks: d.importantLinks || [], fullContentHtml: "",
          };
        } else if (item.url.includes("resultbharat.com") || item.url.includes("sarkarialert.net") || item.url.includes("rojgarresult.com") || item.url.includes("naukaritime.com") || item.url.includes("freejobalert.com")) {
          const d = await scrapeGenericDetail(item.url);
          if (d) detail = { ...d, slug: sanitizeSlug(d.slug) };
        } else {
          const d = await scrapeSarkariResultDetail(item.url);
          if (d) detail = { ...d, slug: sanitizeSlug(d.slug) };
        }
        if (detail && (detail.intro || detail.importantDates?.length > 0)) {
          detail = mergeExistingFields(item.slug, detail);
          detail = generateSEOContent(detail);
          writeFileSync(POSTS_DIR + "/" + item.slug + ".json", JSON.stringify(detail, null, 2), "utf8");
          console.log(`  [RESTORED] ${item.file}`);
        }
      } catch {}
    }
  }

  // ---- Scrape post details with concurrency ----
  if (totalNew > 0) {
    console.log(`\nFetching details for ${totalNew} new items (concurrency: ${CONCURRENCY})...`);
  }
  mkdirSync(POSTS_DIR, { recursive: true });

  function generateSEOContent(detail) {
    const title = detail.title || "";
    const lower = title.toLowerCase();
    // Derive correct category from title — title always wins over source-site category
    const derivedCat = categorizePost(title, detail.category || "latestJobs");
    detail.category = derivedCat;

    // Detect content type flags (result takes priority over admit card)
    const isResult = /\b(result|scorecard|marks|merit list|cut\s*off|selection list|shortlist|qualified|selected candidates?)\b/i.test(lower);
    const isAdmit = !isResult && (lower.includes("admit card") || lower.includes("hall ticket") || lower.includes("call letter"));
    const isAnswerKey = lower.includes("answer key") || lower.includes("response sheet");
    const isJob = !isResult && !isAdmit && (lower.includes("online form") || lower.includes("apply") || lower.includes("recruitment") || lower.includes("vacancy"));

    const dates = detail.importantDates || [];
    const fees = detail.applicationFee || [];
    const links = detail.importantLinks || [];
    const intro = detail.intro || "";

    // Generate keyword-rich intro if current one is short
    if (!intro || intro.length < 150) {
      const parts = [];
      parts.push(title + ".");
      if (isResult) parts.push("Candidates who appeared in the examination can now check their result and download the scorecard from the official website.");
      if (isAdmit) parts.push("Candidates can now download their admit card / hall ticket from the official website before the exam date.");
      if (isAnswerKey) parts.push("Candidates can download the official answer key and raise objections if needed.");
      if (isJob) parts.push("Eligible candidates can apply online through the official website before the last date.");
      if (dates.length > 0) {
        const lastDate = dates.find(d => d.toLowerCase().includes("last") || d.toLowerCase().includes("apply"));
        if (lastDate) parts.push("The last date to apply is " + lastDate.replace(/^.*?:/, "").trim() + ".");
      }
      parts.push("Check important dates, application fee, eligibility criteria and official links below.");
      detail.intro = parts.join(" ");
    }

    // Generate fullContentHtml
    const htmlParts = [];
    htmlParts.push("<h2>" + title + " - Complete Details</h2>");
    htmlParts.push("<p>" + (detail.intro || intro) + "</p>");

    if (dates.length > 0) {
      htmlParts.push("<h2>Important Dates</h2><ul>");
      for (const d of dates) htmlParts.push("<li><strong>" + d.replace(/^([^:]*):\s*/, "$1:</strong> ") + "</li>");
      htmlParts.push("</ul>");
    }

    if (fees.length > 0) {
      htmlParts.push("<h2>Application Fee</h2><ul>");
      for (const f of fees) htmlParts.push("<li>" + f + "</li>");
      htmlParts.push("</ul>");
    }

    if (isResult) {
      htmlParts.push("<h2>How to Check Result</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the result / scorecard link.</li>");
      htmlParts.push("<li>Enter your application number / roll number and date of birth / password.</li>");
      htmlParts.push("<li>Click on submit to view your result.</li>");
      htmlParts.push("<li>Download and take a printout of the scorecard for future reference.</li>");
      htmlParts.push("</ol>");
    }

    if (isAdmit) {
      htmlParts.push("<h2>How to Download Admit Card</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the admit card / hall ticket link.</li>");
      htmlParts.push("<li>Enter your registration number / roll number and date of birth / password.</li>");
      htmlParts.push("<li>Click on submit to view your admit card.</li>");
      htmlParts.push("<li>Download and take a printout. Carry it to the exam center along with a photo ID.</li>");
      htmlParts.push("</ol>");
    }

    if (isAnswerKey) {
      htmlParts.push("<h2>How to Download Answer Key</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the answer key link.</li>");
      htmlParts.push("<li>Select your exam date / shift / paper code.</li>");
      htmlParts.push("<li>Download the answer key PDF.</li>");
      htmlParts.push("<li>Calculate your expected marks and raise objections if any by the specified deadline.</li>");
      htmlParts.push("</ol>");
    }

    if (isJob) {
      htmlParts.push("<h2>How to Apply Online</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the online application / registration link.</li>");
      htmlParts.push("<li>Register with your basic details like name, email, mobile number.</li>");
      htmlParts.push("<li>Fill the application form with personal, educational and address details.</li>");
      htmlParts.push("<li>Upload scanned photograph, signature and required documents.</li>");
      htmlParts.push("<li>Pay the application fee online.</li>");
      htmlParts.push("<li>Submit the form and take a printout for future reference.</li>");
      htmlParts.push("</ol>");
    }

    if (links.length > 0) {
      htmlParts.push("<h2>Important Links</h2><ul>");
      for (const l of links) {
        const label = l.label || "Link";
        const url = l.url || "#";
        htmlParts.push('<li><a href="' + url + '">' + label + "</a></li>");
      }
      htmlParts.push("</ul>");
    }

    // FAQ section
    htmlParts.push("<h2>Frequently Asked Questions (FAQ)</h2>");
    htmlParts.push("<h3>What is " + title + "?</h3>");
    htmlParts.push("<p>" + title + " is a government exam related notification. Complete details including important dates, fee, eligibility and links are provided above.</p>");
    if (dates.length > 0) {
      const last = dates.find(d => d.toLowerCase().includes("last") || d.toLowerCase().includes("apply"));
      if (last) {
        htmlParts.push("<h3>What is the last date to apply?</h3>");
        htmlParts.push("<p>The last date to apply is " + last.replace(/^.*?:/, "").trim() + ".</p>");
      }
    }
    htmlParts.push("<h3>Where can I find the official website?</h3>");
    const officialLink = links.find(l => l.label && l.label.toLowerCase().includes("official"));
    if (officialLink && officialLink.url) {
      htmlParts.push('<p>The official website is: <a href="' + officialLink.url + '">' + officialLink.url + "</a></p>");
    } else if (detail.url) {
      htmlParts.push('<p>The official website is: <a href="' + detail.url + '">' + detail.url + "</a></p>");
    } else {
      htmlParts.push("<p>Visit the official website through the Important Links section above.</p>");
    }
    htmlParts.push("<h3>How to download " + (isAdmit ? "admit card" : isResult ? "result" : isAnswerKey ? "answer key" : "notification") + "?</h3>");
    htmlParts.push("<p>Click on the relevant link in the Important Links section above or visit the official website directly.</p>");

    detail.fullContentHtml = htmlParts.join("\n");
    return detail;
  }

  function mergeExistingFields(slug, detail) {
    const now = new Date();
    const nowIso = now.toISOString();

    function isValidPastDate(val) {
      if (!val) return false;
      const d = new Date(val);
      return !isNaN(d.getTime()) && d.getTime() <= now.getTime();
    }

    try {
      const oldPath = POSTS_DIR + "/" + slug + ".json";
      if (fs.existsSync(oldPath)) {
        const old = JSON.parse(fs.readFileSync(oldPath, "utf8"));
        if (old.cutoff) detail.cutoff = old.cutoff;
        // PRESERVE ORIGINAL PUBLICATION AND CREATION DATES (rejecting any corrupted future dates)
        const oldPublishedValid = isValidPastDate(old.publishedAt) ? old.publishedAt : (isValidPastDate(old.createdAt) ? old.createdAt : null);
        const oldDateValid = isValidPastDate(old.publishedDate) ? old.publishedDate : null;

        if (oldPublishedValid || oldDateValid) {
          detail.publishedAt = oldPublishedValid || (oldDateValid ? new Date(oldDateValid).toISOString() : nowIso);
          detail.createdAt = isValidPastDate(old.createdAt) ? old.createdAt : detail.publishedAt;
          detail.publishedDate = oldDateValid || (oldPublishedValid ? new Date(oldPublishedValid).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }) : detail.publishedAt);
        } else {
          // If previous date was corrupted/future, repair it
          detail.publishedAt = (detail.publishedDate && isValidPastDate(detail.publishedDate)) ? new Date(detail.publishedDate).toISOString() : nowIso;
          detail.createdAt = detail.publishedAt;
          detail.publishedDate = (detail.publishedDate && isValidPastDate(detail.publishedDate)) ? detail.publishedDate : detail.publishedAt;
        }
        detail.updatedAt = nowIso;
        return detail;
      }
    } catch {}

    // New post: set permanent publication dates once
    if (!detail.publishedAt || !isValidPastDate(detail.publishedAt)) {
      detail.publishedAt = (detail.publishedDate && isValidPastDate(detail.publishedDate)) ? (new Date(detail.publishedDate).toISOString() || nowIso) : nowIso;
    }
    if (!detail.createdAt || !isValidPastDate(detail.createdAt)) {
      detail.createdAt = detail.publishedAt;
    }
    if (!detail.publishedDate || !isValidPastDate(detail.publishedDate)) {
      detail.publishedDate = detail.publishedAt;
    }
    return detail;
  }

  async function fetchOne(item) {
    let detail, slug;
    if (item.url.includes("sarkariexam.com")) {
      const d = await scrapeSarkariExamDetail(item.url);
      slug = sanitizeSlug(item.slug);
      detail = {
        title: item.title, slug, url: item.url, category: item.category,
        publishedDate: d.publishedDate || "", intro: d.intro || "",
        importantDates: d.importantDates || [], applicationFee: d.applicationFee || [],
        importantLinks: d.importantLinks || [], fullContentHtml: "",
      };
      item.slug = slug;
    } else if (item.url.includes("resultbharat.com") || item.url.includes("sarkarialert.net") || item.url.includes("rojgarresult.com") || item.url.includes("naukaritime.com") || item.url.includes("freejobalert.com")) {
      const d = await scrapeGenericDetail(item.url);
      if (!d) return null;
      slug = sanitizeSlug(d.slug);
      detail = { ...d, slug };
    } else {
      detail = await scrapeSarkariResultDetail(item.url);
      if (!detail) return null;
      slug = sanitizeSlug(detail.slug);
      detail.slug = slug;
    }
    detail = mergeExistingFields(slug, detail);
    detail = generateSEOContent(detail);

    // Propagate permanent publication dates to listing item
    item.publishedDate = detail.publishedDate;
    item.publishedAt = detail.publishedAt;

    if (!existing.posts) existing.posts = {};
    // Store slim listing data + permanent date lookup
    const lastDate = detail.importantDates?.find(d => d.toLowerCase().includes("last") || d.toLowerCase().includes("apply"));
    existing.posts[slug] = {
      lastDate: lastDate ? lastDate.replace(/^.*?:/, "").trim() : undefined,
      publishedDate: detail.publishedDate,
      publishedAt: detail.publishedAt,
    };
    writeFileSync(POSTS_DIR + "/" + slug + ".json", JSON.stringify(detail, null, 2), "utf8");
    newSlugs.push(slug); // collect for IndexNow submission
    return 1;
  }

  let detailCount = 0;
  if (totalNew > 0) {
    const overallTimer = setTimeout(() => {
      console.log(`\n  ⚠️  Overall detail scraping timeout (${MAX_DETAIL_TIME/1000}s) reached. Saving partial results...`);
    }, MAX_DETAIL_TIME);
    __timers.add(overallTimer);

    for (let i = 0; i < newItems.length; i += CONCURRENCY) {
      const batch = newItems.slice(i, i + CONCURRENCY);
      const results = await Promise.allSettled(batch.map(fetchOne));
      for (const r of results) {
        if (r.status === "fulfilled" && r.value) detailCount++;
      }
      const pct = Math.min(100, Math.round(((i + batch.length) / newItems.length) * 100));
      console.log(`  ${Math.min(i + CONCURRENCY, newItems.length)}/${newItems.length} (${pct}%) - ${detailCount} details so far`);
    }

    clearTimeout(overallTimer);
    __timers.delete(overallTimer);
  }

  // Clear all remaining timers
  for (const t of __timers) clearTimeout(t);
  __timers.clear();

  existing.fetchedAt = new Date().toISOString();
  saveData(existing);

  const elapsed = ((Date.now() - start) / 1000).toFixed(1);
  if (totalNew > 0) {
    console.log(`\nDone in ${elapsed}s. ${totalNew} new items, ${detailCount} details scraped.`);
  } else {
    console.log(`\nDone in ${elapsed}s. No new items. Re-scraped ${reScrapeQueue.length} empty posts.`);
  }
  console.log("Updated data/scraped-data.ts and data/posts/");

  // ── IndexNow: submit newly added URLs to search engines ──────────────────
  if (totalNew > 0 && newSlugs.length > 0) {
    try {
      const INDEXNOW_KEY = "def212d6b0d3407cb3a51212813102f4";
      const HOST = "www.aiexamresult.com";
      const newUrls = [
        `https://${HOST}/`,
        ...newSlugs.slice(0, 99).map((s) => `https://${HOST}/post/${s}`),
      ];
      const payload = {
        host: HOST,
        key: INDEXNOW_KEY,
        keyLocation: `https://${HOST}/${INDEXNOW_KEY}.txt`,
        urlList: newUrls,
      };
      const res = await fetch("https://api.indexnow.org/indexnow", {
        method: "POST",
        headers: { "Content-Type": "application/json; charset=utf-8" },
        body: JSON.stringify(payload),
      });
      if (res.ok || res.status === 202) {
        console.log(`✅ IndexNow: submitted ${newUrls.length} URLs (status ${res.status})`);
      } else {
        console.log(`⚠️  IndexNow: status ${res.status} — ${await res.text().catch(() => "")}`);
      }
    } catch (err) {
      console.log(`⚠️  IndexNow submit failed: ${err.message}`);
    }
  }
  // ─────────────────────────────────────────────────────────────────────────
}

main().catch((e) => { console.error("Error:", e.message); process.exit(1); });
