import cloudscraper from "cloudscraper";
import * as cheerio from "cheerio";
import * as https from "https";
import * as http from "http";
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_FILE = resolve(__dirname, "..", "data", "scraped-data.ts");
const POSTS_DIR = resolve(__dirname, "..", "data", "posts");
const FETCH_TIMEOUT = 20000; // 20s per request
const CONCURRENCY = 5;       // 5 parallel detail fetches
const MAX_DETAIL_TIME = 300000; // 5min overall for detail scraping

function loadData() {
  const raw = readFileSync(DATA_FILE, "utf8");
  const jsonStr = raw
    .replace(/^\/\/.*[\r\n]+/, "")
    .replace(/^export const scrapedData = /, "")
    .replace(/\s*as const\s*;\s*$/, "")
    .replace(/;\s*$/, "");
  return JSON.parse(jsonStr);
}

const __timers = new Set();

function saveData(data) {
  const ts = `// Auto-generated by sync-all - DO NOT EDIT\nexport const scrapedData = ${JSON.stringify(data, null, 2)};\n`;
  writeFileSync(DATA_FILE, ts, "utf8");
  // Also write JSON version for runtime loading (avoids Vercel bundling 100MB+)
  const jsonPath = resolve(__dirname, "..", "data", "scraped.json");
  writeFileSync(jsonPath, JSON.stringify(data, null, 2), "utf8");
}

function sanitizeSlug(s) {
  return s.replace(/[<>:"/\\|?*]+/g, "-").replace(/-+/g, "-").replace(/^-+|-+$/g, "") || "post";
}

function fetchHtmlFallback(url) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const mod = u.protocol === "https:" ? https : http;
    const req = mod.get(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
      },
      timeout: FETCH_TIMEOUT,
    }, (res) => {
      let data = "";
      res.on("data", (chunk) => { data += chunk; });
      res.on("end", () => {
        if (res.statusCode !== 200 && res.statusCode !== 404) {
          return reject(new Error(`HTTP ${res.statusCode}`));
        }
        resolve(data);
      });
    });
    req.on("error", reject);
    req.on("timeout", () => { req.destroy(); reject(new Error("Timeout")); });
  });
}

async function fetchHtml(url) {
  // First try cloudscraper
  try {
    const html = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error("Timeout")), FETCH_TIMEOUT);
      cloudscraper({ uri: url, method: "GET" })
        .then((h) => { clearTimeout(timer); resolve(h); })
        .catch((err) => { clearTimeout(timer); reject(err); });
    });
    // Only fall back if page is clearly a Cloudflare-only challenge (not real content)
    if (html.length < 500 || (html.includes("Just a moment") && !html.includes("<!DOCTYPE")) || (html.includes("_cf_chl") && !html.includes("</html>"))) {
      return fetchHtmlFallback(url);
    }
    return html;
  } catch {
    return fetchHtmlFallback(url);
  }
}

// ======== Source 1: sarkariresult.com ========

async function scrapeSarkariResult() {
  const html = await fetchHtml("https://www.sarkariresult.com/");
  const $ = cheerio.load(html);

  const viewMorePaths = [];
  $("a.gb-button").each((_, a) => {
    const $a = $(a);
    if ($a.text().trim().toLowerCase() === "view more") {
      const href = $a.attr("href") || "";
      const path = href.replace(/https?:\/\/[^/]+\//, "").replace(/\/$/, "");
      viewMorePaths.push(path);
    }
  });

  const CATEGORY_MAP = { result: "results", admitcard: "admitCards", latestjob: "latestJobs", answerkey: "answerKeys", admission: "admissions" };
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  let containerIdx = 0;
  const seen = new Set();

  $("div[class*=gb-container]").each((_, el) => {
    const $el = $(el);
    const postLinks = $el.find("a[href]").filter((_, a) => $(a).text().trim().length > 15);
    if (postLinks.length < 3) return;

    const vmPath = viewMorePaths[containerIdx] || "";
    const category = CATEGORY_MAP[vmPath] || "";
    containerIdx++;

    if (!category) return;

    postLinks.each((_, a) => {
      const $a = $(a);
      const url = $a.attr("href") || "";
      if (!url || seen.has(url)) return;
      seen.add(url);
      const title = $a.text().trim();
      const slug = url.replace(/\/$/, "").split("/").pop() || title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
      items[category].push({ title, url, category, slug });
    });
  });

  return items;
}

async function scrapeSarkariResultDetail(url) {
  try {
    const html = await fetchHtml(url);
    const $ = cheerio.load(html);

    const title = $("h1").first().text().trim() || $("title").text().trim();
    const slug = url.replace(/\/$/, "").split("/").pop().replace(/\.html?$/, "") || "post";

    let publishedDate = $("meta[property='article:published_time']").attr("content") || "";
    if (publishedDate) {
      const d = new Date(publishedDate);
      if (!isNaN(d.getTime())) {
        publishedDate = d.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
      }
    }

    let intro = "";
    $("h3, strong, b").each((_, el) => {
      const text = $(el).text().trim().toLowerCase();
      if (text.includes("short information") || text.includes("brief information")) {
        intro = $(el).parent().next("p").text().trim() || $(el).closest("div").find("p").first().text().trim();
      }
    });
    if (!intro) intro = $(".entry-content p").first().text().trim().slice(0, 300);

    const importantDates = [];
    $("table").each((_, table) => {
      const $table = $(table);
      $table.find("tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length >= 2) {
          const first = $(cells[0]).text().trim().toLowerCase();
          const second = $(cells[1]).text().trim();
          if (first && second && (first.includes("date") || first.includes("fee") || first.includes("age") || first.includes("exam") || !first.includes("link"))) {
            importantDates.push($(cells[0]).text().trim() + " : " + second);
          }
        }
      });
    });

    const importantLinks = [];
    $("table a, .entry-content a").each((_, link) => {
      const $link = $(link);
      const label = $link.text().trim();
      const href = $link.attr("href") || "";
      if (label && href && href !== "#" && !href.startsWith("javascript")) {
        importantLinks.push({ label, url: href });
      }
    });

    return { title, slug, url, publishedDate, intro, importantDates, applicationFee: [], importantLinks, fullContentHtml: "" };
  } catch {
    return null;
  }
}

// ======== Source 2: sarkariexam.com ========

const HEADING_MAP = {
  "result": "results",
  "exam result": "results",
  "new updates": "results",
  "admit card": "admitCards",
  "top online form": "latestJobs",
  "answer keys": "answerKeys",
  "answer key": "answerKeys",
  "admission form": "admissions",
  "document verification": "documents",
  "documents verification": "documents",
  "syllabus": "documents",
  "latest news": "results",
  "diploma / iti": "latestJobs",
  "b.tech / m.tech": "latestJobs",
};

function categorizeByTitle(title) {
  const lower = title.toLowerCase();
  if (lower.includes("admit card") || lower.includes("hall ticket") || lower.includes("call letter") || lower.includes("exam city") || lower.includes("exam date")) return "admitCards";
  if (lower.includes("answer key") || lower.includes("response sheet")) return "answerKeys";
  if (lower.includes("admission") || lower.includes("counselling") || lower.includes("counseling")) return "admissions";
  if (lower.includes("online form") || lower.includes("apply") || lower.includes("recruitment") || lower.includes("apprentice") || lower.includes("vacancy")) return "latestJobs";
  return null;
}

async function scrapeSarkariExam() {
  const html = await fetchHtml("https://www.sarkariexam.com/");
  const $ = cheerio.load(html);
  const items = [];
  const seen = new Set();

  $(".below-block").each((_, block) => {
    const $block = $(block);
    let heading = $block.find("h4.wp-block-heading").text().trim().toLowerCase().replace(/<\/?strong>/g, "");
    if (!heading) {
      heading = $block.find("h4").text().trim().toLowerCase().replace(/<\/?strong>/g, "");
    }
    if (!heading) return;

    const key = HEADING_MAP[heading];
    if (!key) return;

    $block.find("ul.wp-block-latest-posts__list li a.wp-block-latest-posts__post-title").each((__, link) => {
      const $link = $(link);
      const url = $link.attr("href") || "";
      if (!url || seen.has(url)) return;
      seen.add(url);
      const title = $link.text().trim();
      const slug = url.replace(/\/$/, "").split("/").pop() || "";
      const titleCat = categorizeByTitle(title);
      const finalCat = titleCat || key;
      items.push({ title, url, category: finalCat, slug });
    });
  });

  return items;
}

async function scrapeSarkariExamDetail(url) {
  try {
    const html = await fetchHtml(url);
    const $ = cheerio.load(html);

    const titleText = $("title").text().trim().toLowerCase();
    if (titleText.includes("page not found") || html.length < 1000) {
      return { publishedDate: "", intro: "", importantDates: [], applicationFee: [], importantLinks: [] };
    }

    const publishedDate = $("time.entry-date.published").attr("datetime") || "";
    const intro = $("div.post-desc p").text().trim() || $("div.entry-content p").first().text().trim() || "";

    const importantDates = [];
    const applicationFee = [];
    const $table1 = $("div.newtable1");
    if ($table1.length) {
      $table1.find("h3").each((_, h) => {
        const $h = $(h);
        if ($h.text().toLowerCase().includes("important dates")) {
          $h.closest("td.pd-0").find("ul li").each((__, li) => importantDates.push($(li).text().trim()));
        }
        if ($h.text().toLowerCase().includes("application fee")) {
          $h.closest("td.pd-0").find("ul li").each((__, li) => applicationFee.push($(li).text().trim()));
        }
      });
    }
    if (importantDates.length === 0) {
      $("table").each((_, t) => {
        $(t).find("tr").each((_, row) => {
          const cells = $(row).find("td, th");
          if (cells.length >= 2) {
            const first = $(cells[0]).text().trim().toLowerCase();
            const second = $(cells[1]).text().trim();
            if (first && second && (first.includes("date") || first.includes("last") || first.includes("exam") || first.includes("admit"))) {
              importantDates.push($(cells[0]).text().trim() + " : " + second);
            }
          }
        });
      });
    }

    const spamLabels = ["sarkari exam mobile app", "join whatsapp channel", "join telegram channel"];
    const importantLinks = [];
    const $table2 = $("div.newtable2");
    if ($table2.length) {
      $table2.find("table tbody tr").each((_, row) => {
        const $tds = $(row).find("td.tcell");
        if ($tds.length >= 2) {
          const label = $tds.eq(0).find("h4 span, h4").text().trim();
          const linkUrl = $tds.eq(1).find("a").attr("href");
          if (label && !label.toLowerCase().includes("important links")) {
            const lower = label.toLowerCase();
            if (spamLabels.some((s) => lower.includes(s))) return;
            if (linkUrl && (linkUrl.includes("sarkariexam.com") || linkUrl.includes("sarkariresult"))) return;
            importantLinks.push({ label, url: linkUrl });
          }
        }
      });
    }
    if (importantLinks.length === 0) {
      $("a[href]").each((_, a) => {
        const $a = $(a);
        const label = $a.text().trim();
        const href = $a.attr("href") || "";
        if (label && href && href !== "#" && !href.startsWith("javascript") && !href.includes("sarkariexam.com") && !href.includes("sarkariresult")) {
          importantLinks.push({ label, url: href });
        }
      });
    }
    return { publishedDate, intro, importantDates, applicationFee, importantLinks };
  } catch {
    return { publishedDate: "", intro: "", importantDates: [], applicationFee: [], importantLinks: [] };
  }
}

// ======== Source 3+: resultbharat, sarkarialert, rojgarresult ========

function categorizeByKeywords(title) {
  const lower = title.toLowerCase();
  if (lower.includes("admit card") || lower.includes("hall ticket") || lower.includes("call letter") || lower.includes("exam city") || lower.includes("exam date")) return "admitCards";
  if (lower.includes("answer key") || lower.includes("response sheet")) return "answerKeys";
  if (lower.includes("admission") || lower.includes("counselling") || lower.includes("counseling")) return "admissions";
  if (lower.includes("result") || lower.includes("cutoff") || lower.includes("merit list")) return "results";
  if (lower.includes("online form") || lower.includes("apply") || lower.includes("recruitment") || lower.includes("apprentice") || lower.includes("vacancy") || lower.includes("notification")) return "latestJobs";
  return "latestJobs";
}

async function scrapeResultBharat() {
  const html = await fetchHtml("https://www.resultbharat.com/");
  const $ = cheerio.load(html);
  const items = [];
  const seen = new Set();
  $("h3 a[href]").each((_, a) => {
    const $a = $(a);
    let href = $a.attr("href") || "";
    const text = $a.text().trim();
    if (!href || text.length < 15 || seen.has(href)) return;
    seen.add(href);
    if (!href.startsWith("http")) href = "https://www.resultbharat.com" + (href.startsWith("/") ? href : "/" + href);
    items.push({
      title: text, url: href, category: categorizeByKeywords(text),
      slug: href.replace(/\/$/, "").split("/").pop().replace(/\.html?$/, "") || "post",
    });
  });
  return items;
}

async function scrapeSarkariAlert() {
  const html = await fetchHtml("https://sarkarialert.net/");
  const $ = cheerio.load(html);
  const items = [];
  const seen = new Set();
  const spam = ["whatsapp", "telegram", "facebook", "twitter", "instagram", "youtube", "current affairs", "pm kisan"];
  $("a[href]").each((_, a) => {
    const $a = $(a);
    let href = $a.attr("href") || "";
    const text = $a.text().trim();
    if (!href || text.length < 20 || seen.has(href)) return;
    const lower = text.toLowerCase();
    if (spam.some(s => lower.includes(s))) return;
    if (href.includes("#") || href.startsWith("javascript")) return;
    seen.add(href);
    if (!href.startsWith("http")) href = "https://sarkarialert.net" + (href.startsWith("/") ? href : "/" + href);
    items.push({
      title: text, url: href, category: categorizeByKeywords(text),
      slug: href.replace(/\/$/, "").split("/").pop() || "post",
    });
  });
  // Deduplicate slug conflicts
  const slugSeen = new Set();
  return items.filter(i => { const s = i.slug; if (slugSeen.has(s)) return false; slugSeen.add(s); return true; });
}

async function scrapeRojgarResult() {
  const html = await fetchHtml("https://rojgarresult.com/");
  const $ = cheerio.load(html);
  const items = [];
  const seen = new Set();
  const spam = ["whatsapp", "telegram", "facebook", "twitter", "instagram", "youtube", "rojgar result", "privacy", "disclaimer"];
  $("h2 a[href], h3 a[href]").each((_, a) => {
    const $a = $(a);
    let href = $a.attr("href") || "";
    const text = $a.text().trim();
    if (!href || text.length < 20 || seen.has(href)) return;
    const lower = text.toLowerCase();
    if (spam.some(s => lower.includes(s))) return;
    seen.add(href);
    if (!href.startsWith("http")) href = "https://rojgarresult.com" + (href.startsWith("/") ? href : "/" + href);
    items.push({
      title: text, url: href, category: categorizeByKeywords(text),
      slug: href.replace(/\/$/, "").split("/").pop() || "post",
    });
  });
  return items;
}

async function scrapeGenericDetail(url) {
  try {
    const html = await fetchHtml(url);
    const $ = cheerio.load(html);
    const title = $("h1").first().text().trim() || $("title").text().trim();
    let publishedDate = $("meta[property='article:published_time']").attr("content") || $("time").attr("datetime") || "";
    if (publishedDate) {
      const d = new Date(publishedDate);
      if (!isNaN(d.getTime())) publishedDate = d.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
    }
    let intro = $("meta[name='description']").attr("content") || "";
    if (intro.length < 10) intro = $("article p, .entry-content p, .post-content p").first().text().trim().slice(0, 300);
    if (!intro) intro = $("p").first().text().trim().slice(0, 300);

    const importantDates = [];
    const applicationFee = [];
    $("table").each((_, table) => {
      $(table).find("tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length >= 2) {
          const first = $(cells[0]).text().trim().toLowerCase();
          const second = $(cells[1]).text().trim();
          if (first && second) {
            if (first.includes("date") || first.includes("last") || first.includes("exam") || first.includes("admit")) importantDates.push($(cells[0]).text().trim() + " : " + second);
            if (first.includes("fee") || first.includes("general") || first.includes("obc") || first.includes("sc") || first.includes("st")) applicationFee.push($(cells[0]).text().trim() + " : " + second);
          }
        }
      });
    });

    const importantLinks = [];
    $("a[href]").each((_, link) => {
      const $link = $(link);
      const label = $link.text().trim();
      const href = $link.attr("href") || "";
      if (label && href && href !== "#" && !href.startsWith("javascript") && !href.includes("facebook") && !href.includes("twitter") && !href.includes("telegram") && !href.includes("whatsapp")) {
        const lower = label.toLowerCase();
        if (lower.includes("official") || lower.includes("apply") || lower.includes("download") || lower.includes("result") || lower.includes("admit") || lower.includes("answer") || lower.includes("website") || lower.includes("notification")) {
          importantLinks.push({ label, url: href });
        }
      }
    });

    const slug = url.replace(/\/$/, "").split("/").pop().replace(/\.html?$/, "") || "post";
    return { title, slug, url, publishedDate, intro, importantDates, applicationFee, importantLinks, fullContentHtml: "" };
  } catch {
    return null;
  }
}

// ======== Main ========

async function main() {
  const start = Date.now();
  console.log("Loading existing data...");
  const existing = loadData();
  const existingUrls = new Set();

  for (const key of ["results", "admitCards", "latestJobs", "answerKeys", "documents", "admissions"]) {
    for (const item of (existing[key] || [])) {
      if (item.url) existingUrls.add(item.url.replace(/\/$/, ""));
    }
  }

  let totalNew = 0;
  const newItems = [];

  // ---- Source 1: sarkariresult.com ----
  console.log("\n[1/6] Fetching sarkariresult.com...");
  try {
    const srData = await scrapeSarkariResult();
    let newSr = 0;
    for (const cat of ["results", "admitCards", "latestJobs", "answerKeys", "documents", "admissions"]) {
      const freshItems = srData[cat] || [];
      const existingItems = existing[cat] || [];
      for (const item of freshItems) {
        const url = item.url.replace(/\/$/, "");
        if (!existingUrls.has(url)) {
          existingItems.push(item);
          existingUrls.add(url);
          newItems.push(item);
          newSr++;
          totalNew++;
        }
      }
    }
    console.log(`  ${newSr} new items found`);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 2: sarkariexam.com ----
  console.log("\n[2/6] Fetching sarkariexam.com...");
  try {
    const seItems = await scrapeSarkariExam();
    let newSe = 0;
    for (const item of seItems) {
      const url = item.url.replace(/\/$/, "");
      if (!existingUrls.has(url)) {
        const cat = item.category;
        if (existing[cat]) {
          existing[cat].push(item);
        }
        existingUrls.add(url);
        newItems.push(item);
        newSe++;
        totalNew++;
      }
    }
    console.log(`  ${newSe} new items found`);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 3: resultbharat.com ----
  console.log("\n[3/6] Fetching resultbharat.com...");
  try {
    const rbItems = await scrapeResultBharat();
    let newRb = 0;
    for (const item of rbItems) {
      const url = item.url.replace(/\/$/, "");
      if (!existingUrls.has(url)) {
        const cat = item.category;
        if (existing[cat]) existing[cat].push(item);
        existingUrls.add(url);
        newItems.push(item);
        newRb++;
        totalNew++;
      }
    }
    console.log(`  ${newRb} new items found`);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 4: sarkarialert.net ----
  console.log("\n[4/6] Fetching sarkarialert.net...");
  try {
    const saItems = await scrapeSarkariAlert();
    let newSa = 0;
    for (const item of saItems) {
      const url = item.url.replace(/\/$/, "");
      if (!existingUrls.has(url)) {
        const cat = item.category;
        if (existing[cat]) existing[cat].push(item);
        existingUrls.add(url);
        newItems.push(item);
        newSa++;
        totalNew++;
      }
    }
    console.log(`  ${newSa} new items found`);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Source 5: rojgarresult.com ----
  console.log("\n[5/6] Fetching rojgarresult.com...");
  try {
    const rrItems = await scrapeRojgarResult();
    let newRr = 0;
    for (const item of rrItems) {
      const url = item.url.replace(/\/$/, "");
      if (!existingUrls.has(url)) {
        const cat = item.category;
        if (existing[cat]) existing[cat].push(item);
        existingUrls.add(url);
        newItems.push(item);
        newRr++;
        totalNew++;
      }
    }
    console.log(`  ${newRr} new items found`);
  } catch (e) {
    console.log("  Error:", e.message);
  }

  // ---- Re-scrape existing empty post files ----
  const existingFiles = readdirSync(POSTS_DIR).filter(f => f.endsWith(".json"));
  const reScrapeQueue = [];
  for (const file of existingFiles) {
    try {
      const p = JSON.parse(fs.readFileSync(POSTS_DIR + "/" + file, "utf8"));
      const empty = (!p.intro || p.intro.length < 5) && (!p.fullContentHtml || p.fullContentHtml.length < 20) && p.url;
      if (empty && p.url && !p.url.includes("tinyurl") && !p.url.includes("pdf")) {
        // Only re-scrape known source URLs
        if (p.url.includes("sarkariresult.com") || p.url.includes("sarkariexam.com") || p.url.includes("resultbharat.com") || p.url.includes("sarkarialert.net") || p.url.includes("rojgarresult.com")) {
          reScrapeQueue.push({ file, url: p.url, slug: p.slug || file.replace(".json", ""), title: p.title || "" });
        }
      }
    } catch {}
  }
  if (reScrapeQueue.length > 0) {
    console.log(`\nRe-scraping ${reScrapeQueue.length} empty post files...`);
    for (const item of reScrapeQueue) {
      try {
        let detail;
        if (item.url.includes("sarkariexam.com")) {
          const d = await scrapeSarkariExamDetail(item.url);
          detail = {
            title: item.title || "", slug: item.slug, url: item.url, category: "",
            publishedDate: d.publishedDate || "", intro: d.intro || "",
            importantDates: d.importantDates || [], applicationFee: d.applicationFee || [],
            importantLinks: d.importantLinks || [], fullContentHtml: "",
          };
        } else if (item.url.includes("resultbharat.com") || item.url.includes("sarkarialert.net") || item.url.includes("rojgarresult.com")) {
          const d = await scrapeGenericDetail(item.url);
          if (d) detail = { ...d, slug: sanitizeSlug(d.slug) };
        } else {
          const d = await scrapeSarkariResultDetail(item.url);
          if (d) detail = { ...d, slug: sanitizeSlug(d.slug) };
        }
        if (detail && (detail.intro || detail.importantDates?.length > 0)) {
          detail = mergeExistingFields(item.slug, detail);
          detail = generateSEOContent(detail);
          writeFileSync(POSTS_DIR + "/" + item.slug + ".json", JSON.stringify(detail, null, 2), "utf8");
          console.log(`  [RESTORED] ${item.file}`);
        }
      } catch {}
    }
  }

  // ---- Scrape post details with concurrency ----
  if (totalNew > 0) {
    console.log(`\nFetching details for ${totalNew} new items (concurrency: ${CONCURRENCY})...`);
  }
  mkdirSync(POSTS_DIR, { recursive: true });

  function generateSEOContent(detail) {
    const title = detail.title || "";
    const lower = title.toLowerCase();
    const isResult = lower.includes("result");
    const isAdmit = lower.includes("admit card") || lower.includes("hall ticket") || lower.includes("exam city");
    const isAnswerKey = lower.includes("answer key") || lower.includes("response sheet");
    const isJob = lower.includes("online form") || lower.includes("apply") || lower.includes("recruitment") || lower.includes("vacancy");

    const dates = detail.importantDates || [];
    const fees = detail.applicationFee || [];
    const links = detail.importantLinks || [];
    const intro = detail.intro || "";

    // Generate keyword-rich intro if current one is short
    if (!intro || intro.length < 150) {
      const parts = [];
      parts.push(title + ".");
      if (isResult) parts.push("Candidates who appeared in the examination can now check their result and download the scorecard from the official website.");
      if (isAdmit) parts.push("Candidates can now download their admit card / hall ticket from the official website before the exam date.");
      if (isAnswerKey) parts.push("Candidates can download the official answer key and raise objections if needed.");
      if (isJob) parts.push("Eligible candidates can apply online through the official website before the last date.");
      if (dates.length > 0) {
        const lastDate = dates.find(d => d.toLowerCase().includes("last") || d.toLowerCase().includes("apply"));
        if (lastDate) parts.push("The last date to apply is " + lastDate.replace(/^.*?:/, "").trim() + ".");
      }
      parts.push("Check important dates, application fee, eligibility criteria and official links below.");
      detail.intro = parts.join(" ");
    }

    // Generate fullContentHtml
    const htmlParts = [];
    htmlParts.push("<h2>" + title + " - Complete Details</h2>");
    htmlParts.push("<p>" + (detail.intro || intro) + "</p>");

    if (dates.length > 0) {
      htmlParts.push("<h2>Important Dates</h2><ul>");
      for (const d of dates) htmlParts.push("<li><strong>" + d.replace(/^([^:]*):\s*/, "$1:</strong> ") + "</li>");
      htmlParts.push("</ul>");
    }

    if (fees.length > 0) {
      htmlParts.push("<h2>Application Fee</h2><ul>");
      for (const f of fees) htmlParts.push("<li>" + f + "</li>");
      htmlParts.push("</ul>");
    }

    if (isResult) {
      htmlParts.push("<h2>How to Check Result</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the result / scorecard link.</li>");
      htmlParts.push("<li>Enter your application number / roll number and date of birth / password.</li>");
      htmlParts.push("<li>Click on submit to view your result.</li>");
      htmlParts.push("<li>Download and take a printout of the scorecard for future reference.</li>");
      htmlParts.push("</ol>");
    }

    if (isAdmit) {
      htmlParts.push("<h2>How to Download Admit Card</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the admit card / hall ticket link.</li>");
      htmlParts.push("<li>Enter your registration number / roll number and date of birth / password.</li>");
      htmlParts.push("<li>Click on submit to view your admit card.</li>");
      htmlParts.push("<li>Download and take a printout. Carry it to the exam center along with a photo ID.</li>");
      htmlParts.push("</ol>");
    }

    if (isAnswerKey) {
      htmlParts.push("<h2>How to Download Answer Key</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the answer key link.</li>");
      htmlParts.push("<li>Select your exam date / shift / paper code.</li>");
      htmlParts.push("<li>Download the answer key PDF.</li>");
      htmlParts.push("<li>Calculate your expected marks and raise objections if any by the specified deadline.</li>");
      htmlParts.push("</ol>");
    }

    if (isJob) {
      htmlParts.push("<h2>How to Apply Online</h2><ol>");
      htmlParts.push("<li>Visit the official website.</li>");
      htmlParts.push("<li>Click on the online application / registration link.</li>");
      htmlParts.push("<li>Register with your basic details like name, email, mobile number.</li>");
      htmlParts.push("<li>Fill the application form with personal, educational and address details.</li>");
      htmlParts.push("<li>Upload scanned photograph, signature and required documents.</li>");
      htmlParts.push("<li>Pay the application fee online.</li>");
      htmlParts.push("<li>Submit the form and take a printout for future reference.</li>");
      htmlParts.push("</ol>");
    }

    if (links.length > 0) {
      htmlParts.push("<h2>Important Links</h2><ul>");
      for (const l of links) {
        const label = l.label || "Link";
        const url = l.url || "#";
        htmlParts.push('<li><a href="' + url + '">' + label + "</a></li>");
      }
      htmlParts.push("</ul>");
    }

    // FAQ section
    htmlParts.push("<h2>Frequently Asked Questions (FAQ)</h2>");
    htmlParts.push("<h3>What is " + title + "?</h3>");
    htmlParts.push("<p>" + title + " is a government exam related notification. Complete details including important dates, fee, eligibility and links are provided above.</p>");
    if (dates.length > 0) {
      const last = dates.find(d => d.toLowerCase().includes("last") || d.toLowerCase().includes("apply"));
      if (last) {
        htmlParts.push("<h3>What is the last date to apply?</h3>");
        htmlParts.push("<p>The last date to apply is " + last.replace(/^.*?:/, "").trim() + ".</p>");
      }
    }
    htmlParts.push("<h3>Where can I find the official website?</h3>");
    const officialLink = links.find(l => l.label && l.label.toLowerCase().includes("official"));
    if (officialLink && officialLink.url) {
      htmlParts.push('<p>The official website is: <a href="' + officialLink.url + '">' + officialLink.url + "</a></p>");
    } else if (detail.url) {
      htmlParts.push('<p>The official website is: <a href="' + detail.url + '">' + detail.url + "</a></p>");
    } else {
      htmlParts.push("<p>Visit the official website through the Important Links section above.</p>");
    }
    htmlParts.push("<h3>How to download " + (isAdmit ? "admit card" : isResult ? "result" : isAnswerKey ? "answer key" : "notification") + "?</h3>");
    htmlParts.push("<p>Click on the relevant link in the Important Links section above or visit the official website directly.</p>");

    detail.fullContentHtml = htmlParts.join("\n");
    return detail;
  }

  function mergeExistingFields(slug, detail) {
    try {
      const oldPath = POSTS_DIR + "/" + slug + ".json";
      if (fs.existsSync(oldPath)) {
        const old = JSON.parse(fs.readFileSync(oldPath, "utf8"));
        if (old.cutoff) detail.cutoff = old.cutoff;
        // PRESERVE ORIGINAL PUBLICATION AND CREATION DATES
        const originalDate = old.publishedAt || old.createdAt || old.publishedDate;
        if (originalDate) {
          detail.publishedAt = old.publishedAt || originalDate;
          detail.createdAt = old.createdAt || detail.publishedAt;
          detail.publishedDate = old.publishedDate || detail.publishedAt;
        }
        detail.updatedAt = new Date().toISOString();
        return detail;
      }
    } catch {}
    // New post: set permanent publication dates once
    const nowIso = new Date().toISOString();
    if (!detail.publishedAt) {
      detail.publishedAt = detail.publishedDate ? (new Date(detail.publishedDate).toISOString() || nowIso) : nowIso;
    }
    if (!detail.createdAt) {
      detail.createdAt = detail.publishedAt;
    }
    if (!detail.publishedDate) {
      detail.publishedDate = detail.publishedAt;
    }
    return detail;
  }

  async function fetchOne(item) {
    let detail, slug;
    if (item.url.includes("sarkariexam.com")) {
      const d = await scrapeSarkariExamDetail(item.url);
      slug = sanitizeSlug(item.slug);
      detail = {
        title: item.title, slug, url: item.url, category: item.category,
        publishedDate: d.publishedDate || "", intro: d.intro || "",
        importantDates: d.importantDates || [], applicationFee: d.applicationFee || [],
        importantLinks: d.importantLinks || [], fullContentHtml: "",
      };
      item.slug = slug;
    } else if (item.url.includes("resultbharat.com") || item.url.includes("sarkarialert.net") || item.url.includes("rojgarresult.com")) {
      const d = await scrapeGenericDetail(item.url);
      if (!d) return null;
      slug = sanitizeSlug(d.slug);
      detail = { ...d, slug };
    } else {
      detail = await scrapeSarkariResultDetail(item.url);
      if (!detail) return null;
      slug = sanitizeSlug(detail.slug);
      detail.slug = slug;
    }
    detail = mergeExistingFields(slug, detail);
    detail = generateSEOContent(detail);

    // Propagate permanent publication dates to listing item
    item.publishedDate = detail.publishedDate;
    item.publishedAt = detail.publishedAt;

    if (!existing.posts) existing.posts = {};
    // Store slim listing data + permanent date lookup
    const lastDate = detail.importantDates?.find(d => d.toLowerCase().includes("last") || d.toLowerCase().includes("apply"));
    existing.posts[slug] = {
      lastDate: lastDate ? lastDate.replace(/^.*?:/, "").trim() : undefined,
      publishedDate: detail.publishedDate,
      publishedAt: detail.publishedAt,
    };
    writeFileSync(POSTS_DIR + "/" + slug + ".json", JSON.stringify(detail, null, 2), "utf8");
    return 1;
  }

  let detailCount = 0;
  if (totalNew > 0) {
    const overallTimer = setTimeout(() => {
      console.log(`\n  ⚠️  Overall detail scraping timeout (${MAX_DETAIL_TIME/1000}s) reached. Saving partial results...`);
    }, MAX_DETAIL_TIME);
    __timers.add(overallTimer);

    for (let i = 0; i < newItems.length; i += CONCURRENCY) {
      const batch = newItems.slice(i, i + CONCURRENCY);
      const results = await Promise.allSettled(batch.map(fetchOne));
      for (const r of results) {
        if (r.status === "fulfilled" && r.value) detailCount++;
      }
      const pct = Math.min(100, Math.round(((i + batch.length) / newItems.length) * 100));
      console.log(`  ${Math.min(i + CONCURRENCY, newItems.length)}/${newItems.length} (${pct}%) - ${detailCount} details so far`);
    }

    clearTimeout(overallTimer);
    __timers.delete(overallTimer);
  }

  // Clear all remaining timers
  for (const t of __timers) clearTimeout(t);
  __timers.clear();

  existing.fetchedAt = new Date().toISOString();
  saveData(existing);

  const elapsed = ((Date.now() - start) / 1000).toFixed(1);
  if (totalNew > 0) {
    console.log(`\nDone in ${elapsed}s. ${totalNew} new items, ${detailCount} details scraped.`);
  } else {
    console.log(`\nDone in ${elapsed}s. No new items. Re-scraped ${reScrapeQueue.length} empty posts.`);
  }
  console.log("Updated data/scraped-data.ts and data/posts/");
}

main().catch((e) => { console.error("Error:", e.message); process.exit(1); });
