/**
 * sync-all.mjs — AI Exam Result Data Sync
 * Source: sarkariexam.com only
 * Content: Rewritten in AIExamResult.com style — zero competitor traces
 */
import cloudscraper from "cloudscraper";
import * as cheerio from "cheerio";
import * as https from "https";
import * as http from "http";
import * as fs from "fs";
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_FILE  = resolve(__dirname, "..", "data", "scraped-data.ts");
const JSON_FILE  = resolve(__dirname, "..", "data", "scraped.json");
const POSTS_DIR  = resolve(__dirname, "..", "data", "posts");
const SOURCE_HOME = "https://www.sarkariexam.com/";
const SOURCE_HOST = "www.sarkariexam.com";
const FETCH_TIMEOUT   = 20000;
const CONCURRENCY     = 4;
const MAX_DETAIL_TIME = 300000; // 5 min
const SITE_HOST = "www.aiexamresult.com";
const SITE_NAME = "All India Exam Result";
const SITE_URL  = `https://${SITE_HOST}`;
const INDEXNOW_KEY = "def212d6b0d3407cb3a51212813102f4";

const CATEGORIES = ["results", "admitCards", "latestJobs", "answerKeys", "documents", "admissions"];

// ── Heading → category map from sarkariexam.com homepage ─────────────────────
const HEADING_MAP = {
  "result":                 "results",
  "exam result":            "results",
  "new updates":            "results",
  "admit card":             "admitCards",
  "top online form":        "latestJobs",
  "answer keys":            "answerKeys",
  "answer key":             "answerKeys",
  "admission form":         "admissions",
  "document verification":  "documents",
  "documents verification": "documents",
  "syllabus":               "documents",
  "latest news":            "results",
  "diploma / iti":          "latestJobs",
  "b.tech / m.tech":        "latestJobs",
};

// ── Data load / save ──────────────────────────────────────────────────────────
function loadData() {
  if (!existsSync(DATA_FILE)) return emptyData();
  const raw = readFileSync(DATA_FILE, "utf8");
  const jsonStr = raw
    .replace(/^\/\/.*[\r\n]+/gm, "")
    .replace(/^export const scrapedData = /, "")
    .replace(/\s*as const\s*;\s*$/, "")
    .replace(/;\s*$/, "");
  return JSON.parse(jsonStr);
}

function emptyData() {
  return { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [], posts: {}, fetchedAt: "" };
}

function saveData(data) {
  data.fetchedAt = new Date().toISOString();
  const json = JSON.stringify(data, null, 2);
  writeFileSync(DATA_FILE, `// Auto-generated by sync-all - DO NOT EDIT\nexport const scrapedData = ${json};\n`, "utf8");
  writeFileSync(JSON_FILE, json, "utf8");
}

// ── Slug helpers ──────────────────────────────────────────────────────────────
function sanitizeSlug(s) {
  return (s || "post")
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "post";
}

function slugFromUrl(url) {
  try {
    const raw = new URL(url).pathname.replace(/\/$/, "").split("/").pop().replace(/\.html?$/i, "");
    if (!raw || raw.length < 6 || /^[a-z0-9]{4,8}$/i.test(raw)) return "";
    return raw.toLowerCase();
  } catch { return ""; }
}

function generateSlug(url, title) {
  return slugFromUrl(url) || sanitizeSlug(title) || "post";
}

// ── Text cleaning — removes all competitor/source traces ─────────────────────
const SOURCE_PATTERNS = [
  /sarkari\s*exam(?:\.com)?/gi,
  /sarkari\s*result(?:\.com)?/gi,
  /freejobalert(?:\.com)?/gi,
  /naukari\s*time(?:\.com)?/gi,
  /result\s*bharat(?:\.com)?/gi,
  /sarkari\s*alert(?:\.net)?/gi,
  /rojgar\s*result(?:\.com)?/gi,
  /Author\s*:\s*Sarkari\s*(Exam|Result)\s*Team/gi,
  /Tag\s*:\s*[^\n\r<]+/gi,
  /Join\s+(?:our\s+)?(?:WhatsApp|Telegram)\s+(?:Channel|Group)/gi,
  /Download\s+(?:Our\s+)?(?:Mobile\s+App|App)/gi,
  /(?:www\.)?joinindiannavy\.gov\.in\s*[-–]\s*(?:Official\s+)?(?:Website|Site)/gi,
];

function cleanText(text) {
  if (!text) return "";
  let t = text;
  for (const pat of SOURCE_PATTERNS) t = t.replace(pat, SITE_NAME);
  // Remove doubled spaces, trailing dots from replacements
  return t.replace(/\s{2,}/g, " ").replace(/\s([,;.])/g, "$1").trim();
}

// De-duplicate doubled text (sarkariexam often doubles link labels)
function dedup(label) {
  if (!label) return "";
  const clean = label.trim();
  const half  = Math.floor(clean.length / 2);
  if (clean.length > 4 && clean.slice(0, half) === clean.slice(half)) return clean.slice(0, half).trim();
  return clean;
}

// Blocked domains — any link pointing here is dropped
const BLOCKED_DOMAINS = [
  SOURCE_HOST, "sarkariresult.com", "freejobalert.com", "naukaritime.com",
  "resultbharat.com", "sarkarialert.net", "rojgarresult.com",
  "facebook.com", "instagram.com", "twitter.com", "x.com", "youtube.com",
  "t.me", "whatsapp.com", "play.google.com", "testbook.com",
];
const BLOCKED_LABEL_WORDS = [
  "whatsapp", "telegram", "instagram", "mobile app", "join channel",
  "download app", "sarkari exam", "sarkari result", "freejobalert",
  "naukaritime", "result bharat",
];

function isBlockedLink(url, label) {
  if (!url || url === "#" || url.startsWith("javascript")) return true;
  const lu = url.toLowerCase();
  const ll = (label || "").toLowerCase();
  if (BLOCKED_DOMAINS.some(d => lu.includes(d))) return true;
  if (BLOCKED_LABEL_WORDS.some(w => ll.includes(w))) return true;
  return false;
}

function isJunk(title, url) {
  if (!title || !url) return true;
  const t = title.toLowerCase();
  const u = url.toLowerCase();
  if (u.endsWith(".pdf") || u.endsWith(".zip") || u.endsWith(".doc")) return true;
  if (t.includes("privacy policy") || t.includes("disclaimer") || t.includes("terms and condition") || t.includes("contact us") || t.includes("about us")) return true;
  if (t.includes("get started for free") || t.includes("sarkari result shine")) return true;
  return false;
}

// ── Category detection — RESULT always beats ADMIT CARD ──────────────────────
function categorize(title, fallback = "latestJobs") {
  const t = (title || "").toLowerCase();
  if (/\b(result|scorecard|marks|merit list|cut\s*off|selection list|shortlist|allotment result|qualified|selected candidates?)\b/i.test(t)) return "results";
  if (/\b(answer key|response sheet|objection|omr sheet|model answer)\b/i.test(t)) return "answerKeys";
  if (/\b(admit card|hall ticket|call letter|pravesh patra)\b/i.test(t)) return "admitCards";
  if (/\b(interview schedule|interview letter|interview date|interview list)\b/i.test(t)) return "results";
  if (/\b(admission|counselling|counseling|seat allotment|entrance test|entrance exam|deled|b\.ed entrance)\b/i.test(t)) return "admissions";
  if (/\b(exam date|exam schedule|new exam date|revised exam date|time table|dv schedule|document verification|syllabus|pattern|certificate|application status|rejected list|exam city)\b/i.test(t)) return "documents";
  if (/\b(online form|apply online|recruitment|vacancy|vacancies|apprentice|bharti|posts?|officer|assistant|constable|teacher)\b/i.test(t)) return "latestJobs";
  return fallback;
}

// ── HTTP fetch with cloudscraper + fallback ───────────────────────────────────
function fetchHtmlFallback(url) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const mod = u.protocol === "https:" ? https : http;
    const req = mod.get(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
        Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
      },
      timeout: FETCH_TIMEOUT,
    }, (res) => {
      let data = "";
      res.on("data", (chunk) => { data += chunk; });
      res.on("end", () => { resolve(data); });
    });
    req.on("error", reject);
    req.on("timeout", () => { req.destroy(); reject(new Error("Timeout")); });
  });
}

async function fetchHtml(url) {
  try {
    const html = await new Promise((resolve, reject) => {
      const t = setTimeout(() => reject(new Error("Timeout")), FETCH_TIMEOUT);
      cloudscraper({ uri: url, method: "GET" })
        .then(h => { clearTimeout(t); resolve(h); })
        .catch(e => { clearTimeout(t); reject(e); });
    });
    if (html.length < 500 || (html.includes("Just a moment") && !html.includes("<!DOCTYPE"))) {
      return fetchHtmlFallback(url);
    }
    return html;
  } catch {
    return fetchHtmlFallback(url);
  }
}

// ── Scrape homepage listings ──────────────────────────────────────────────────
async function scrapeListings() {
  const html  = await fetchHtml(SOURCE_HOME);
  const $     = cheerio.load(html);
  const items = { results: [], admitCards: [], latestJobs: [], answerKeys: [], documents: [], admissions: [] };
  const seen  = new Set();

  $(".below-block").each((_, block) => {
    const $block  = $(block);
    let heading   = $block.find("h4.wp-block-heading, h4").first().text().trim().toLowerCase().replace(/<\/?strong>/g, "");
    if (!heading) return;
    const fallback = HEADING_MAP[heading];
    if (!fallback || !items[fallback]) return;

    $block.find("ul.wp-block-latest-posts__list li a.wp-block-latest-posts__post-title, a[href]").each((__, link) => {
      const href     = $(link).attr("href") || "";
      const rawTitle = $(link).text().trim();
      if (!href || !rawTitle || rawTitle.length < 12 || seen.has(href)) return;
      if (href.includes(SOURCE_HOST) === false && !href.includes(SOURCE_HOST)) {
        // Only accept links from sarkariexam.com
        try { if (new URL(href).hostname !== SOURCE_HOST) return; } catch { return; }
      }
      seen.add(href);
      const title = cleanText(rawTitle);
      if (isJunk(title, href)) return;
      const cat  = categorize(title, fallback);
      const slug = generateSlug(href, title);
      if (items[cat]) items[cat].push({ title, sourceUrl: href, slug, category: cat });
    });
  });

  return items;
}

// ── Scrape individual post detail ─────────────────────────────────────────────
async function scrapeDetail(sourceUrl, title, category) {
  try {
    const html = await fetchHtml(sourceUrl);
    const $    = cheerio.load(html);

    if ($("title").text().toLowerCase().includes("page not found") || html.length < 1000) {
      return null;
    }

    // ── Published date ──
    let publishedDate = $("time.entry-date.published").attr("datetime") || "";
    if (publishedDate) {
      const d = new Date(publishedDate);
      if (isNaN(d.getTime()) || d > new Date()) publishedDate = "";
    }

    // ── Short intro (raw from source, we will rewrite below) ──
    let rawIntro = $("div.post-desc p").text().trim() || $("div.entry-content p").first().text().trim() || "";
    rawIntro = cleanText(rawIntro);

    // ── Important Dates ──
    const importantDates = [];
    const applicationFee = [];

    $("div.newtable1 h3").each((_, h) => {
      const sectionLabel = $(h).text().trim().toLowerCase();
      const $tbl = $(h).next("table");
      if (!$tbl.length) return;
      $tbl.find("tr").each((__, row) => {
        const cells = $(row).find("td");
        if (cells.length < 2) return;
        const col0 = dedup(cells.eq(0).text().trim());
        const col1 = dedup(cells.eq(1).text().trim());
        if (!col0 || !col1 || col0.length > 70 || col1.length > 70) return;
        if (/qualification|post name|click here|download/i.test(col0 + col1)) return;
        const entry = `${col0} : ${col1}`;
        if (sectionLabel.includes("fee")) applicationFee.push(entry);
        else importantDates.push(entry);
      });
    });

    // Fallback: scan all tables
    if (importantDates.length === 0) {
      $("table tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length < 2) return;
        const col0 = dedup($(cells[0]).text().trim());
        const col1 = dedup($(cells[1]).text().trim());
        if (!col0 || !col1 || col0.length > 70 || col1.length > 70) return;
        const lo = col0.toLowerCase();
        if (lo.includes("date") || lo.includes("last") || lo.includes("exam") || lo.includes("admit")) {
          importantDates.push(`${col0} : ${col1}`);
        }
      });
    }

    // ── Important Links — only external official links ──
    const importantLinks = [];
    const seenUrls = new Set();

    $("div.newtable2 table tbody tr").each((_, row) => {
      const $tds = $(row).find("td.tcell");
      if ($tds.length < 2) return;
      const labelBase = dedup($tds.eq(0).find("h4 span, h4").text().trim() || $tds.eq(0).text().trim());
      $tds.eq(1).find("a[href]").each((__, a) => {
        const href  = $(a).attr("href") || "";
        const aText = dedup($(a).text().trim());
        if (!href || href === "#" || href.startsWith("javascript") || seenUrls.has(href)) return;
        if (isBlockedLink(href, labelBase)) return;
        let label = labelBase || aText;
        if (aText && !aText.toLowerCase().includes("click here") && aText.toLowerCase() !== label.toLowerCase()) {
          label = labelBase ? `${labelBase} (${aText})` : aText;
        }
        label = cleanText(dedup(label));
        if (!label || label.length < 3) return;
        seenUrls.add(href);
        importantLinks.push({ label, url: href });
      });
    });

    // Fallback: scan all table links
    if (importantLinks.length === 0) {
      $("table tr").each((_, row) => {
        const cells = $(row).find("td, th");
        if (cells.length < 2) return;
        const labelBase = dedup($(cells[0]).text().trim());
        $(cells[1]).find("a[href]").each((__, a) => {
          const href  = $(a).attr("href") || "";
          const aText = dedup($(a).text().trim());
          if (!href || seenUrls.has(href) || isBlockedLink(href, labelBase)) return;
          let label = labelBase || aText;
          if (aText && !aText.toLowerCase().includes("click here") && aText.toLowerCase() !== label.toLowerCase()) {
            label = labelBase ? `${labelBase} (${aText})` : aText;
          }
          label = cleanText(dedup(label));
          if (!label || label.length < 3) return;
          seenUrls.add(href);
          importantLinks.push({ label, url: href });
        });
      });
    }

    return {
      publishedDate,
      rawIntro,
      importantDates: [...new Set(importantDates.map(x => cleanText(x)).filter(Boolean))],
      applicationFee: [...new Set(applicationFee.map(x => cleanText(x)).filter(Boolean))],
      importantLinks: importantLinks.slice(0, 15),
    };
  } catch {
    return null;
  }
}

// ── Generate content in AIExamResult.com style ────────────────────────────────
// Content is FRESHLY WRITTEN — no source site traces at all
function buildPostContent(title, category, detail) {
  const { rawIntro, importantDates = [], applicationFee = [], importantLinks = [] } = detail;
  const cat = category || categorize(title);

  const isResult    = cat === "results";
  const isAdmit     = cat === "admitCards";
  const isAnswerKey = cat === "answerKeys";
  const isAdmission = cat === "admissions";
  const isDocument  = cat === "documents";
  // isJob = everything else

  // ── Build original intro in AIExamResult style ──
  let intro = "";
  if (rawIntro && rawIntro.length > 50) {
    // Rewrite: remove short-info framing, keep substance
    intro = rawIntro
      .replace(/^Short\s+Information\s*[:–-]?\s*/i, "")
      .replace(/^Brief\s+Information\s*[:–-]?\s*/i, "")
      .trim();
  }
  // If intro is still short, generate one from context
  if (!intro || intro.length < 80) {
    const parts = [`${title}.`];
    if (isResult)    parts.push("Candidates who appeared in the examination can check their result and download the scorecard from the direct link provided below.");
    if (isAdmit)     parts.push("Candidates can download their Admit Card / Hall Ticket from the official website. Carry it to the examination center along with a valid government photo ID.");
    if (isAnswerKey) parts.push("The official Answer Key has been released. Candidates can download it and raise objections within the stipulated time.");
    if (isAdmission) parts.push("Candidates can check admission status, seat allotment and complete counselling schedule from the links below.");
    if (isDocument)  parts.push("Candidates can check complete details including exam schedule, syllabus, and other important information from the links below.");
    if (!isResult && !isAdmit && !isAnswerKey && !isAdmission && !isDocument) {
      parts.push("Eligible candidates can apply online through the official website before the last date. Check complete details including eligibility, fee, and important dates below.");
    }
    if (importantDates.length > 0) {
      const last = importantDates.find(d => /last|apply/i.test(d));
      if (last) parts.push(`Important: ${last.replace(/^[^:]+:\s*/, "").trim()} is the last date.`);
    }
    intro = parts.join(" ");
  }

  // ── Build fullContentHtml ──
  const html = [];

  // H2 heading in AIExamResult style
  html.push(`<h2>${title} – Full Details</h2>`);
  html.push(`<p>${intro}</p>`);

  // Important Dates table-style list
  if (importantDates.length > 0) {
    html.push(`<h2>Important Dates</h2><ul>`);
    for (const d of importantDates) html.push(`<li><strong>${d.replace(/^([^:]+):\s*/, "$1:</strong> ")}</li>`);
    html.push(`</ul>`);
  }

  // Application Fee
  if (applicationFee.length > 0) {
    html.push(`<h2>Application Fee</h2><ul>`);
    for (const f of applicationFee) html.push(`<li>${f}</li>`);
    html.push(`</ul>`);
  }

  // How-to section — completely original, no source reference
  if (isResult) {
    html.push(`<h2>How to Check ${title}</h2><ol>`);
    html.push(`<li>Visit the official website link provided below.</li>`);
    html.push(`<li>Click on the Result / Scorecard link.</li>`);
    html.push(`<li>Enter your Application Number / Roll Number and Date of Birth.</li>`);
    html.push(`<li>Submit to view your result on screen.</li>`);
    html.push(`<li>Download and save the scorecard for future reference.</li>`);
    html.push(`</ol>`);
  } else if (isAdmit) {
    html.push(`<h2>How to Download Admit Card</h2><ol>`);
    html.push(`<li>Open the official website from the link given below.</li>`);
    html.push(`<li>Click on the Admit Card / Hall Ticket download link.</li>`);
    html.push(`<li>Enter your Registration Number / Roll Number and Date of Birth.</li>`);
    html.push(`<li>Submit to view your Admit Card.</li>`);
    html.push(`<li>Download the PDF and take a printout. Carry it with a valid Photo ID to the exam centre.</li>`);
    html.push(`</ol>`);
  } else if (isAnswerKey) {
    html.push(`<h2>How to Download Answer Key</h2><ol>`);
    html.push(`<li>Go to the official website using the link below.</li>`);
    html.push(`<li>Click on the Answer Key / Response Sheet link.</li>`);
    html.push(`<li>Select your Exam Date / Shift / Paper Code if applicable.</li>`);
    html.push(`<li>Download the PDF answer key.</li>`);
    html.push(`<li>Match your responses and submit objections if any within the deadline.</li>`);
    html.push(`</ol>`);
  } else if (isAdmission) {
    html.push(`<h2>How to Apply for Admission / Counselling</h2><ol>`);
    html.push(`<li>Visit the official portal using the direct link below.</li>`);
    html.push(`<li>Register / Login with your credentials.</li>`);
    html.push(`<li>Fill in your personal and academic details.</li>`);
    html.push(`<li>Submit choice filling / document upload as required.</li>`);
    html.push(`<li>Take a printout of the confirmation for records.</li>`);
    html.push(`</ol>`);
  } else if (!isDocument) {
    // Job / Online Form
    html.push(`<h2>How to Apply Online</h2><ol>`);
    html.push(`<li>Click the official application link provided below.</li>`);
    html.push(`<li>Register with your basic details (Name, Email, Mobile).</li>`);
    html.push(`<li>Fill the application form with personal, educational and address information.</li>`);
    html.push(`<li>Upload scanned photograph, signature and required documents.</li>`);
    html.push(`<li>Pay the application fee online (if applicable).</li>`);
    html.push(`<li>Submit the form and save the confirmation receipt.</li>`);
    html.push(`</ol>`);
  }

  // Important Links
  if (importantLinks.length > 0) {
    html.push(`<h2>Important Links</h2><ul>`);
    for (const l of importantLinks) {
      html.push(`<li><a href="${l.url}" target="_blank" rel="noopener noreferrer">${l.label}</a></li>`);
    }
    html.push(`</ul>`);
  }

  // FAQ — 100% original content
  html.push(`<h2>Frequently Asked Questions (FAQ)</h2>`);
  html.push(`<h3>What is ${title}?</h3>`);
  if (isResult)    html.push(`<p>${title} is the official result notification published by the concerned authority. Qualified candidates can download their scorecard using the direct link above.</p>`);
  else if (isAdmit) html.push(`<p>${title} is the official hall ticket / admit card issued for the upcoming examination. Candidates must carry it on the day of the exam along with a valid government photo ID.</p>`);
  else if (isAnswerKey) html.push(`<p>${title} contains the official answers to the recently conducted examination. Candidates can use it to estimate their marks and raise objections if needed.</p>`);
  else              html.push(`<p>${title} is an official government recruitment / examination notification. Complete details including eligibility, important dates, and direct links are provided above.</p>`);

  html.push(`<h3>Where can I find the official link?</h3>`);
  const officialLink = importantLinks.find(l => /official|website|portal/i.test(l.label));
  if (officialLink) {
    html.push(`<p>The official link is: <a href="${officialLink.url}" target="_blank" rel="noopener noreferrer">${officialLink.url}</a></p>`);
  } else {
    html.push(`<p>All official links are provided in the Important Links section above on this page.</p>`);
  }

  if (isResult) {
    html.push(`<h3>How to check the result?</h3>`);
    html.push(`<p>Visit the official website, click the result link, enter your roll number and date of birth, and download your scorecard.</p>`);
  } else if (isAdmit) {
    html.push(`<h3>How to download the Admit Card?</h3>`);
    html.push(`<p>Click on the direct download link above, enter your registration details, and save the admit card PDF.</p>`);
  } else {
    html.push(`<h3>How to apply online?</h3>`);
    html.push(`<p>Click on the Apply Online link given above, register on the official portal, fill the form, upload documents and pay the fee before the last date.</p>`);
  }

  return { intro, fullContentHtml: html.join("\n") };
}

// ── Build JSON-LD for a post ──────────────────────────────────────────────────
function buildJsonLd(title, slug, category, intro, importantLinks) {
  const postUrl  = `${SITE_URL}/post/${slug}`;
  const catLabel = { results:"Result", admitCards:"Admit Card", answerKeys:"Answer Key", admissions:"Admission", documents:"Documents", latestJobs:"Latest Jobs" }[category] || "Sarkari Exam";
  const catPath  = { results:"result", admitCards:"admit-card", answerKeys:"answer-key", admissions:"admission", documents:"documents", latestJobs:"latest-jobs" }[category] || "latest-jobs";
  const ogImg    = `${SITE_URL}/api/og?title=${encodeURIComponent(title)}`;

  const faqItems = [];
  const isResult = category === "results";
  const isAdmit  = category === "admitCards";

  faqItems.push({
    "@type": "Question",
    "name": `What is ${title}?`,
    "acceptedAnswer": { "@type": "Answer", "text": isResult
      ? `${title} is the official result announced by the concerned authority. Candidates can check their status and download the scorecard from the official link.`
      : isAdmit
      ? `${title} is the official hall ticket issued for the upcoming examination. Candidates must carry it to the exam centre.`
      : `${title} is an official government exam notification. Complete details are available on this page.` }
  });

  faqItems.push({
    "@type": "Question",
    "name": `Where can I find the official link for ${title}?`,
    "acceptedAnswer": { "@type": "Answer", "text": `All official and direct links for ${title} are available in the Important Links section on this page at ${SITE_URL}/post/${slug}.` }
  });

  faqItems.push({
    "@type": "Question",
    "name": isResult ? `How to check ${title}?` : isAdmit ? `How to download ${title}?` : `How to apply for ${title}?`,
    "acceptedAnswer": { "@type": "Answer", "text": isResult
      ? "Visit the official website, click the result link, enter your roll number and date of birth, then download your scorecard."
      : isAdmit
      ? "Click the admit card link above, enter your registration details, and save the admit card PDF to carry on exam day."
      : "Click the Apply Online link, register on the official portal, fill the form, upload documents, pay the fee and submit before the last date." }
  });

  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": postUrl,
        "url": postUrl,
        "name": `${title} | ${SITE_NAME}`,
        "description": (intro || title).slice(0, 200),
        "inLanguage": "en-IN",
        "isPartOf": { "@id": `${SITE_URL}/#website` },
        "primaryImageOfPage": { "@type": "ImageObject", "url": ogImg },
        "datePublished": new Date().toISOString().split("T")[0],
        "dateModified":  new Date().toISOString().split("T")[0],
        "author": { "@type": "Organization", "name": SITE_NAME, "url": SITE_URL }
      },
      {
        "@type": "FAQPage",
        "@id": `${postUrl}#faq`,
        "url": `${postUrl}#faq`,
        "mainEntity": faqItems
      },
      {
        "@type": "BreadcrumbList",
        "@id": `${postUrl}#breadcrumb`,
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Home",    "item": `${SITE_URL}/` },
          { "@type": "ListItem", "position": 2, "name": catLabel,  "item": `${SITE_URL}/${catPath}` },
          { "@type": "ListItem", "position": 3, "name": title,     "item": postUrl }
        ]
      }
    ]
  };
}

// ── Date helpers ──────────────────────────────────────────────────────────────
function isValidPastDate(val) {
  if (!val) return false;
  const d = new Date(val);
  return !isNaN(d.getTime()) && d.getTime() <= Date.now();
}

function preserveDates(slug, newPublishedDate) {
  const now    = new Date().toISOString();
  const oldPath = `${POSTS_DIR}/${slug}.json`;
  if (existsSync(oldPath)) {
    try {
      const old = JSON.parse(readFileSync(oldPath, "utf8"));
      const oldAt   = isValidPastDate(old.publishedAt)   ? old.publishedAt   : (isValidPastDate(old.createdAt) ? old.createdAt : null);
      const oldDate = isValidPastDate(old.publishedDate) ? old.publishedDate : null;
      if (oldAt || oldDate) {
        return {
          publishedAt:   oldAt || (oldDate ? new Date(oldDate).toISOString() : now),
          createdAt:     isValidPastDate(old.createdAt) ? old.createdAt : (oldAt || now),
          publishedDate: oldDate || (oldAt ? new Date(oldAt).toLocaleDateString("en-IN", { day:"numeric", month:"long", year:"numeric" }) : now),
          updatedAt:     now,
        };
      }
    } catch {}
  }
  // New post
  const pAt = (newPublishedDate && isValidPastDate(newPublishedDate)) ? new Date(newPublishedDate).toISOString() : now;
  return { publishedAt: pAt, createdAt: pAt, publishedDate: newPublishedDate || now, updatedAt: pAt };
}

// ── Main ──────────────────────────────────────────────────────────────────────
const __timers = new Set();

async function main() {
  const start = Date.now();
  console.log("🔄 AI Exam Result Sync — sarkariexam.com only");
  console.log("   Zero source traces · AIExamResult style content\n");

  const existing    = loadData();
  const existingUrls = new Set();
  for (const cat of CATEGORIES) {
    for (const item of (existing[cat] || [])) {
      if (item.url) existingUrls.add(item.url.replace(/\/$/, ""));
    }
  }
  if (!existing.posts) existing.posts = {};

  // ── Scrape homepage ──
  console.log("[1/3] Scraping sarkariexam.com listings...");
  let fresh;
  try {
    fresh = await scrapeListings();
  } catch (e) {
    console.error("  ❌ Failed to scrape listings:", e.message);
    process.exit(1);
  }

  // Merge new items
  const newItems = [];
  for (const cat of CATEGORIES) {
    for (const item of (fresh[cat] || [])) {
      if (isJunk(item.title, item.sourceUrl)) continue;
      const finalCat = categorize(item.title, cat);
      item.category  = finalCat;
      item.slug      = generateSlug(item.sourceUrl, item.title);
      const pubUrl   = `/post/${item.slug}`;
      if (!existingUrls.has(pubUrl)) {
        const bucket = existing[finalCat] || (existing[finalCat] = []);
        bucket.unshift({ title: item.title, url: pubUrl, category: finalCat, slug: item.slug });
        existingUrls.add(pubUrl);
        newItems.push(item);
      }
    }
  }
  console.log(`  ✓ ${newItems.length} new posts found`);

  // ── Re-scrape existing empty posts ──
  const reScrapeQueue = [];
  for (const file of readdirSync(POSTS_DIR).filter(f => f.endsWith(".json"))) {
    try {
      const p = JSON.parse(readFileSync(`${POSTS_DIR}/${file}`, "utf8"));
      const isEmpty = (!p.intro || p.intro.length < 20) && (!p.fullContentHtml || p.fullContentHtml.length < 50);
      if (isEmpty && p.url && p.url.includes("sarkariexam.com")) {
        reScrapeQueue.push({ file, sourceUrl: p.url, slug: p.slug || file.replace(".json",""), title: p.title || "", category: p.category || "latestJobs" });
      }
    } catch {}
  }
  if (reScrapeQueue.length > 0) console.log(`  ✓ ${reScrapeQueue.length} empty posts queued for re-scrape`);

  // ── Fetch details for new posts ──
  mkdirSync(POSTS_DIR, { recursive: true });
  const newSlugs = [];
  let detailCount = 0;

  console.log("\n[2/3] Fetching post details...");

  async function processItem(item) {
    const detail = await scrapeDetail(item.sourceUrl, item.title, item.category);
    if (!detail) return;

    const cat      = categorize(item.title, item.category);
    const { intro, fullContentHtml } = buildPostContent(item.title, cat, detail);
    const dates    = preserveDates(item.slug, detail.publishedDate);
    const jsonLd   = buildJsonLd(item.title, item.slug, cat, intro, detail.importantLinks);
    const seoTitle = `${item.title} | ${SITE_NAME}`;

    const post = {
      title:          item.title,
      slug:           item.slug,
      category:       cat,
      publishedDate:  dates.publishedDate,
      publishedAt:    dates.publishedAt,
      createdAt:      dates.createdAt,
      updatedAt:      dates.updatedAt,
      intro,
      importantDates: detail.importantDates,
      applicationFee: detail.applicationFee,
      importantLinks: detail.importantLinks,
      fullContentHtml,
      jsonLd,
      seoMeta: {
        title:       seoTitle,
        description: intro.slice(0, 200),
        canonical:   `${SITE_URL}/post/${item.slug}`,
      },
    };

    // Update listing item dates
    const bucket = existing[cat] || [];
    const idx    = bucket.findIndex(b => b.slug === item.slug);
    if (idx !== -1) {
      bucket[idx] = { ...bucket[idx], publishedDate: dates.publishedDate, publishedAt: dates.publishedAt };
      existing[cat] = bucket;
    }
    existing.posts[item.slug] = {
      publishedDate: dates.publishedDate,
      publishedAt:   dates.publishedAt,
      lastDate:      detail.importantDates.find(d => /last/i.test(d))?.replace(/^[^:]+:\s*/, "").trim(),
    };

    writeFileSync(`${POSTS_DIR}/${item.slug}.json`, JSON.stringify(post, null, 2), "utf8");
    newSlugs.push(item.slug);
    detailCount++;
  }

  // Batch with concurrency
  const allToProcess = [...newItems, ...reScrapeQueue];
  const overallTimer = setTimeout(() => {
    console.log(`\n  ⚠️  Detail fetch timeout (${MAX_DETAIL_TIME/1000}s) reached — saving partial results`);
  }, MAX_DETAIL_TIME);
  __timers.add(overallTimer);

  for (let i = 0; i < allToProcess.length; i += CONCURRENCY) {
    const batch   = allToProcess.slice(i, i + CONCURRENCY);
    await Promise.allSettled(batch.map(item => processItem(item).catch(() => {})));
    const pct = Math.min(100, Math.round(((i + batch.length) / allToProcess.length) * 100));
    process.stdout.write(`\r  ${Math.min(i + CONCURRENCY, allToProcess.length)}/${allToProcess.length} (${pct}%) — ${detailCount} done`);
  }
  console.log("");

  clearTimeout(overallTimer);
  __timers.delete(overallTimer);
  for (const t of __timers) clearTimeout(t);
  __timers.clear();

  // Trim each category list
  for (const cat of CATEGORIES) {
    existing[cat] = (existing[cat] || []).slice(0, 500);
  }

  // ── Save ──
  console.log("\n[3/3] Saving data...");
  saveData(existing);
  const elapsed = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`✅ Done in ${elapsed}s — ${newItems.length} new posts, ${detailCount} details written`);

  // ── IndexNow ──
  if (newSlugs.length > 0) {
    try {
      const urlList = [`${SITE_URL}/`, ...newSlugs.slice(0, 99).map(s => `${SITE_URL}/post/${s}`)];
      const res = await fetch("https://api.indexnow.org/indexnow", {
        method: "POST",
        headers: { "Content-Type": "application/json; charset=utf-8" },
        body: JSON.stringify({ host: SITE_HOST, key: INDEXNOW_KEY, keyLocation: `${SITE_URL}/${INDEXNOW_KEY}.txt`, urlList }),
      });
      console.log(`✅ IndexNow: ${urlList.length} URLs submitted (status ${res.status})`);
    } catch (err) {
      console.log(`⚠️  IndexNow failed: ${err.message}`);
    }
  }
}

main().catch(e => { console.error("Fatal error:", e.message); process.exit(1); });
