/**
 * AIExamResult.com - Content Update Engine
 * Detects revised exam/recruitment dates, links, or statuses on existing articles
 * and updates them surgically without changing their permanent URL or canonical slug.
 */

import { existsSync, readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const POSTS_DIR = resolve(__dirname, "../../data/posts");
const SCRAPED_JSON = resolve(__dirname, "../../data/scraped.json");
const SCRAPED_DATA_TS = resolve(__dirname, "../../data/scraped-data.ts");

export async function updateExistingPost(slug, updates = {}) {
  const filePath = resolve(POSTS_DIR, `${slug}.json`);
  if (!existsSync(filePath)) {
    return { success: false, reason: `Post file '${slug}.json' not found.` };
  }

  let post;
  try {
    let raw = readFileSync(filePath, "utf8");
    if (raw.charCodeAt(0) === 0xfeff) raw = raw.substring(1);
    post = JSON.parse(raw);
  } catch (err) {
    return { success: false, reason: `Failed to parse post JSON: ${err.message}` };
  }

  const nowIso = new Date().toISOString();
  post.updatedAt = nowIso;

  // Surgical updates
  if (Array.isArray(updates.importantDates) && updates.importantDates.length > 0) {
    post.importantDates = updates.importantDates;
  }
  if (Array.isArray(updates.importantLinks) && updates.importantLinks.length > 0) {
    post.importantLinks = updates.importantLinks;
  }
  if (updates.lastDate) {
    post.lastDate = updates.lastDate;
  }
  if (updates.fullContentHtml) {
    post.fullContentHtml = updates.fullContentHtml;
  }

  // Update Schema dateModified
  if (post.jsonLd && Array.isArray(post.jsonLd["@graph"])) {
    for (const node of post.jsonLd["@graph"]) {
      if (node["@type"] === "WebPage" || node["@type"] === "Article") {
        node.dateModified = nowIso;
      }
    }
  }

  // Save updated post
  writeFileSync(filePath, JSON.stringify(post, null, 2), "utf8");

  // Sync scraped.json
  if (existsSync(SCRAPED_JSON)) {
    try {
      const data = JSON.parse(readFileSync(SCRAPED_JSON, "utf8"));
      if (data.posts && data.posts[slug]) {
        data.posts[slug] = {
          ...data.posts[slug],
          lastDate: post.lastDate,
          updatedAt: nowIso,
        };
      }
      data.fetchedAt = nowIso;
      const jsonStr = JSON.stringify(data, null, 2);
      writeFileSync(SCRAPED_JSON, jsonStr, "utf8");
      writeFileSync(SCRAPED_DATA_TS, `// Auto-generated by clean sync - DO NOT EDIT\nexport const scrapedData = ${jsonStr};\n`, "utf8");
    } catch {}
  }

  console.log(`✅ Successfully updated post: /post/${slug} (dateModified: ${nowIso})`);
  return { success: true, slug, updatedAt: nowIso };
}
